// The moving "how this works" hints, one per product and one per console idea that is not obvious. Built on Vanik UI (vanik-ui.js).
const mi = n => `<span class="mi material-icons">${n}</span>`, S = (icon, label, text) => ({ icon: mi(icon), label, text });
const H = {
  'console-apps': ['How apps get to people', [S('add_circle', 'Add', 'Pick an app. One click.'), S('auto_fix_high', 'It wires itself', 'The model, database, storage and key are set up for it.'), S('group', 'Choose who', 'Give it to everyone, a team or a few people, with a role.'), S('apps', 'They open it', 'It appears under My apps. No second sign-in.')]],
  'console-access': ['How access works', [S('person', 'A person', 'Invited by email, or picked up from your directory.'), S('groups', 'Their team', 'A team carries apps, roles and documents.'), S('apps', 'An app', 'Each app can be open to everyone, to teams, or to a few people.'), S('badge', 'A role', 'The app names its own roles. A role on a person beats a role on their team.')]],
  'console-knowledge': ['How documents are shared', [S('lock', 'My documents', 'Anything you add is private until you share it.'), S('groups', 'Team', 'Each team has a space its members can read and add to.'), S('domain', 'Company', 'General documents that everyone can read.'), S('rule', 'The rule', 'An answer uses only what the asker can read and the app is allowed to use.')]],
  gpt: ['How VanikGPT answers', [S('chat', 'Ask', 'Type a question in your own words.'), S('search', 'It looks', 'Only in documents you can read: yours, your team\'s, the company\'s.'), S('fact_check', 'It answers', 'With the passages it used, so you can check.'), S('block', 'Or says so', 'When there is no source it says "not found" and does not guess.')]],
  sense: ['How Vanik Sense works', [S('event', 'Your meeting', 'Any Teams meeting on your calendar. You do nothing.'), S('notes', 'Minutes', 'After it ends: outcome, decisions, and who owes what.'), S('task_alt', 'Actions', 'Each goes to the person named. Fix an owner or a date in one click.'), S('mail', 'Follow-up', 'One email a day: overdue, due tomorrow, due this week.'), S('lock', 'Private', 'Only the people who were in a meeting can open it.')]],
  scout: ['How Scout ranks people', [S('upload_file', 'Add resumes', 'Drop files into a job posting. Duplicates are refused.'), S('edit_note', 'Describe', 'A few words or the whole job description.'), S('tune', 'Check its reading', 'Must-haves show as chips. Change one and the list re-runs.'), S('format_list_numbered', 'Ranked', 'Each person shows what they have, what they lack, and how they were found.'), S('share', 'Share', 'Send the shortlist to the hiring manager.')]],
  measurebook: ['How a takeoff is made', [S('upload_file', 'Drop drawings', 'One sheet or a whole tender set.'), S('layers', 'Read four ways', 'Text, drawn lines, symbols and standard sizes, each with a confidence.'), S('rule', 'Review', 'Start with the least certain rows. Click a row to see it on the drawing.'), S('payments', 'Price', 'Pick a rate book for a priced bill.'), S('verified', 'Approve', 'Lock the bill, then export it.')]],
  idp: ['How a document becomes data', [S('upload_file', 'Drop', 'Invoices, orders, e-way bills.'), S('document_scanner', 'Read', 'Fields are read by document type.'), S('fact_check', 'Checked', 'Tax numbers, totals and duplicates.'), S('edit', 'Fix', 'Only the fields that are marked.'), S('verified', 'Approve', 'Then export as a sheet or JSON.')]],
  desk: ['How a request is answered', [S('inbox', 'It arrives', 'A request lands in one queue.'), S('timer', 'A timer starts', 'For the first reply and for solving it.'), S('auto_awesome', 'A draft', 'Written from your documents, with its sources.'), S('send', 'You send', 'Edit and send. The timer stops.')]],
  echo: ['How a room meeting is captured', [S('mic', 'Start', 'One button. Place the laptop where it can hear everyone.'), S('graphic_eq', 'Speak', 'Each line appears after a pause, with who said it.'), S('stop_circle', 'End', 'The transcript is kept on the appliance.'), S('send', 'Hand over', 'Send it to Vanik Sense for minutes and actions.')]],
};
const UI = window.VanikUI;
if (UI) for (const [id, [title, steps]] of Object.entries(H)) UI.hint.define(id, { title, steps });
export const hint = id => (UI && H[id] ? UI.hint.tag(id) : '');
