// The console after the audit of the real Vanik OS: seven places for an admin, each page answering one question,
// and a home of their own for people who are not admins. This file holds the pages that were rebuilt or are new:
// Home, Appliance (overview, updates and power, advanced), Activity, Sources, Connected systems, People, Train,
// Notifications, Help, and the user's home at #/me.
import { S, $, esc, icon, info, chip, go, ago, when, api, refresh, rerender, acts, ins, toast, modal, confirmBox, menu, navToggle, downloadText, initials, ROLE, themeButton, userButton, LOGO, accessLabel, pickFiles } from './core.js';
import { osShell, uploadFiles } from './os.js';
import { hero, edgeNeed } from './edge.js';
import { appsCard, setupBanner, suiteNeed } from './suite.js';
import { platformState, platformEnsure } from './platform.js';
import { apiPage } from './edge.js';

const Q = { days: 7, ptab: 'all', pq: '', aq: '' };
export const planeRouteChanged = () => { Object.keys(Q).forEach(k => { if (k.endsWith('Key')) Q[k] = ''; }); };
const get = (slot, key, path) => { if (Q[slot + 'Key'] !== key) { Q[slot + 'Key'] = key; api('GET', path).then(d => { if (Q[slot + 'Key'] === key) { Q[slot] = d; rerender(); } }).catch(e => toast(e.message, 'err')); } return Q[slot]; };
const reload = slot => { Q[slot + 'Key'] = ''; rerender(); };
const head = (title, sub, right = '') => `<div class="page-head"><div class="grow"><h1>${title}</h1>${sub ? `<p class="sub">${sub}</p>` : ''}</div>${right}</div>`;
const dot = st => `<span class="hdot ${st}"></span>`;
const copy = t => `<button class="icon-btn sm" data-act="copy" data-text="${esc(t)}" data-tip="Copy" aria-label="Copy">${icon('content_copy')}</button>`;
const meter = (used, total) => `<div class="meter"><i style="width:${Math.min(100, Math.max(1, 100 * used / (total || 1))).toFixed(1)}%"></i></div>`;
const loading = '<p class="muted">Loading…</p>';
const n = (c, w) => `${c} ${w}${c === 1 ? '' : 's'}`;

// ================= Home: is it all right, what should I do now, is it being used =================
function pageHome() {
  const B = S.boot, d = B.device, h = new Date().getHours(), att = B.attention, first = att[0], use = get('use7', 'use7', '/api/plane/activity?days=7'), e = edgeNeed(); suiteNeed();
  return osShell('home', 'Home', head(`${h < 12 ? 'Good morning' : h < 17 ? 'Good afternoon' : 'Good evening'}, ${esc(B.me.name.split(' ')[0])}`, att.length ? `${n(att.length, 'thing')} ${att.length === 1 ? 'needs' : 'need'} you.` : 'Everything is running. Nothing needs you.')
    + setupBanner() + hero()
    + (first ? `<div class="card next"><span class="cap">Do this next</span><div class="row" style="margin-top:8px"><div class="grow"><h3>${esc(first.text)}</h3></div><a class="btn lg" href="${esc(first.href)}">${esc(first.action)}</a></div></div>` : '')
    + `<div class="grid two" style="align-items:start;margin-top:16px"><div class="stack" style="gap:16px">
        ${att.length > 1 ? `<div class="card"><div class="card-head"><h3>Also needs attention</h3><span class="mono">${att.length - 1}</span></div>${att.slice(1).map(x => `<div class="set-row">${dot('warn')}<span class="grow">${esc(x.text)}</span><a class="btn ghost" href="${esc(x.href)}">${esc(x.action)}</a></div>`).join('')}</div>` : ''}
        ${appsCard() || `<div class="card"><p class="muted">Nothing installed yet. <a class="link" href="#/os/apps">Open Apps</a></p></div>`}</div>
      <div class="stack" style="gap:16px">
        <div class="card"><div class="card-head"><h3>This week</h3><a class="btn ghost right" href="#/os/activity">Activity</a></div>${!use ? loading : `<div class="grid three"><div class="stat"><span class="k">Questions asked</span><b>${use.questions}</b></div><div class="stat"><span class="k">People active</span><b>${use.activePeople}</b><span class="small muted">of ${B.users.length}</span></div><div class="stat"><span class="k">API requests</span><b>${use.apiRequests.toLocaleString('en-IN')}</b><span class="small muted">all time</span></div></div>`}</div>
        <div class="card"><div class="card-head"><h3>Capacity</h3><a class="btn ghost right" href="#/os/devices">Appliance</a></div>
          <div class="row"><span class="cap grow">GPU memory</span><span class="small muted">${d.usedGb} of ${d.memGb} GB · ${d.freeGb} GB free</span></div>${meter(d.usedGb, d.memGb)}
          <div class="row" style="margin-top:14px"><span class="cap grow">Models serving</span><span class="small muted">${d.serving} of ${d.slots} slots</span></div>${meter(d.serving, d.slots)}
          ${e ? `<div class="row" style="margin-top:14px"><span class="cap grow">Disk</span><span class="small muted">${e.storage.used} of ${e.storage.total.toLocaleString('en-IN')} GB</span></div>${meter(e.storage.used, e.storage.total)}` : ''}</div></div></div>`);
}

// ================= Appliance =================
const DSTATE = { online: ['Online', 'ok'], offline: ['Offline', 'err'], waiting: ['Waiting for its first check-in', 'warn'] };
const showCommand = (title, r) => modal({ title, wide: true, cancel: 'Done', text: 'Run this once on the device. The code in it is shown now and never again; only its fingerprint is kept. This build has no second device to answer, so it stays waiting.', body: `<pre class="code" style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(r.command)}</pre><div class="row" style="margin-top:10px"><span class="grow"></span><button class="btn ghost" data-act="copy" data-text="${esc(r.command)}">${icon('content_copy')}Copy the command</button></div>` });
acts['dev-new'] = () => modal({ title: 'Register a device', text: 'Step 1 of 2. Name the device. Step 2 gives you one command to run on it.', body: `<div class="stack" style="gap:12px"><label class="field"><span>Name</span><input class="input" id="dv-name" maxlength="40" placeholder="Plant 2 server"></label><label class="field"><span>Hostname ${info('Optional. The device reports it by itself when it first checks in.')}</span><input class="input" id="dv-host" placeholder="plant2-ai"></label></div>`, actions: [{ label: 'Continue', run: async o => { const r = await api('POST', '/api/plane/devices', { name: $('#dv-name', o).value, hostname: $('#dv-host', o).value }); reload('devs'); setTimeout(() => showCommand('Step 2 of 2: run this on ' + r.device.name, r), 50); } }] });
acts['dev-menu'] = el => { const d = Q.devs.find(x => x.id === el.dataset.id); menu(el, [{ label: 'Rename', icon: 'edit', run: () => modal({ title: 'Rename ' + d.name, body: `<input class="input" id="dv-name" maxlength="40" value="${esc(d.name)}" aria-label="Name">`, actions: [{ label: 'Save', run: async o => { await api('PATCH', '/api/plane/devices/' + d.id, { name: $('#dv-name', o).value }); reload('devs'); await refresh(); } }] }) },
  ...(d.primary ? [] : [{ label: 'New install command', icon: 'terminal', run: () => confirmBox('Make a new install command?', 'Any command copied earlier for this device stops working.', 'Make a new one', async () => { const r = await api('POST', `/api/plane/devices/${d.id}/token`); reload('devs'); showCommand('Run this on ' + d.name, r); }, false) }, '-',
    { label: 'Delete device', icon: 'delete_outline', danger: true, run: async () => { const im = await api('GET', `/api/plane/devices/${d.id}/impact`); confirmBox(`Delete ${d.name}?`, im.why + ' Its install command stops working.', 'Delete', async () => { await api('DELETE', '/api/plane/devices/' + d.id); reload('devs'); }); } }])]); };
function pageAppliance() {
  const B = S.boot, d = B.device, devs = get('devs', 'devs', '/api/plane/devices'), s = suiteNeed(), e = edgeNeed(); platformEnsure('devices', false); const D = platformState.data;
  const word = { ok: 'ok', down: 'err', idle: '' };
  return osShell('devices', 'Appliance', head('Appliance', 'The hardware this tenant runs on: how healthy it is and how full.', `<button class="btn" data-act="dev-new">${icon('add')}Register a device</button>`)
    + `<div class="grid two" style="align-items:start"><div class="card"><div class="row"><span class="avatar sq">${icon('dns')}</span><div class="grow"><h3>${esc(d.name)}</h3><div class="small muted">Vanik OS ${esc(d.agent)} · <span class="mono">${esc(d.ip)}</span></div></div>${chip(d.online ? 'Online' : 'Offline', d.online ? 'ok' : 'err')}</div>
        <div class="row" style="margin-top:16px"><span class="cap grow">GPU memory</span><span class="small muted">${d.usedGb} of ${d.memGb} GB</span></div>${meter(d.usedGb, d.memGb)}
        <div class="row" style="margin-top:12px"><span class="cap grow">Models serving</span><span class="small muted">${d.serving} of ${d.slots} slots</span></div>${meter(d.serving, d.slots)}
        ${e ? `<div class="row" style="margin-top:12px"><span class="cap grow">Disk</span><span class="small muted">${e.storage.used} of ${e.storage.total.toLocaleString('en-IN')} GB</span></div>${meter(e.storage.used, e.storage.total)}` : ''}</div>
      <div class="card">${!s ? loading : `<span class="cap">Plan</span><h3 style="margin-top:6px">${esc(s.plan.tier)}</h3><p class="small muted">${s.plan.used} of ${s.plan.people} people · renews ${esc(new Date(s.plan.renewsOn).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }))}</p>${meter(s.plan.used, s.plan.people)}<p class="small faint" style="margin-top:10px">Every app in the store is included. To add people or change the device, talk to Vanik.</p>`}</div></div>
    <div class="card" style="margin-top:16px"><div class="card-head"><h3>Devices</h3>${info('The first is the one this console runs on. Others join with a one-time command and then show here with their own health.')}</div>
      ${!devs ? loading : devs.map(x => { const st = DSTATE[x.status]; return `<div class="set-row">${dot(st[1])}<div class="grow"><div class="lbl">${esc(x.name)}${x.primary ? ' <span class="faint small">runs this console</span>' : ''}</div><div class="small muted">${x.primary ? `${n(x.apps, 'app')} · ${n(x.models, 'model')} serving · ${x.usedGb} of ${x.memGb} GB` : `Registered ${ago(x.createdAt)} by ${esc(x.by)}${x.hostname ? ' · ' + esc(x.hostname) : ''}`}</div></div>${chip(st[0], st[1], false)}<button class="icon-btn sm" data-act="dev-menu" data-id="${x.id}" aria-label="More">${icon('more_vert')}</button></div>`; }).join('')}</div>
    <div class="card" style="margin-top:16px"><div class="card-head"><h3>Checks</h3>${info('Each is tested every few seconds from this console.')}</div>${!D ? loading : D.probes.map(p => `<div class="set-row">${dot(word[p.state])}<div class="grow"><div class="lbl">${esc(p.name)}</div><div class="small muted">${esc(p.detail)}</div></div></div>`).join('')}</div>`);
}
function pageUpdates() {
  const B = S.boot, d = B.device, e = edgeNeed(), s = suiteNeed();
  if (!e || !s) return osShell('settings', 'Updates and power', head('Updates and power', '') + loading);
  const u = e.updates, r = s.recovery, row = (label, sub, btn) => `<div class="set-row"><div class="grow"><div class="lbl">${label}</div><div class="small muted">${sub}</div></div>${btn}</div>`;
  return osShell('settings', 'Updates and power', head('Updates and power', 'Keep Vanik OS current, and switch the appliance off or on.')
    + `<div class="stack" style="max-width:820px;gap:16px">
      <div class="card"><div class="row"><div class="grow"><h3>${u.latest === u.version ? 'Vanik OS is up to date' : 'An update is ready'}</h3><p class="small muted">Version ${esc(u.version)}${u.checkedAt ? ' · checked ' + ago(u.checkedAt) : ''}</p></div><button class="btn ghost" data-act="up-check">Check again</button></div>
        ${row('Go back to the version before', u.previous.length ? 'Version ' + esc(u.previous[0]) + '. Apps and data are kept.' : 'No earlier version on this appliance.', `<button class="btn ghost" data-act="up-back" ${u.previous.length ? '' : 'disabled'}>Roll back</button>`)}</div>
      <div class="card"><div class="card-head"><h3>Power</h3></div>
        ${row(d.online ? 'Take it offline' : 'Bring it back online', d.online ? 'Stops every app and model. Nobody can use it until you bring it back. Data is kept.' : 'It is offline now. Apps and models are stopped.', `<button class="btn ${d.online ? 'ghost' : ''}" data-act="device-toggle">${d.online ? 'Go offline' : 'Go online'}</button>`)}
        ${row('Restart', 'Apps and models stop for a few seconds, then come back.', `<button class="btn ghost" data-act="pw" data-v="restart">Restart</button>`)}
        ${row('Shut down', 'Stays off until someone powers it on.', `<button class="btn danger" data-act="pw" data-v="shutdown">Shut down</button>`)}
        ${row(`Factory reset ${info('Erases people, chats, documents and downloaded models. Vanik OS stays. This build asks for the confirmation but does not erase anything.')}`, 'Erases everything except Vanik OS.', `<button class="btn danger" data-act="pw" data-v="reset">Reset</button>`)}</div>
      <div class="card"><div class="card-head"><h3>Getting back in</h3></div>
        ${row('Recovery key', r ? `Made ${ago(r.createdAt)} by ${esc(r.by)}. Only its fingerprint is kept here.` : 'None yet. Without one, a locked-out owner cannot get back in.', `${r ? `<button class="btn ghost" data-act="rk-check">Check a key</button>` : ''}<button class="btn ${r ? 'ghost' : ''}" data-act="rk-new">${r ? 'Make a new key' : 'Make a key'}</button>`)}
        ${row('Set-up', s.setup ? 'Finished ' + ago(s.setup.doneAt) + ' by ' + esc(s.setup.by) : 'Not finished', `<a class="btn ghost" href="#/os/welcome">${s.setup ? 'Run again' : 'Set up'}</a>`)}</div></div>`);
}
function pageAdvanced() {
  const B = S.boot, s = suiteNeed(); platformEnsure('devices', true); const D = platformState.data;
  const ports = [...(B.app.status !== 'not_installed' ? [[B.app.port, 'VanikGPT', 'App']] : []), ...(s ? s.apps.filter(a => a.status !== 'not_installed').map(a => [a.port, a.name, 'App']) : []), ...B.models.filter(m => m.port).map(m => [m.port, m.id, 'Model'])].sort((a, b) => a[0] - b[0]);
  return osShell('devices', 'Advanced', head('Advanced', 'For Vanik support engineers: what the device was told to do, and which port serves what.')
    + `<div class="card" style="margin-bottom:16px"><div class="card-head"><h3>Commands sent to the device</h3>${info('Every install, deploy, serve and park is a command the device agent picks up.')}</div>${!D ? loading : D.commands.length ? D.commands.map(c => `<div class="set-row" style="align-items:flex-start">${dot(c.result === 'ok' ? 'ok' : c.result === 'failed' ? 'err' : c.result === 'cancelled' ? '' : 'warn')}<div class="grow"><div class="lbl">${esc(c.type)} <span class="mono">${esc(c.target)}</span></div><div class="small muted">${when(c.startedAt)} · ${esc(c.by)}${c.endedAt ? ' · took ' + Math.max(1, Math.round((new Date(c.endedAt) - new Date(c.startedAt)) / 1000)) + ' s' : ''}</div>${c.reason && c.result !== 'ok' ? `<details class="adv"><summary class="small">Why it did not finish</summary><div class="small" style="margin-top:6px">${esc(c.reason)}</div></details>` : ''}</div>${chip(c.result === 'ok' ? 'Done' : c.result === 'failed' ? 'Did not finish' : c.result === 'cancelled' ? 'Cancelled' : 'In progress', c.result === 'ok' ? 'ok' : c.result === 'failed' ? 'err' : c.result ? '' : 'warn', false)}</div>`).join('') : '<p class="muted">No commands yet.</p>'}</div>
    <div class="card"><div class="card-head"><h3>Ports in use</h3>${info('Read-only. Models take 9000 to 9005, apps from 9006.')}</div><table class="list"><tr><th>Port</th><th>Serving</th><th>Kind</th></tr>${ports.map(p => `<tr><td class="mono">${p[0]}</td><td>${esc(p[1])}</td><td class="muted">${p[2]}</td></tr>`).join('') || '<tr><td colspan="3" class="muted">Nothing is listening.</td></tr>'}</table></div>`);
}

// ================= Activity: who used what, who changed what =================
acts['act-days'] = el => { Q.days = +el.dataset.v; rerender(); };
acts['act-csv'] = () => downloadText(`usage-last-${Q.use.days}-days.csv`, Q.use.csv, 'text/csv');
acts['audit-csv'] = async () => { const r = await api('GET', '/api/admin/audit/export'); downloadText(r.name + '.csv', r.csv, 'text/csv'); };
ins['audit-q'] = el => { Q.aq = el.value; const box = $('#audit-rows'); if (box) box.innerHTML = auditRows(); };
const auditRows = () => { const q = Q.aq.toLowerCase(), rows = (Q.audit || []).filter(e => !q || (e.userName + ' ' + e.action + ' ' + e.target + ' ' + e.detail).toLowerCase().includes(q)).slice(0, 150); return rows.map(e => `<tr><td class="muted" style="white-space:nowrap">${when(e.at)}</td><td>${esc(e.userName)}</td><td>${esc(e.action)}</td><td class="muted">${esc(e.target)}${e.detail ? `<div class="small faint">${esc(e.detail)}</div>` : ''}</td></tr>`).join('') || '<tr><td colspan="4" class="muted">Nothing matches.</td></tr>'; };
function pageActivity(tab) {
  if (tab === 'audit') {
    const a = get('audit', 'audit', '/api/admin/audit'), v = get('verify', 'verify', '/api/admin/audit/verify');
    return osShell('activity', 'Audit log', head('Audit log', 'Who changed what, newest first. Each entry carries the fingerprint of the one before it.', `${v ? chip(v.ok ? 'Unbroken' : 'Broken at entry ' + v.brokenAt, v.ok ? 'ok' : 'err') : ''}<button class="btn ghost" data-act="audit-csv">${icon('download')}Download</button>`)
      + `<div class="card"><input class="input" style="margin-bottom:12px" placeholder="Search by person, action or thing" value="${esc(Q.aq)}" data-on="audit-q" aria-label="Search the audit log">${!a ? loading : `<table class="list"><tr><th>When</th><th>Who</th><th>Did</th><th>On</th></tr><tbody id="audit-rows">${auditRows()}</tbody></table>`}</div>`);
  }
  const u = get('use', 'use' + Q.days, '/api/plane/activity?days=' + Q.days), max = u ? Math.max(1, ...u.byDay.map(x => x.n)) : 1;
  return osShell('activity', 'Usage', head('Usage', 'Who used what, and how much.', `<div class="seg">${[[1, '24 hours'], [7, '7 days'], [30, '30 days'], [90, '90 days']].map(x => `<button class="${Q.days === x[0] ? 'on' : ''}" data-act="act-days" data-v="${x[0]}">${x[1]}</button>`).join('')}</div>${u ? `<button class="btn ghost" data-act="act-csv">${icon('download')}Download</button>` : ''}`)
    + (!u ? loading : `<div class="grid four" style="margin-bottom:16px"><div class="card flat stat"><span class="k">Questions asked</span><b>${u.questions}</b><span class="small muted">in VanikGPT</span></div><div class="card flat stat"><span class="k">People active</span><b>${u.activePeople}</b><span class="small muted">of ${S.boot.users.length}</span></div><div class="card flat stat"><span class="k">Words handled</span><b>${Math.round(u.tokens * 0.75).toLocaleString('en-IN')}</b><span class="small muted">about ${u.tokens.toLocaleString('en-IN')} tokens</span></div><div class="card flat stat"><span class="k">API requests</span><b>${u.apiRequests.toLocaleString('en-IN')}</b><span class="small muted">all time</span></div></div>
      <div class="card" style="margin-bottom:16px"><div class="card-head"><h3>Questions by day</h3></div><div class="bars">${u.byDay.map(x => `<div class="bar" data-tip="${x.n} on ${x.day}"><i style="height:${Math.max(2, 100 * x.n / max)}%"></i></div>`).join('')}</div><div class="row small faint"><span class="grow">${esc(u.byDay[0].day)}</span><span>${esc(u.byDay[u.byDay.length - 1].day)}</span></div></div>
      <div class="grid two" style="align-items:start"><div class="card"><div class="card-head"><h3>People</h3></div>${u.people.length ? `<table class="list"><tr><th>Person</th><th>Questions</th><th>In other apps</th><th>Last active</th></tr>${u.people.map(p => `<tr><td><b>${esc(p.name)}</b></td><td>${p.questions}</td><td>${p.actions}</td><td class="muted">${ago(p.last)}</td></tr>`).join('')}</table>` : '<p class="muted">Nobody used it in this period.</p>'}</div>
        <div class="stack" style="gap:16px"><div class="card"><div class="card-head"><h3>Apps</h3></div>${u.apps.length ? u.apps.map(a => `<div class="set-row"><div class="grow lbl">${esc(a.name)}</div><span class="muted">${n(a.n, a.name === 'VanikGPT' ? 'question' : 'action')}</span></div>`).join('') : '<p class="muted">No app was used in this period.</p>'}</div>
          <div class="card"><div class="card-head"><h3>API keys</h3>${info('Totals since each key was made. The gateway does not keep a count per day.')}</div>${u.keys.length ? u.keys.map(k => `<div class="set-row"><div class="grow"><div class="lbl">${esc(k.name)}</div><div class="small muted">${k.system ? 'Issued by Vanik OS' : 'Made by ' + esc(k.by)} · ${k.lastUsedAt ? 'last used ' + ago(k.lastUsedAt) : 'never used'}</div></div><span class="muted">${k.requests.toLocaleString('en-IN')} requests</span></div>`).join('') : '<p class="muted">No keys.</p>'}</div></div></div>`));
}

// ================= Knowledge: where documents come from =================
const SICON = { drive: 'add_to_drive', sharepoint: 'grid_view', confluence: 'menu_book' };
const SWHAT = { drive: 'Shared drives and folders, copied into a collection.', sharepoint: 'Document libraries from a Microsoft 365 tenant.', confluence: 'Spaces and pages from Atlassian Confluence.' };
const SFORM = {
  drive: `<label class="field"><span>Service-account key ${info('In Google Cloud: IAM and Admin, Service accounts, create one, then Keys, Add key, JSON. Turn on the Google Drive API for that project. Share the drives or folders with the account.')}</span><textarea class="input mono" id="s-keyFile" rows="3" placeholder="Paste the JSON key file. Use the word sample to try it with sample files."></textarea></label>`,
  sharepoint: `<div class="row" style="gap:12px"><label class="field grow"><span>Directory (tenant) id</span><input class="input" id="s-tenantId" placeholder="contoso.onmicrosoft.com"></label><label class="field grow"><span>Application (client) id</span><input class="input" id="s-clientId" placeholder="00000000-0000-…"></label></div><label class="field"><span>Client secret ${info('In Microsoft Entra ID: App registrations, New registration. Add the Microsoft Graph permission Sites.Read.All and grant admin consent. Create a client secret and paste its value.')}</span><input class="input" id="s-clientSecret" autocomplete="off" placeholder="The secret's value. Use the word sample to try it with sample files."></label><label class="field"><span>Site address ${info('Only needed when the app is allowed chosen sites.')}</span><input class="input" id="s-siteUrl" placeholder="https://contoso.sharepoint.com/sites/hr"></label>`,
  confluence: `<label class="field"><span>Confluence address</span><input class="input" id="s-baseUrl" placeholder="https://your-site.atlassian.net"></label><div class="row" style="gap:12px"><label class="field grow"><span>Account email</span><input class="input" id="s-email" placeholder="you@company.com"></label><label class="field grow"><span>API token ${info('Create one at id.atlassian.com, Security, API tokens. It reads whatever this account can read.')}</span><input class="input" id="s-token" autocomplete="off" placeholder="Use the word sample to try it"></label></div>`,
};
const sCfg = (kind, o) => Object.fromEntries([...o.querySelectorAll('[id^="s-"]')].filter(x => !['s-name', 's-col', 's-every'].includes(x.id)).map(x => [x.id.slice(2), x.value]));
acts['src-new'] = el => {
  const kind = el.dataset.kind, k = Q.src.kinds.find(x => x.id === kind), cols = S.boot.collections;
  if (!cols.length) return modal({ title: 'Make a collection first', text: 'A source is copied into a collection. Create one under Collections, then come back.', actions: [{ label: 'Open Collections', run: () => go('#/os/knowledge') }] });
  const m = modal({ title: 'Connect ' + k.name, wide: true, text: `Files are copied onto the appliance and indexed there. Nothing is written back to ${k.name}. What you enter is stored on the appliance and never shown again.`, body: `<div class="stack" style="gap:12px">${SFORM[kind]}<div class="row"><button class="btn ghost" id="s-test">${icon('network_check')}Test connection</button><span class="small" id="s-result"></span></div>
    <div class="row" style="gap:12px"><label class="field grow"><span>Copy into</span><select class="input" id="s-col">${cols.map(c => `<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label class="field grow"><span>How often</span><select class="input" id="s-every">${Object.entries(Q.src.every).map(([v, l]) => `<option value="${v}" ${v === 'day' ? 'selected' : ''}>${esc(l)}</option>`).join('')}</select></label></div></div>`,
    actions: [{ label: 'Connect and sync', run: async o => { const s = await api('POST', '/api/plane/sources', { kind, config: sCfg(kind, o), collectionId: $('#s-col', o).value, every: $('#s-every', o).value }); toast(s.error || `Connected. ${n(s.stats.added, 'file')} copied in.`, s.error ? 'err' : ''); reload('src'); await refresh(); } }] });
  $('#s-test', m.el).onclick = async () => { const r = await api('POST', '/api/plane/sources/test', { kind, config: sCfg(kind, m.el) }); const out = $('#s-result', m.el); out.textContent = r.detail; out.style.color = r.ok ? 'var(--vnk-ok)' : 'var(--vnk-err)'; };
};
acts['src-sync'] = async el => { try { const s = await api('POST', `/api/plane/sources/${el.dataset.id}/sync`); toast(s.error || 'Checked. Nothing new unless a file changed.', s.error ? 'err' : ''); reload('src'); await refresh(); } catch (e) { toast(e.message, 'err'); } };
acts['src-pause'] = async el => { await api('PATCH', `/api/plane/sources/${el.dataset.id}`, { paused: el.dataset.on === '1' }); reload('src'); };
acts['src-del'] = el => confirmBox('Disconnect this source?', 'Vanik OS stops reading it. Documents already copied stay in the collection.', 'Disconnect', async () => { await api('DELETE', '/api/plane/sources/' + el.dataset.id); reload('src'); });
const SSTATE = { connected: ['Connected', 'ok'], waiting: ['Waiting for its first sync', 'warn'], paused: ['Paused', ''], failed: ['Could not sync', 'err'] };
function pageSources() {
  const src = get('src', 'src', '/api/plane/sources'); platformEnsure('connectors', false); const D = platformState.data;
  const kindCard = k => { const mine = src.sources.filter(s => s.kind === k.id); return `<div class="card" style="margin-bottom:16px"><div class="card-head"><span class="avatar sq">${icon(SICON[k.id])}</span><div class="grow"><h3>${esc(k.name)}</h3><p class="small muted">${SWHAT[k.id]}</p></div><button class="btn ${mine.length ? 'ghost' : ''}" data-act="src-new" data-kind="${k.id}">${mine.length ? 'Connect another' : 'Connect'}</button></div>
    ${mine.map(s => { const st = SSTATE[s.state]; return `<div class="set-row">${dot(st[1])}<div class="grow"><div class="lbl">${esc(s.name)} ${chip(st[0], st[1], false)}</div><div class="small muted">Into <a class="link" href="#/os/knowledge/${s.collectionId}">${esc(s.collection)}</a> · ${esc(s.everyLabel.toLowerCase())} · ${s.syncedAt ? 'checked ' + ago(s.syncedAt) + ' · ' + n(s.stats.added, 'file') + ' copied' : 'not checked yet'}</div>${s.error ? `<div class="small" style="color:var(--vnk-err);margin-top:4px">${esc(s.error)}</div>` : ''}</div><button class="btn ghost" data-act="src-sync" data-id="${s.id}" ${s.paused ? 'disabled' : ''}>Sync now</button><button class="btn ghost" data-act="src-pause" data-id="${s.id}" data-on="${s.paused ? 0 : 1}">${s.paused ? 'Resume' : 'Pause'}</button><button class="icon-btn sm" data-act="src-del" data-id="${s.id}" data-tip="Disconnect" aria-label="Disconnect">${icon('link_off')}</button></div>`; }).join('')}</div>`; };
  return osShell('connectors', 'Sources', head('Sources', 'Where documents come from. They are copied onto the appliance and indexed there; nothing is sent back out.')
    + `<div class="card" style="margin-bottom:16px"><div class="row"><span class="avatar sq">${icon('upload_file')}</span><div class="grow"><h3>From your computer</h3><p class="small muted">PDF, Word, Excel, text, code, scans and recordings, added straight into a collection.</p></div>${chip('Always on', 'ok', false)}<a class="btn ghost" href="#/os/knowledge">Collections</a></div></div>
    <div class="card" style="margin-bottom:16px"><div class="card-head"><span class="avatar sq">${icon('folder_open')}</span><div class="grow"><h3>Folder on the appliance</h3><p class="small muted">A folder or a mounted network share, kept in step with a collection.</p></div><button class="btn ${D && D.connectors.length ? 'ghost' : ''}" data-act="cn-new">${D && D.connectors.length ? 'Connect another' : 'Connect'}</button></div>
      ${!D ? loading : D.connectors.map(c => `<div class="set-row">${dot(c.error ? 'err' : 'ok')}<div class="grow"><div class="lbl"><span class="mono" style="color:var(--vnk-ink)">${esc(c.path)}</span></div><div class="small muted">Into <a class="link" href="#/os/knowledge/${c.collectionId}">${esc(c.collectionName)}</a> · every ${c.everyMinutes} min · ${c.lastSyncAt ? 'checked ' + ago(c.lastSyncAt) : 'not checked yet'}${c.stats ? ` · ${c.stats.files} files` : ''}</div>${c.error ? `<div class="small" style="color:var(--vnk-err);margin-top:4px">${esc(c.error)}</div>` : ''}</div><button class="btn ghost" data-act="cn-sync" data-id="${c.id}">Sync now</button><button class="icon-btn sm" data-act="cn-del" data-id="${c.id}" data-tip="Disconnect" aria-label="Disconnect">${icon('link_off')}</button></div>`).join('')}</div>
    ${!src ? loading : src.kinds.map(kindCard).join('')}`);
}
function pageSystems() {
  platformEnsure('connectors', true); const M = platformState.mcp;
  return osShell('apps', 'Connected systems', head('Connected systems', 'Other systems your apps can act in, such as an ERP or a ticket desk. A tool that changes something waits for a go-ahead.', `<button class="btn" data-act="mcp-new">${icon('add')}Connect a system</button>`)
    + (!M ? loading : !M.length ? `<div class="empty">${icon('hub')}No system is connected yet. Connect one and its tools appear here and in VanikGPT.</div>` : M.map(m => `<div class="card" style="margin-bottom:16px"><div class="row"><span class="avatar sq">${icon('hub')}</span><div class="grow"><h3>${esc(m.name)}</h3><div class="mono">${esc(m.url)}${m.hasToken ? ' · token set' : ''}</div></div>${m.error ? chip('Not reachable', 'err') : chip(n(m.tools.length, 'tool'), 'ok')}<button class="btn ghost" data-act="mcp-refresh" data-id="${m.id}">Check</button><button class="icon-btn sm" data-act="mcp-del" data-id="${m.id}" data-tip="Remove" aria-label="Remove">${icon('link_off')}</button></div>${m.error ? `<div class="small" style="color:var(--vnk-err);margin-top:8px">${esc(m.error)}</div>` : ''}
      ${m.tools.map(t => `<div class="set-row"><div class="grow"><div class="lbl mono">${esc(t.name)}</div><div class="small muted">${esc(t.description)}</div></div><span class="small muted">Ask first ${info('On: a person must say go ahead before this tool runs. Keep it on for anything that changes data.')}</span><button class="switch ${t.ask ? 'on' : ''}" role="switch" aria-checked="${t.ask}" aria-label="Ask before running ${esc(t.name)}" data-act="mcp-ask" data-id="${m.id}" data-tool="${esc(t.name)}" data-on="${t.ask ? '' : '1'}"></button></div>`).join('')}</div>`).join('')));
}

// ================= People =================
acts['ppl-tab'] = el => { Q.ptab = el.dataset.v; rerender(); };
ins['ppl-q'] = el => { Q.pq = el.value; const box = $('#ppl-rows'); if (box) box.innerHTML = peopleRows(); };
acts['ppl-can'] = el => { const u = S.boot.users.find(x => x.id === el.dataset.id), a = Q.can, ok = acc => u.role !== 'user' || !acc || (!(acc.deny || []).includes(u.id) && (acc.mode === 'everyone' || (acc.users || []).includes(u.id) || (u.teams || []).some(t => (acc.teams || []).includes(t)))), s = suiteNeed(), B = S.boot;
  const apps = [...(B.app.status !== 'not_installed' && ok(B.app.config.access) ? ['VanikGPT'] : []), ...(s ? s.apps.filter(x => x.status !== 'not_installed' && ok(x.access)).map(x => x.name) : [])], cols = B.collections.filter(c => ok(c.access)).map(c => c.name), rest = (a || []).filter(x => x.kind !== 'collection' && ok(x.access));
  const list = (t, items) => `<div><div class="cap" style="margin-bottom:6px">${t}</div><div class="row wrap" style="gap:6px">${items.length ? items.map(i => `<span class="tag">${esc(i)}</span>`).join('') : '<span class="muted small">None</span>'}</div></div>`;
  modal({ title: 'What ' + u.name + ' can use', wide: true, cancel: 'Close', text: u.role === 'user' ? 'Worked out from their teams and from what is open to everyone. Change it on the Access tab.' : 'Owners and admins can use everything.', body: `<div class="stack" style="gap:16px">${list('Apps', apps)}${list('Collections', cols)}${list('Agents, plugins, systems and workflows', rest.map(x => x.name))}</div>` }); };
const peopleFilter = u => ({ all: true, active: u.status !== 'invited', invited: u.status === 'invited', admins: u.role !== 'user', directory: !!u.fromDirectory })[Q.ptab];
const peopleRows = () => { const B = S.boot, q = Q.pq.toLowerCase(), rows = B.users.filter(peopleFilter).filter(u => !q || (u.name + ' ' + u.email + ' ' + (u.teams || []).join(' ')).toLowerCase().includes(q));
  return rows.map(u => `<tr><td><div class="row"><span class="avatar">${esc(initials(u.name))}</span><div><b>${esc(u.name)}</b>${u.id === B.me.id ? ` <span class="faint small">you</span>` : ''}<div class="small muted">${esc(u.email)}</div></div></div></td>
    <td>${u.role === 'owner' ? ROLE.owner : `<select class="input" style="height:32px;width:130px" data-change="user-role" data-id="${u.id}" aria-label="Role of ${esc(u.name)}"><option value="admin" ${u.role === 'admin' ? 'selected' : ''}>Admin</option><option value="user" ${u.role === 'user' ? 'selected' : ''}>App user</option></select>`}</td>
    <td><div class="row wrap" style="gap:5px">${(u.teams || []).map(t => `<span class="tag">${esc(t)}</span>`).join('')}<button class="icon-btn sm" data-act="user-teams" data-id="${u.id}" data-tip="Edit teams" aria-label="Edit teams">${icon('edit')}</button></div></td>
    <td><button class="btn ghost" data-act="ppl-can" data-id="${u.id}">See</button></td>
    <td class="muted">${u.status === 'invited' ? chip('Invited', 'warn') : ago(u.lastActiveAt)}${u.fromDirectory ? `<div class="small faint">From the directory</div>` : ''}</td>
    <td class="act">${B.app.config.safety.adminChats ? `<button class="icon-btn sm tip-left" data-act="user-chats" data-id="${u.id}" data-tip="Open their chats (recorded)" aria-label="Open their chats">${icon('forum')}</button>` : ''}<button class="icon-btn sm tip-left" data-act="user-erase" data-id="${u.id}" data-tip="Erase their chats and files" aria-label="Erase data">${icon('cleaning_services')}</button>${u.role === 'owner' ? '' : `<button class="icon-btn sm" data-act="user-remove" data-id="${u.id}" data-tip="Remove" aria-label="Remove">${icon('person_remove')}</button>`}</td></tr>`).join('') || '<tr><td colspan="6" class="muted">Nobody matches.</td></tr>'; };
function pagePeople() {
  const B = S.boot, U = B.users, c = { all: U.length, active: U.filter(u => u.status !== 'invited').length, invited: U.filter(u => u.status === 'invited').length, admins: U.filter(u => u.role !== 'user').length, directory: U.filter(u => u.fromDirectory).length }; get('can', 'can', '/api/access'); suiteNeed();
  return osShell('people', 'People', `<div class="page-head"><div class="grow"><h1>People</h1><p class="sub">Who can sign in, what role they have and what they can use.</p></div><button class="btn lg" data-act="user-invite">${icon('person_add')}Invite someone</button></div>
    <div class="card"><div class="row wrap" style="gap:12px;margin-bottom:12px"><div class="seg">${[['all', 'All'], ['active', 'Active'], ['invited', 'Invited'], ['admins', 'Admins'], ['directory', 'From the directory']].map(t => `<button class="${Q.ptab === t[0] ? 'on' : ''}" data-act="ppl-tab" data-v="${t[0]}">${t[1]} <span class="mono">${c[t[0]]}</span></button>`).join('')}</div><input class="input grow" style="min-width:200px" placeholder="Search by name, email or team" value="${esc(Q.pq)}" data-on="ppl-q" aria-label="Search people"></div>
      <table class="list"><tr><th>Person</th><th>Role ${info('Owners and admins run the appliance. App users only use what they are given.')}</th><th>Teams ${info('Give a team an app or a collection in one go on the Access tab.')}</th><th>Can use</th><th>Last active</th><th></th></tr><tbody id="ppl-rows">${peopleRows()}</tbody></table></div>`);
}

// ================= Models: ask Vanik to train one =================
acts['train-send'] = async () => { try { await api('POST', '/api/plane/train', { goal: $('#tr-goal').value, data: $('#tr-data').value, size: $('#tr-size').value, base: $('#tr-base').value }); toast('Sent. Vanik will reply with a quote.'); reload('train'); } catch (e) { toast(e.message, 'err'); } };
function pageTrain() {
  const B = S.boot, past = get('train', 'train', '/api/plane/train');
  return osShell('train', 'Train', head('Train a model on your own data', 'Training is set up with the Vanik team and runs on this appliance. It starts with a request.')
    + `<div class="grid two" style="align-items:start"><div class="card stack" style="gap:14px"><label class="field"><span>What should the model do</span><textarea class="input" id="tr-goal" rows="3" placeholder="Answer supplier questions using our contracts and past tickets"></textarea></label>
        <div class="row" style="gap:12px"><label class="field grow"><span>Train it on</span><select class="input" id="tr-data">${['Documents', 'Support tickets', 'Code', 'Chat logs', 'Structured data', 'Not sure yet'].map(x => `<option>${x}</option>`).join('')}</select></label><label class="field grow"><span>How much</span><select class="input" id="tr-size">${['Under 10,000 documents', '10,000 to 100,000 documents', 'Over 100,000 documents'].map(x => `<option>${x}</option>`).join('')}</select></label></div>
        <label class="field"><span>Start from ${info('The open model to adapt. Leave it to Vanik if unsure.')}</span><select class="input" id="tr-base"><option value="">Let Vanik suggest one</option>${B.models.filter(m => m.kind === 'chat').map(m => `<option>${esc(m.id)}</option>`).join('')}</select></label>
        <div class="row"><span class="small muted grow">This sends a request to Vanik. Nothing is trained by pressing it.</span><button class="btn" data-act="train-send">Ask for a quote</button></div></div>
      <div class="stack" style="gap:16px"><div class="card"><div class="card-head"><h3>How it works</h3></div>${[['Your data stays here', 'Datasets, checkpoints and logs never leave the appliance.'], ['Start from an open model', 'It is adapted, not built from nothing.'], ['Test before you switch', 'The trained model is compared with its base on your own questions.'], ['Serve it like any other', 'An approved model appears on this page as a private model.']].map(x => `<div class="set-row"><div class="grow"><div class="lbl">${x[0]}</div><div class="small muted">${x[1]}</div></div></div>`).join('')}</div>
        <div class="card"><div class="card-head"><h3>Your requests</h3></div>${!past ? loading : past.length ? past.map(r => `<div class="set-row"><div class="grow"><div class="lbl" style="white-space:normal">${esc(r.goal)}</div><div class="small muted">${esc(r.data)} · ${esc(r.size)} · ${esc(r.by)} · ${ago(r.at)}</div></div>${chip(r.status, 'line', false)}</div>`).join('') : '<p class="muted">None yet.</p>'}</div></div></div>`);
}

// ================= API keys: a scope, a daily limit and an end date =================
acts['key-new'] = () => {
  const B = S.boot, serving = B.models.filter(m => m.status === 'serving');
  const m = modal({ title: 'Create an API key', wide: true, text: 'Name it for where it will be used. Give it only what that use needs.', body: `<div class="stack" style="gap:14px"><label class="field"><span>Name</span><input class="input" id="k-name" maxlength="40" placeholder="ERP bridge"></label>
    <div><div class="small" style="font-weight:600;margin-bottom:8px">Which models ${info('Leave all unpicked to allow every model, including ones served later.')}</div><div class="row wrap" style="gap:6px" id="k-models">${serving.map(x => `<button class="tag" data-v="${esc(x.id)}">${esc(x.id)}</button>`).join('') || '<span class="muted small">No model is serving.</span>'}</div></div>
    <div class="row" style="gap:12px"><label class="field grow"><span>Requests a day ${info('0 means no daily limit. Every key is also held to 60 requests a minute.')}</span><input class="input" type="number" min="0" id="k-limit" value="0"></label><label class="field grow"><span>Ends on ${info('Leave empty for a key that does not end.')}</span><input class="input" type="date" id="k-end"></label></div>
    <label class="field"><span>Can read documents ${info('Models only: chat and embeddings. With knowledge, the key can also fetch passages from the collections you pick.')}</span><select class="input" id="k-know"><option value="none">No. Models only</option><option value="all">Every collection</option>${B.collections.map(c => `<option value="${c.id}">Only ${esc(c.name)}</option>`).join('')}</select></label></div>`,
    actions: [{ label: 'Create key', run: async o => { const kv = $('#k-know', o).value, k = await api('POST', '/api/plane/keys', { name: $('#k-name', o).value, models: [...o.querySelectorAll('#k-models .on')].map(b => b.dataset.v), dailyLimit: +$('#k-limit', o).value, expiresOn: $('#k-end', o).value, knowledge: kv === 'none' || kv === 'all' ? kv : [kv] }); platformState.key = ''; await refresh(); setTimeout(() => modal({ title: 'Copy the key now', text: 'This is the only time it is shown. Vanik OS keeps a fingerprint, not the key.', cancel: 'Done', body: `<div class="row"><code class="mono grow" style="font-size:12.5px;color:var(--vnk-ink);overflow-wrap:anywhere">${esc(k.key)}</code>${copy(k.key)}</div>` }), 50); } }] });
  const box = $('#k-models', m.el); if (box) box.onclick = e => { const b = e.target.closest('button'); if (b) b.classList.toggle('on'); };
};

// ================= Notifications and Help =================
function pageNotifications() {
  const N = get('notes', 'notes', '/api/plane/notifications'); if (N && !Q.seenSent) { Q.seenSent = true; api('POST', '/api/plane/notifications/seen').catch(() => {}); }
  return osShell('home', 'Notifications', head('Notifications', 'What needs someone now, then what changed lately.')
    + (!N ? loading : `<div class="stack" style="max-width:820px;gap:16px"><div class="card"><div class="card-head"><h3>Needs someone now</h3><span class="mono">${N.now.length}</span></div>${N.now.length ? N.now.map(x => `<div class="set-row">${dot('warn')}<span class="grow">${esc(x.text)}</span><a class="btn ghost" href="${esc(x.href)}">${esc(x.action)}</a></div>`).join('') : '<p class="muted">Nothing.</p>'}</div>
      <div class="card"><div class="card-head"><h3>Changed lately</h3><a class="btn ghost right" href="#/os/activity/audit">Audit log</a></div>${N.recent.length ? N.recent.map(x => `<div class="set-row">${x.fresh ? dot('ok') : '<span class="hdot" style="visibility:hidden"></span>'}<span class="grow">${esc(x.text)}</span><span class="small faint">${ago(x.at)}</span></div>`).join('') : '<p class="muted">Nothing yet.</p>'}</div></div>`));
}
const HELP = [['Home', 'home', 'Whether everything is running, the one thing to do next, and how much it was used this week.'], ['Apps', 'apps', 'What is installed, what can be added, each app\'s setup and who can open it. Connected systems are the other systems apps can act in.'], ['Knowledge', 'library_books', 'The collections apps search, and the sources that fill them: uploads, a folder, Google Drive, SharePoint, Confluence.'], ['Models', 'memory', 'Which models are serving and what each is good for, models outside your network, API keys, a playground, and a request to train your own.'], ['People', 'group', 'Who can sign in, their role and teams, and what each person can use. Access is set per app, collection, agent and tool.'], ['Activity', 'insights', 'Who used what, who changed what, and an evidence pack for an auditor.'], ['Appliance', 'dns', 'The hardware: health, how to reach it, how full it is, updates, power, help from Vanik, and tools for support engineers.']];
function pageHelp() {
  const B = S.boot;
  return osShell('home', 'Help', head('Help', 'What each place in this console is for.')
    + `<div class="stack" style="max-width:820px;gap:16px"><div class="card">${HELP.map(h => `<div class="set-row"><span class="avatar sq">${icon(h[1])}</span><div class="grow"><div class="lbl">${h[0]}</div><div class="small muted" style="white-space:normal">${h[2]}</div></div></div>`).join('')}</div>
      <div class="card"><div class="card-head"><h3>Good to know</h3></div>${[['Search everything', 'Press Ctrl K to jump to a page, a collection or a chat.'], ['Nothing leaves by default', 'The evidence pack under Activity shows every way data could leave, read from the live settings.'], ['When something is stuck', 'Appliance, Support lets a Vanik engineer in for a set time. It ends by itself.'], ['The first admin', B.users.find(u => u.role === 'owner') ? esc(B.users.find(u => u.role === 'owner').name) + ' owns this tenant.' : 'No owner is set.']].map(x => `<div class="set-row"><div class="grow"><div class="lbl">${x[0]}</div><div class="small muted" style="white-space:normal">${x[1]}</div></div></div>`).join('')}</div></div>`);
}
acts.notif = () => go('#/os/notifications');

export function planeOsPage(parts) {
  if (!S.boot.admin) return undefined;
  const [p, a] = parts;
  if (p === 'home' || !p) return pageHome();
  if (p === 'devices' && !a) return pageAppliance();
  if (p === 'devices' && a === 'advanced') return pageAdvanced();
  if (p === 'settings') return pageUpdates();
  if (p === 'activity') return pageActivity(a);
  if (p === 'connectors') return a === 'systems' ? pageSystems() : pageSources();
  if (p === 'people') return pagePeople();
  if (p === 'train') return pageTrain();
  if (p === 'notifications') return pageNotifications();
  if (p === 'help') return pageHelp();
  return undefined;
}

// ================= a person's own home: my apps, my documents, my keys, help =================
const ME = [['', 'My apps', 'apps'], ['documents', 'My documents', 'library_books'], ['keys', 'My keys', 'key'], ['help', 'Help', 'help_outline']];
function meShell(active, content) {
  const B = S.boot;
  return `<div class="shell"><aside class="console-nav"><a class="brand" href="#/me">${LOGO}<span class="vk-brand"><small>Vanik Edge</small><b>My apps</b></span></a>
    ${ME.map(m => `<a class="nav-item ${active === m[0] ? 'is-active' : ''}" href="#/me${m[0] ? '/' + m[0] : ''}">${icon(m[2])}<span>${m[1]}</span></a>`).join('')}
    ${B.admin ? `<span class="nav-group-label">Admin</span><a class="nav-item" href="#/os/home">${icon('dns')}<span>Vanik OS console</span></a>` : ''}</aside>
    <div class="main"><header class="topbar">${navToggle()}<span class="crumb">${esc(B.tenant.name)} / <b>${ME.find(m => m[0] === active)[1]}</b></span><span class="right"></span>${themeButton()}${userButton()}</header><div class="scroll" id="scroll"><div class="page">${content}</div></div></div></div>`;
}
acts['me-upload'] = async el => { const files = await pickFiles(true); if (!files.length) return; await uploadFiles(`/api/collections/${el.dataset.id}/documents`, files); reload('me'); await refresh(); };
ins['me-q'] = el => { Q.mq = el.value; };
acts['me-search'] = async () => { const q = ($('#me-q') || {}).value || ''; if (q.trim().length < 3) return toast('Type a few words to search for.', 'err'); Q.mq = q; Q.mhits = await api('POST', '/api/search', { q }); rerender(); };
export function mePage(parts) {
  const B = S.boot, [p] = parts, M = get('me', 'me', '/api/me/home'), h = new Date().getHours();
  if (p === 'keys') { const k = apiPage(true); return meShell('keys', head('My keys', 'Your own keys for calling the models on this appliance from your tools.', k.allowed ? `<button class="btn" data-act="my-key-new">${icon('add')}New key</button>` : '') + `<div style="max-width:760px">${k.body}</div>`); }
  if (p === 'help') return meShell('help', head('Help', 'Who to ask, and what you can do here.') + (!M ? loading : `<div class="stack" style="max-width:760px;gap:16px"><div class="card"><div class="card-head"><h3>Who to ask</h3></div>${M.admins.map(a => `<div class="set-row"><span class="avatar">${esc(initials(a.name))}</span><div class="grow"><div class="lbl">${esc(a.name)}</div><div class="small muted">${esc(a.email)}</div></div></div>`).join('')}<p class="small faint" style="margin-top:10px">They can give you an app or a collection, and add you to a team.</p></div>
    <div class="card">${[['My apps', 'Every app you have been given. Open one to use it.'], ['My documents', 'Collections you can search. Where you are allowed, you can add files.'], ['My keys', M.keysAllowed ? 'Your own keys for calling the models from your tools.' : 'Your admin has not turned on personal keys.'], ['Where your data is', 'Everything stays on ' + esc(M.appliance.name) + ', inside your company.']].map(x => `<div class="set-row"><div class="grow"><div class="lbl">${x[0]}</div><div class="small muted" style="white-space:normal">${x[1]}</div></div></div>`).join('')}</div></div>`));
  if (p === 'documents') return meShell('documents', head('My documents', 'Collections you can search. Ask about them in VanikGPT, or look something up here.')
    + (!M ? loading : `<div class="card" style="margin-bottom:16px"><div class="row"><input class="input grow" id="me-q" placeholder="Look something up, for example travel claim" value="${esc(Q.mq || '')}" data-on="me-q" aria-label="Search your documents"><button class="btn" data-act="me-search">Search</button></div>
        ${Q.mhits ? (Q.mhits.length ? Q.mhits.map(x => `<div class="set-row" style="align-items:flex-start"><div class="grow"><div class="lbl">${esc(x.docName)}${x.page ? ' · page ' + x.page : ''}</div><div class="small muted" style="white-space:normal">${esc(x.text.slice(0, 260))}${x.text.length > 260 ? '…' : ''}</div></div></div>`).join('') : '<p class="muted" style="margin-top:12px">Nothing matches.</p>') : ''}</div>
      ${M.collections.length ? `<div class="card">${M.collections.map(c => `<div class="set-row"><span class="avatar sq">${icon('library_books')}</span><div class="grow"><div class="lbl">${esc(c.name)}</div><div class="small muted">${esc(c.description || '')}${c.description ? ' · ' : ''}${n(c.documents, 'document')}</div></div>${c.canAdd ? `<button class="btn ghost" data-act="me-upload" data-id="${c.id}">${icon('upload_file')}Add files</button>` : `<span class="small faint">Read only</span>`}</div>`).join('')}</div>` : `<div class="empty">${icon('library_books')}No collection has been shared with you yet. Ask an admin (see Help).</div>`}`));
  return meShell('', head(`${h < 12 ? 'Good morning' : h < 17 ? 'Good afternoon' : 'Good evening'}, ${esc(B.me.name.split(' ')[0])}`, !M ? '' : M.appliance.online ? (M.tasks ? `${n(M.tasks, 'task')} waiting for you.` : 'Pick an app to start.') : 'The appliance is offline, so apps cannot be opened right now.', M && M.tasks && B.canUseGpt ? `<a class="btn ghost" href="#/gpt/tasks">Open tasks</a>` : '')
    + (!M ? loading : M.apps.length ? `<div class="grid">${M.apps.map(a => `<a class="card app-card" href="${a.href}" style="text-decoration:none;color:inherit"><div class="row"><span class="app-ico">${icon(a.icon)}</span></div><h3>${esc(a.name)}</h3><p class="muted small">${esc(a.what)}</p><div class="foot"><span class="grow"></span><span class="btn">Open</span></div></a>`).join('')}</div>` : `<div class="empty">${icon('apps')}You have not been given an app yet. Ask an admin (see Help).</div>`));
}
