// The four apps that could be read on the testing appliance, screen for screen: Vanik Scout, Vanik MeasureBook, Vanik mBot, and
// Vanik Echo as its catalogue entry describes it. Tabs, controls and words follow ../apps/*.md. Server side: real.js.
import { S, $, esc, icon, info, chip, go, ago, api, rerender, acts, ins, toast, modal, confirmBox, menu, downloadText } from './core.js';
import { appShell, get, put, P, readFiles } from './suite.js';

const loading = '<p class="muted">Loading…</p>';
const menuD = (el, items) => menu(el, items.filter(i => i && !i.disabled));
const pickAny = (multiple, accept) => new Promise(ok => { const i = document.createElement('input'); i.type = 'file'; i.multiple = multiple; i.accept = accept; i.onchange = () => ok([...i.files]); i.click(); });
const tabs = (base, list, on) => `<nav class="tabs">${list.map(t => `<a class="${t[0] === on ? 'on' : ''}" href="${base}${t[0] ? '/' + t[0] : ''}">${t[1]}</a>`).join('')}</nav>`;
const sw = (on, act, label, extra = '') => `<button class="switch ${on ? 'on' : ''}" role="switch" aria-checked="${!!on}" aria-label="${esc(label)}" data-act="${act}" ${extra}></button>`;
const day = iso => new Date(iso).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
const size = n => n > 1e6 ? (n / 1e6).toFixed(1) + ' MB' : Math.max(1, Math.round(n / 1000)) + ' KB';
const fresh = (...slots) => slots.forEach(s => { P[s + 'Key'] = ''; });
const on = h => location.hash === h || location.hash.startsWith(h + '/');
document.addEventListener('keydown', e => { if (e.key !== 'Enter' || e.shiftKey || !e.target.dataset || !e.target.dataset.enter) return; e.preventDefault(); const f = acts[e.target.dataset.enter]; if (f) f(e.target, e); });

// =====================================================================================================================
// Vanik Scout
// =====================================================================================================================
const SC = { q: '', res: null, busy: false, strict: false, allV: false, col: '', F: {}, sel: '', cand: null, why: 'summary', picks: [], page: 1, role: 'all', showRej: true, scope: 'mine', upCol: '' };
const SOON = { collections: ['Collections', 'Job postings you upload résumés into and scope search to'], index: ['Index admin', 'Create, inspect and edit the résumé index'], admin: ['Admin', 'Approve access requests and manage the live model endpoints'] };
async function scRun(mode, extra) {
  SC.busy = true; rerender();
  const base = { collectionId: SC.col, strict: SC.strict, allVersions: SC.allV, filters: SC.F, page: SC.page };
  try {
    SC.res = mode === 'q' ? await api('POST', '/api/scout/search', { ...base, q: SC.q }) : mode === 'refine' ? await api('POST', '/api/scout/refine', { ...base, parsed: SC.res.parsed, text: extra }) : await api('POST', '/api/scout/search/parsed', { ...base, parsed: SC.res.parsed });
    if (!SC.res.hits.some(h => h.id === SC.sel)) { SC.sel = ''; SC.cand = null; }
  } catch (e) { toast(e.message, 'err'); }
  SC.busy = false; rerender();
}
ins['sc-q'] = el => { SC.q = el.value; };
ins['sc-col'] = el => { SC.col = el.value; if (SC.res) { SC.page = 1; scRun(SC.res.browse ? 'q' : 'p'); } };
acts['sc-find'] = () => { SC.q = ($('#sc-q') || { value: SC.q }).value; SC.F = {}; SC.page = 1; SC.picks = []; scRun('q'); };
acts['sc-refine'] = () => { const el = $('#sc-refine'), t = el ? el.value.trim() : ''; if (!t) return; SC.page = 1; scRun('refine', t); };
acts['sc-strict'] = () => { SC.strict = !SC.strict; SC.page = 1; scRun('p'); };
acts['sc-allv'] = () => { SC.allV = !SC.allV; SC.page = 1; scRun('p'); };
acts['sc-page'] = el => { SC.page = +el.dataset.v; scRun('p'); };
acts['sc-facet'] = el => { const k = el.dataset.k, v = el.dataset.v, L = SC.F[k] = SC.F[k] || []; SC.F[k] = L.includes(v) ? L.filter(x => x !== v) : [...L, v]; SC.page = 1; scRun('p'); };
acts['sc-chip'] = el => { const p = SC.res.parsed, s = el.dataset.v, k = el.dataset.k; menu(el, [k === 'must' ? { label: 'Make this a nice-to-have', icon: 'south', run: () => { p.must = p.must.filter(x => x !== s); p.nice.push(s); scRun('p'); } } : { label: 'Make this a must-have', icon: 'north', run: () => { p.nice = p.nice.filter(x => x !== s); p.must.push(s); scRun('p'); } }, { label: 'Remove', icon: 'close', run: () => { p[k] = p[k].filter(x => x !== s); scRun('p'); } }]); };
acts['sc-pref'] = el => { const p = SC.res.parsed, k = el.dataset.k; if (k === 'minYears') p.minYears = 0; else if (k === 'also') p.also = p.also.filter(x => x !== el.dataset.v); else p[k] = k === 'location' ? (p.also.shift() || '') : ''; scRun('p'); };
ins['sc-add'] = el => { if (!el.value) return; const p = SC.res.parsed; if (!p.must.includes(el.value) && !p.nice.includes(el.value)) p.must.push(el.value); scRun('p'); };
acts['sc-drop'] = el => { const p = SC.res.parsed; p.must = p.must.filter(x => x !== el.dataset.v); scRun('p'); };
acts['sc-open'] = async el => { SC.sel = el.dataset.id; SC.cand = null; SC.why = 'summary'; rerender(); try { SC.cand = await api('GET', '/api/scout/candidate/' + SC.sel); rerender(); } catch (e) { toast(e.message, 'err'); } };
acts['sc-why'] = el => { SC.why = el.dataset.v; rerender(); };
acts['sc-full'] = () => modal({ title: SC.cand.profile.name, wide: true, body: `<pre class="code" style="white-space:pre-wrap;max-height:60vh;overflow:auto">${esc(SC.cand.text)}</pre>`, cancel: 'Close' });
const scMark = async (key, status, reason) => { try { await api('POST', '/api/scout/shortlist', { key, status, reason, role: SC.col }); fresh('scList'); await scRun(SC.res && !SC.res.browse ? 'p' : 'q'); } catch (e) { toast(e.message, 'err'); } };
acts['sc-star'] = el => el.dataset.on ? api('DELETE', '/api/scout/shortlist/' + encodeURIComponent(el.dataset.key)).then(() => { fresh('scList'); scRun(SC.res && !SC.res.browse ? 'p' : 'q'); }) : scMark(el.dataset.key, 'shortlisted');
acts['sc-reject'] = el => { const h = P.scHealth; if (el.dataset.on) return acts['sc-star']({ dataset: { on: '1', key: el.dataset.key } }); menu(el, [{ heading: 'Why not?' }, ...((h && h.reasons) || ['Other']).map(r => ({ label: r, run: () => scMark(el.dataset.key, 'rejected', r) }))]); };
acts['sc-pick'] = el => { const k = el.dataset.key; SC.picks = SC.picks.includes(k) ? SC.picks.filter(x => x !== k) : [...SC.picks, k]; rerender(); };
acts['sc-pick-page'] = () => { const ks = SC.res.hits.map(h => h.key); SC.picks = ks.every(k => SC.picks.includes(k)) ? [] : ks; rerender(); };
acts['sc-bulk'] = async el => { const all = el.dataset.v === 'all', n = all ? SC.res.total : SC.picks.length; if (!n) return toast('Select a candidate first.', 'err'); confirmBox(`Shortlist ${all ? 'all ' + n + ' matching' : n} candidate${n === 1 ? '' : 's'}?`, all ? 'Every ranked match for this search.' : 'The ones you ticked on this page.', 'Shortlist', async () => { const r = await api('POST', '/api/scout/shortlist/bulk', { parsed: SC.res.parsed, collectionId: SC.col, strict: SC.strict, allVersions: SC.allV, filters: SC.F, scope: all ? 'all' : 'keys', keys: SC.picks }); toast(r.capped ? `Shortlisted the first ${r.added} (capped at ${r.cap}).` : `Shortlisted ${r.added}.`); SC.picks = []; fresh('scList'); scRun('p'); }); };
ins['sc-role'] = el => { SC.role = el.value; fresh('scList'); rerender(); };
acts['sc-rej-toggle'] = () => { SC.showRej = !SC.showRej; rerender(); };
acts['sc-unlist'] = async el => { await api('DELETE', '/api/scout/shortlist/' + encodeURIComponent(el.dataset.key)); fresh('scList'); rerender(); };
acts['sc-export'] = async el => { const r = await api('GET', '/api/scout/shortlist/export' + (el.dataset.v === 'zip' ? '?kind=zip' : '')); downloadText(r.name, r.text); };
acts['sc-clear'] = () => confirmBox('Clear this list?', 'Rejections are kept.', 'Clear this list', async () => { const r = await api('POST', '/api/scout/shortlist/bulk-remove', { all: true, ...(SC.role === 'all' ? {} : { role: SC.role }) }); toast(`Removed ${r.removed} from the shortlist.`); fresh('scList'); rerender(); }, true);
ins['sc-upcol'] = el => { SC.upCol = el.value; };
acts['sc-newcol'] = () => modal({ title: 'New collection', text: 'The job posting these résumés belong to', body: `<input class="input" id="sc-colname" placeholder="New collection name">`, actions: [{ label: 'Create', run: async o => { const c = await api('POST', '/api/scout/collections', { name: $('#sc-colname', o).value }); SC.upCol = c.id; fresh('scCols'); rerender(); } }] });
acts['sc-upload'] = async () => { if (!SC.upCol) return toast('Pick a collection first. Every résumé is filed under one.', 'err'); const files = await readFiles(); if (!files.length) return; try { const r = await api('POST', '/api/scout/uploads', { collectionId: SC.upCol, files: files.map(f => ({ name: f.name, text: f.text, size: f.text.length })) }); r.rejected.forEach(x => toast(`${x.file}: ${x.rejected}`, 'err')); if (r.accepted.length) toast(`${r.accepted.length} uploaded.`); fresh('scUps', 'scHealth'); rerender(); } catch (e) { toast(e.message, 'err'); } };
acts['sc-bulk-up'] = async el => { try { await api('POST', '/api/scout/uploads/bulk', { kind: el.dataset.v, collectionId: SC.upCol }); } catch (e) { toast(e.message, 'err'); } };
acts['sc-scope'] = el => { SC.scope = el.dataset.v; fresh('scUps'); rerender(); };
acts['sc-retry'] = async el => { await api('POST', `/api/scout/uploads/${el.dataset.id}/retry`); fresh('scUps'); rerender(); };
acts['sc-del'] = el => confirmBox('Delete?', 'Delete this upload and its file.', 'Yes, delete it', async () => { await api('DELETE', '/api/scout/uploads/' + el.dataset.id); fresh('scUps', 'scHealth'); rerender(); }, true);
acts['sc-insearch'] = el => { SC.q = el.dataset.name; SC.F = {}; SC.page = 1; go('#/app/scout'); scRun('q'); };
const foundLine = (h, long) => !h.found ? '' : h.found.kind === 'both' ? (long ? `Found by both keyword (#${h.found.kw}) and semantic (#${h.found.sem}) search. The résumé uses your terms and describes the same work.` : 'Found by keyword + semantic search.') : h.found.kind === 'semantic' ? (long ? `Found by semantic similarity (#${h.found.sem}). The résumé describes this kind of work even without your exact keywords.` : 'Found by semantic similarity.') : (long ? `Found by keyword match (#${h.found.kw}). The résumé literally mentions your search terms.` : 'Found by keyword match.');
function scSearch(cols, h) {
  const r = SC.res, p = r && r.parsed, sel = r && r.hits.find(x => x.id === SC.sel), c = SC.cand;
  const chips = (k, list) => list.map(s => `<button class="tag ${k === 'must' ? 'on' : ''}" data-act="sc-chip" data-k="${k}" data-v="${esc(s)}">${esc(s)}</button>`).join('');
  const pref = (k, label, v = '') => `<button class="tag" data-act="sc-pref" data-k="${k}" data-v="${esc(v)}" data-tip="Remove">${esc(label)} ${icon('close')}</button>`;
  const read = !r || r.browse ? '' : `<div class="card" style="margin-bottom:16px"><div class="card-head"><h3>How this was read</h3>${info('Click a chip to change it. The search re-runs on your edit. The model does not get a second opinion.')}</div>
    <div class="row wrap" style="gap:6px"><span class="cap">Must have</span>${chips('must', p.must) || '<span class="small muted">none: all candidates considered</span>'}<select class="input" style="width:auto;padding:2px 8px" data-change="sc-add" aria-label="Add a skill"><option value="">+ skill</option>${((h && h.skills) || []).filter(s => !p.must.includes(s) && !p.nice.includes(s)).map(s => `<option>${esc(s)}</option>`).join('')}</select></div>
    ${p.nice.length ? `<div class="row wrap" style="gap:6px;margin-top:8px"><span class="cap">Nice to have</span>${chips('nice', p.nice)}</div>` : ''}
    ${p.minYears || p.location || p.seniority || p.also.length ? `<div class="row wrap" style="gap:6px;margin-top:8px"><span class="cap">Preferences</span>${p.minYears ? pref('minYears', p.minYears + '+ years') : ''}${p.location ? pref('location', p.location) : ''}${p.also.map(a => pref('also', 'also ' + a, a)).join('')}${p.seniority ? pref('seniority', p.seniority) : ''}</div>` : ''}
    <div class="row" style="gap:8px;margin-top:14px"><input class="input grow" id="sc-refine" data-enter="sc-refine" placeholder="Refine in plain English: also Pune · drop AutoCAD · more senior…"><button class="btn ghost" data-act="sc-refine">Refine</button></div>
    <div class="set-row" style="margin-top:10px"><div class="grow"><div class="lbl">Strict requirements ${info('Off by default. A location the résumé never stated, or a skill the extractor missed, would otherwise delete an ideal candidate with nothing on screen telling you it happened.')}</div><div class="small muted">Exclude anyone missing a must-have, the location, or the years${r.hidden ? ` · ${r.hidden} hidden now` : ''}</div></div>${sw(SC.strict, 'sc-strict', 'Strict requirements')}</div>
    <div class="set-row"><div class="grow"><div class="lbl">Every version, not just the latest résumé ${info('By default each person is ranked on their newest résumé only.')}</div></div>${sw(SC.allV, 'sc-allv', 'Every version')}</div></div>`;
  const facet = (k, label) => { const L = r.facets[k] || []; return !L.length ? '' : `<div style="margin-bottom:14px"><div class="cap" style="margin-bottom:6px">${label}</div>${L.map(f => `<button class="check ${(SC.F[k] || []).includes(f.value) ? 'on' : ''}" style="display:flex;width:100%;gap:6px;padding:3px 6px;border-radius:6px;font-size:12.5px;text-align:left" data-act="sc-facet" data-k="${k}" data-v="${esc(f.value)}">${icon((SC.F[k] || []).includes(f.value) ? 'check_box' : 'check_box_outline_blank')}<span class="grow">${esc(f.value)}</span><span class="faint">${f.n}</span></button>`).join('')}</div>`; };
  const row = x => `<div class="set-row hit ${x.id === SC.sel ? 'sel' : ''}" style="align-items:flex-start;gap:10px"><button class="icon-btn sm" data-act="sc-pick" data-key="${esc(x.key)}" aria-label="Select">${icon(SC.picks.includes(x.key) ? 'check_box' : 'check_box_outline_blank')}</button>
    <button class="grow" style="text-align:left;min-width:0" data-act="sc-open" data-id="${x.id}"><div class="row" style="gap:8px"><b>${esc(x.name)}</b>${x.mark === 'shortlisted' ? chip('Shortlisted', 'ok', false) : x.mark === 'rejected' ? chip('Rejected', 'err', false) : ''}${x.fit != null ? `<span class="mono" style="margin-left:auto" data-tip="Rank within your results (top ≈ 100%), weighted by requirement coverage. Not an absolute score.">${x.fit}%</span>` : ''}</div>
      <div class="small muted">${esc(x.title)}${x.years ? ` · ${x.years} yrs` : ''}${x.location ? ' · ' + esc(x.location) : ''}</div>
      ${x.has.length || x.missing.length ? `<div class="row wrap" style="gap:4px;margin-top:6px">${x.has.map(s => `<span class="tag on">${esc(s)}</span>`).join('')}${x.missing.map(s => `<span class="tag" style="text-decoration:line-through">${esc(s)}</span>`).join('')}</div>` : ''}${x.found ? `<div class="small faint" style="margin-top:4px">${foundLine(x)}</div>` : ''}</button>
    <button class="icon-btn sm" data-act="sc-star" data-key="${esc(x.key)}" ${x.mark === 'shortlisted' ? 'data-on="1"' : ''} data-tip="${x.mark === 'shortlisted' ? 'Remove from shortlist' : 'Add to shortlist'}" aria-label="Shortlist">${icon(x.mark === 'shortlisted' ? 'star' : 'star_border')}</button><button class="icon-btn sm" data-act="sc-reject" data-key="${esc(x.key)}" ${x.mark === 'rejected' ? 'data-on="1"' : ''} data-tip="${x.mark === 'rejected' ? 'Undo rejection' : 'Not a fit'}" aria-label="Not a fit">${icon(x.mark === 'rejected' ? 'undo' : 'thumb_down_off_alt')}</button></div>`;
  let pane = `<div class="empty">${icon('person')}Select a candidate to see their profile.</div>`;
  if (sel) {
    const need = p.must.length, met = sel.has.length, ev = c ? c.text.split('\n').filter(l => [...sel.has, ...sel.nice].some(s => l.toLowerCase().includes(s))).slice(0, 6) : [];
    const why = sel.found ? `<div class="card-head" style="margin-top:14px"><h3>Why this match</h3></div><div class="seg" style="margin-bottom:10px">${['summary', 'requirements', 'evidence'].map(t => `<button class="${SC.why === t ? 'on' : ''}" data-act="sc-why" data-v="${t}">${t[0].toUpperCase() + t.slice(1)}</button>`).join('')}</div>
      ${SC.why === 'summary' ? `<p><b>${!need ? 'Ranked by overall similarity' : met === need ? `Meets every requirement (${need})` : `Meets ${met} of ${need} requirements`}</b></p><p class="small muted" style="margin-top:6px">${foundLine(sel, true)}</p><p class="small faint" style="margin-top:6px">The ${sel.fit}% is this candidate's rank within your results (the top match ≈ 100%), weighted by requirement coverage. Not an absolute score.</p>`
      : SC.why === 'requirements' ? `<div class="stack" style="gap:6px">${!need ? '<p class="small muted">No must-haves in this profile, so nothing to check against.</p>' : ''}${p.must.map(s => `<div class="row small">${icon(sel.has.includes(s) ? 'check' : 'close')}<span>${esc(s)}</span></div>`).join('')}${need && met === need ? '<p class="small muted">Nothing missing from your requirements.</p>' : ''}${sel.nice.length ? `<p class="small muted">Also brings nice-to-have: ${esc(sel.nice.join(', '))}.</p>` : ''}${p.minYears ? `<div class="row small">${icon(sel.yearsOk ? 'check' : 'close')}<span>${sel.years} years stated, ${p.minYears} asked</span></div>` : ''}${p.location ? `<div class="row small">${icon(sel.locOk ? 'check' : 'close')}<span>${esc(sel.location || 'Location not stated')}, ${esc([p.location, ...p.also].join(' or '))} asked</span></div>` : ''}</div>`
      : ev.length ? ev.map(l => `<p class="small" style="margin-bottom:6px">${esc(l)}</p>`).join('') : '<p class="small muted">No line in the résumé names these skills directly.</p>'}` : '';
    pane = `<div class="card"><div class="row"><div class="grow"><h3>${esc(sel.name)}</h3><div class="small muted">${esc(sel.title)}${sel.years ? ` · ${sel.years} yrs` : ''}${sel.location ? ' · ' + esc(sel.location) : ''}</div></div></div>${why}
      ${!c ? loading : `<div class="cap" style="margin:16px 0 4px">Summary</div><p class="small">${esc(c.profile.summary)}</p><div class="cap" style="margin:14px 0 6px">Skills</div><div class="row wrap" style="gap:4px">${c.profile.skills.map(s => `<span class="tag">${esc(s)}</span>`).join('')}</div>
        <div class="cap" style="margin:14px 0 4px">Experience</div>${c.profile.experience.map(e => `<p class="small">${esc(e)}</p>`).join('')}<div class="cap" style="margin:14px 0 4px">Education</div>${c.profile.education.map(e => `<p class="small">${esc(e)}</p>`).join('')}
        <p class="small faint" style="margin-top:12px">${esc(c.collection)}${c.versions > 1 ? ` · ${c.versions} versions on file` : ''}</p><button class="btn ghost" style="margin-top:10px" data-act="sc-full">${icon('description')}Open full résumé</button>`}</div>`;
  }
  return `<div class="card" style="margin-bottom:16px"><div class="row wrap" style="gap:8px;margin-bottom:8px"><select class="input" style="width:auto" data-change="sc-col" aria-label="Search within a collection, or all résumés"><option value="">All résumés</option>${(cols || []).map(x => `<option value="${x.id}" ${SC.col === x.id ? 'selected' : ''}>${esc(x.name)}</option>`).join('')}</select></div>
      <textarea class="input" id="sc-q" rows="2" data-on="sc-q" data-enter="sc-find" placeholder="solar project manager, Bangalore, 6+ years…">${esc(SC.q)}</textarea>
      <div class="row" style="margin-top:8px"><span class="small faint grow">A few words (solar PM pune 8 years) or a whole job description. Leave empty to browse everyone. Shift + Enter for a new line</span><button class="btn" data-act="sc-find" ${SC.busy ? 'disabled' : ''}>${SC.busy ? 'Searching…' : r ? 'Search again' : 'Find candidates'}</button></div></div>
    ${read}${!r ? '' : `<div class="sc-grid"><div>${r.total ? `<div class="cap" style="margin-bottom:10px">Filters ${info('Ticking two skills finds people who have both.')}</div>${facet('skills', 'Skills')}${facet('seniority', 'Seniority')}${facet('location', 'Location')}${facet('domain', 'Domain')}${facet('employer', 'Employer')}` : ''}</div>
      <div><div class="row" style="margin-bottom:8px"><b>${r.total}</b><span class="muted small">&nbsp;candidates · ${r.browse ? 'newest first' : 'ranked by fit'}</span><span class="grow"></span>${r.total ? `<button class="btn ghost" data-act="sc-pick-page">This page</button><button class="btn ghost" data-act="sc-bulk" data-v="keys">Shortlist selected${SC.picks.length ? ' (' + SC.picks.length + ')' : ''}</button><button class="btn ghost" data-act="sc-bulk" data-v="all" data-tip="${r.browse ? 'Every candidate matching these filters' : 'Every ranked match for this search'}">All matches</button>` : ''}</div>
        ${r.mode === 'keyword' ? `<div class="banner" style="margin-bottom:10px">${icon('warning')}Keyword-only results. The embedding service is unavailable, so this search ran without semantic matching.</div>` : ''}
        ${!r.total ? `<div class="empty">${icon('search_off')}<b>${r.browse ? 'No résumés match these filters' : 'No candidates matched'}</b><br>${r.blocker && !r.blocker.count ? `No candidate has "${esc(r.blocker.skill)}". This is what's shrinking your results. Drop it to widen them.<br><button class="btn" style="margin-top:10px" data-act="sc-drop" data-v="${esc(r.blocker.skill)}">Drop '${esc(r.blocker.skill)}' and search again</button>` : r.browse ? 'Try clearing a filter.' : 'Drop a must-have, loosen a filter, or turn off strict requirements.'}</div>` : `<div class="card" style="padding:4px 14px">${r.hits.map(row).join('')}</div>
        ${r.pages > 1 ? `<div class="row" style="margin-top:10px;gap:8px;justify-content:center"><button class="btn ghost" data-act="sc-page" data-v="${r.page - 1}" ${r.page < 2 ? 'disabled' : ''}>Prev</button><span class="small muted">Page ${r.page} of ${r.pages}</span><button class="btn ghost" data-act="sc-page" data-v="${r.page + 1}" ${r.page >= r.pages ? 'disabled' : ''}>Next</button></div>` : ''}`}</div>
      <div>${pane}</div></div>`}`;
}
function scShortlist(cols) {
  const L = get('scList', SC.role, '/api/scout/shortlist?role=' + encodeURIComponent(SC.role)); if (!L) return loading;
  const tr = (x, rej) => `<tr><td><b>${esc(x.name)}</b><div class="small muted">${esc(x.title)}</div></td><td>${x.years ? x.years + ' yrs' : ''}${x.location ? ' · ' + esc(x.location) : ''}</td><td class="small">${esc(x.email)}<br>${esc(x.phone)}</td><td>${esc(x.role)}${x.verdict ? ' ' + chip(x.verdict === 'interview' ? 'Interview' : 'Pass', x.verdict === 'interview' ? 'ok' : 'err', false) : ''}${rej ? `<div class="small muted">${esc(x.reason)}</div>` : ''}</td><td class="act"><button class="icon-btn sm" data-act="sc-unlist" data-key="${esc(x.key)}" data-tip="${rej ? 'Undo rejection' : 'Remove from the shortlist'}" aria-label="Remove">${icon(rej ? 'undo' : 'close')}</button></td></tr>`;
  return `<div class="row wrap" style="gap:8px;margin-bottom:14px"><select class="input" style="width:auto" data-change="sc-role" aria-label="Role"><option value="all">All roles</option><option value="" ${SC.role === '' ? 'selected' : ''}>General</option>${(cols || []).map(c => `<option value="${c.id}" ${SC.role === c.id ? 'selected' : ''}>${esc(c.name)}</option>`).join('')}</select><span class="grow"></span>${SC.role && SC.role !== 'all' ? `<button class="btn" data-act="sc-share">${icon('share')}Share with the hiring manager</button>` : ''}<button class="btn ghost" data-act="sc-export" data-v="csv">${icon('download')}Export CSV</button><button class="btn ghost" data-act="sc-export" data-v="zip">${icon('folder_zip')}Export résumés (ZIP)</button><button class="btn ghost" data-act="sc-clear">Clear this list</button></div>
    ${!L.shortlisted.length ? `<div class="empty">${icon('star_border')}<b>Nothing shortlisted yet</b><br>Star a candidate from the Search tab and they'll collect here.</div>` : `<div class="card"><table class="list"><tr><th>Candidate</th><th>Experience</th><th>Contact</th><th>Role</th><th></th></tr>${L.shortlisted.map(x => tr(x)).join('')}</table></div>`}
    ${L.rejected.length ? `<div class="card" style="margin-top:16px"><div class="card-head"><h3>Rejected <span class="mono">${L.rejected.length}</span></h3>${info('Rejection reasons are kept deliberately: they are the only labelled data this system gets for free, and every future ranking improvement needs them.')}<span class="grow"></span><button class="btn ghost" data-act="sc-rej-toggle">${SC.showRej ? 'Hide' : 'Show'}</button></div>${SC.showRej ? `<table class="list"><tr><th>Candidate</th><th>Experience</th><th>Contact</th><th>Role and reason</th><th></th></tr>${L.rejected.map(x => tr(x, true)).join('')}</table>` : ''}</div>` : ''}`;
}
function scUploads(cols) {
  const U = get('scUps', SC.scope, '/api/scout/uploads?scope=' + SC.scope);
  if (U && U.some(x => !['Searchable', 'Failed'].includes(x.stage))) setTimeout(() => { if (on('#/app/scout/uploads')) { fresh('scUps', 'scHealth'); rerender(); } }, 1300);
  const st = { Searchable: 'ok', Failed: 'err' };
  return `<div class="card" style="margin-bottom:16px"><div class="row wrap" style="gap:8px"><select class="input" style="width:auto" data-change="sc-upcol" aria-label="Collection"><option value="">Choose a collection…</option>${(cols || []).map(c => `<option value="${c.id}" ${SC.upCol === c.id ? 'selected' : ''}>${esc(c.name)}</option>`).join('')}</select><button class="btn ghost" data-act="sc-newcol">${icon('add')}New collection</button><span class="grow"></span><span class="small muted">Bulk:</span><button class="btn ghost" data-act="sc-bulk-up" data-v="zip">Upload a .zip</button><button class="btn ghost" data-act="sc-bulk-up" data-v="sheet" data-tip="An .xlsx or .csv of Google Drive links. The server fetches each file">Upload a link sheet</button></div>
      <button class="empty" style="width:100%;margin-top:12px" data-act="sc-upload">${icon('upload_file')}Drop résumés here, or browse<br><span class="small faint">25 MB each · PDF, Word or text</span></button></div>
    <div class="row" style="margin-bottom:10px"><div class="seg"><button class="${SC.scope === 'mine' ? 'on' : ''}" data-act="sc-scope" data-v="mine">Mine</button><button class="${SC.scope === 'all' ? 'on' : ''}" data-act="sc-scope" data-v="all">Everyone</button></div></div>
    ${!U ? loading : !U.length ? `<div class="empty">${icon('inbox')}Nothing uploaded yet.</div>` : `<div class="card"><table class="list"><tr><th>File</th><th>Stage</th><th>Size</th><th>Uploaded</th><th>Actions</th></tr>${U.map(x => `<tr><td><b>${esc(x.file)}</b><div class="small muted">${esc(x.collection)}${SC.scope === 'all' ? ' · ' + esc(x.by) : ''}</div></td><td>${chip(x.stage, st[x.stage] || 'warn')}${x.attempts > 1 ? `<div class="small faint">Processing attempts so far: ${x.attempts}</div>` : ''}</td><td>${size(x.size)}</td><td class="small muted">${ago(x.at)}</td><td class="act">${x.stage === 'Searchable' ? `<button class="icon-btn sm" data-act="sc-insearch" data-name="${esc(x.file.replace(/\.\w+$/, '').replace(/_/g, ' '))}" data-tip="Open in search" aria-label="Open in search">${icon('search')}</button>` : ''}<button class="icon-btn sm" data-act="sc-retry" data-id="${x.id}" data-tip="Process it again" aria-label="Process it again">${icon('refresh')}</button><button class="icon-btn sm" data-act="sc-del" data-id="${x.id}" data-tip="Delete this upload and its file" aria-label="Delete">${icon('delete')}</button></td></tr>`).join('')}</table></div>`}`;
}
acts['sc-share'] = async () => { try { const r = await api('POST', `/api/scout/collections/${SC.role}/share`); toast(`Shared ${r.count} people with ${r.manager}.`); fresh('scCols'); rerender(); } catch (e) { toast(e.message, 'err'); } };
acts['sc-post-new'] = () => modal({ title: 'New job posting', text: 'Resumes are filed under a posting. The hiring manager sees the shortlist you share.', body: `<div class="stack" style="gap:10px"><input class="input" id="sp-n" placeholder="Role, for example Project Manager, Solar"><select class="input" id="sp-m"><option value="">Hiring manager (can be added later)</option>${S.boot.users.map(u => `<option value="${u.id}">${esc(u.name)}</option>`).join('')}</select></div>`, actions: [{ label: 'Create', run: async o => { await api('POST', '/api/scout/collections', { name: $('#sp-n', o).value, managerId: $('#sp-m', o).value }); fresh('scCols'); rerender(); } }] });
ins['sc-post'] = async el => { try { await api('PATCH', '/api/scout/collections/' + el.dataset.id, { [el.dataset.k]: el.value }); toast('Saved.'); } catch (e) { toast(e.message, 'err'); } fresh('scCols'); rerender(); };
acts['sc-verdict'] = async el => { await api('POST', '/api/scout/reviews', { collectionId: el.dataset.c, key: el.dataset.key, verdict: el.dataset.on ? '' : el.dataset.v }); fresh('scRev', 'scList'); rerender(); };
acts['sc-test'] = async () => { const r = await api('POST', '/api/scout/admin/test'); modal({ title: `Answered in ${r.ms} ms`, text: r.sample, cancel: 'Close' }); };
acts['sc-erase-find'] = () => { SC.eq = $('#sc-eq').value.trim(); fresh('scAdmin'); rerender(); };
acts['sc-erase'] = el => confirmBox(`Erase ${el.dataset.name}?`, 'Every version of their resume is removed from search, from disk and from every shortlist. This cannot be undone.', 'Erase', async () => { const r = await api('DELETE', '/api/scout/person/' + encodeURIComponent(el.dataset.key)); toast(`${r.removed} version${r.removed === 1 ? '' : 's'} erased.`); fresh('scAdmin', 'scHealth', 'scList'); rerender(); }, true);
function scPostings(cols) {
  return `<div class="row" style="margin-bottom:14px"><span class="grow"></span><button class="btn" data-act="sc-post-new">${icon('add')}New job posting</button></div>
    ${!cols ? loading : !cols.length ? `<div class="empty">${icon('work_outline')}No job postings yet. Make one, then add resumes to it.</div>` : `<div class="card" style="padding:0;overflow:auto"><table class="list"><tr><th>Job posting</th><th>Hiring manager</th><th>Resumes</th><th>Shortlisted</th><th>Status</th></tr>${cols.map(c => `<tr><td><b>${esc(c.name)}</b><div class="small muted">${esc(c.by)}${c.sharedAt ? ' · shortlist shared ' + ago(c.sharedAt) : ''}</div></td><td><select class="input" style="width:auto;height:30px" data-change="sc-post" data-id="${c.id}" data-k="managerId" aria-label="Hiring manager"><option value="">Nobody yet</option>${S.boot.users.map(u => `<option value="${u.id}" ${c.managerId === u.id ? 'selected' : ''}>${esc(u.name)}</option>`).join('')}</select></td><td>${c.count}</td><td>${c.shortlisted}</td><td><select class="input" style="width:auto;height:30px" data-change="sc-post" data-id="${c.id}" data-k="status" aria-label="Status"><option value="open" ${c.status === 'open' ? 'selected' : ''}>Open</option><option value="closed" ${c.status === 'closed' ? 'selected' : ''}>Closed</option></select></td></tr>`).join('')}</table></div>`}`;
}
function scReview(R) {
  return !R ? loading : !R.length ? `<div class="empty">${icon('rate_review')}Nothing is waiting for you.</div>` : R.map(c => `<div class="card" style="margin-bottom:16px"><div class="card-head"><h3>${esc(c.name)}</h3><span class="small muted">Shared by ${esc(c.sharedBy)} ${ago(c.sharedAt)}</span></div>${c.people.map(p => `<div class="set-row" style="align-items:flex-start;flex-wrap:wrap"><div class="grow" style="min-width:220px"><div class="lbl">${esc(p.name)}</div><div class="small muted">${esc(p.title)}${p.years ? ` · ${p.years} yrs` : ''}${p.location ? ' · ' + esc(p.location) : ''}</div><div class="small" style="margin-top:4px">${esc(p.summary)}</div><div class="row wrap" style="gap:4px;margin-top:6px">${p.skills.map(k => `<span class="tag">${esc(k)}</span>`).join('')}</div></div>
      <div class="row" style="gap:6px"><button class="btn ghost ${p.verdict === 'interview' ? 'on' : ''}" data-act="sc-verdict" data-c="${c.id}" data-key="${esc(p.key)}" data-v="interview" ${p.verdict === 'interview' ? 'data-on="1"' : ''}>Interview</button><button class="btn ghost ${p.verdict === 'pass' ? 'on' : ''}" data-act="sc-verdict" data-c="${c.id}" data-key="${esc(p.key)}" data-v="pass" ${p.verdict === 'pass' ? 'data-on="1"' : ''}>Pass</button></div></div>`).join('')}</div>`).join('');
}
function scAdmin() {
  const A = get('scAdmin', SC.eq || '', '/api/scout/admin?q=' + encodeURIComponent(SC.eq || '')); if (!A) return loading;
  return `<div class="stack" style="gap:16px;max-width:760px"><div class="card"><div class="card-head"><h3>Models</h3><span class="grow"></span><button class="btn ghost" data-act="sc-test">Test</button></div>${A.models.map(m => `<div class="set-row"><div class="grow lbl">${m.role}</div><span class="small muted">${esc(m.model)}</span></div>`).join('')}<div class="set-row"><div class="grow lbl">Resumes that can be searched</div><b>${A.indexed}</b></div></div>
    <div class="card"><div class="set-row"><div class="grow"><div class="lbl">People and roles</div><div class="small muted">Who can use Scout, and as what, is set in the console.</div></div>${S.boot.admin ? '<a class="btn ghost" href="#/os/apps/scout/people">Open</a>' : ''}</div></div>
    <div class="card"><div class="card-head"><h3>Erase a person</h3>${info('For a privacy request. Every version of their resume is removed.')}</div><div class="row" style="gap:8px"><input class="input grow" id="sc-eq" data-enter="sc-erase-find" value="${esc(SC.eq || '')}" placeholder="Name or email"><button class="btn ghost" data-act="sc-erase-find">Find</button></div>${A.people.map(p => `<div class="set-row"><div class="grow"><div class="lbl">${esc(p.name)}</div><div class="small muted">${esc(p.email)} · ${p.versions} version${p.versions === 1 ? '' : 's'}</div></div><button class="btn danger" style="height:30px" data-act="sc-erase" data-key="${esc(p.key)}" data-name="${esc(p.name)}">Erase</button></div>`).join('') || (SC.eq ? '<p class="muted" style="margin-top:10px">Nobody by that name.</p>' : '')}</div></div>`;
}
export function scoutPage(tab = '') {
  const h = get('scHealth', 'h', '/api/scout/health'), cols = get('scCols', 'c', '/api/scout/collections'), rev = get('scRev', 'r', '/api/scout/reviews');
  const T = [['', 'Search'], ['shortlist', 'Shortlist'], ['uploads', 'My uploads'], ['postings', 'Job postings'], ...(rev && rev.length ? [['review', `For my review`]] : []), ...(h && h.role === 'Scout admin' ? [['admin', 'Admin']] : [])];
  if (!T.some(t => t[0] === tab)) tab = '';
  const body = tab === 'shortlist' ? scShortlist(cols) : tab === 'uploads' ? scUploads(cols) : tab === 'postings' ? scPostings(cols) : tab === 'review' ? scReview(rev) : tab === 'admin' ? scAdmin() : scSearch(cols, h);
  const subs = { '': 'Ranked matches from your own backlog', shortlist: 'People you kept, and the ones you passed on', uploads: 'Resumes you added, and where each one is', postings: 'Each role, its hiring manager and its resumes', review: 'Shortlists shared with you', admin: 'Models, people and privacy requests' };
  return appShell('scout', 'Scout', `<div class="page-head"><div class="grow"><h1>Scout</h1><p class="sub">${subs[tab]}${h ? ` · ${h.indexed} resumes` : ''}</p></div></div>
    ${h && h.stub ? `<div class="banner" style="margin-bottom:14px">${icon('science')}<span>No model is connected in this build. Resumes are read and ranked by plain rules.</span></div>` : ''}${tabs('#/app/scout', T, tab)}${body}`);
}

// =====================================================================================================================
// Vanik MeasureBook
// =====================================================================================================================
const MB = { mode: 'single', files: [], disc: 'auto', room: '', dim: '', vl: false, tool: '', pts: [], hide: false, group: false, side: true, view: '2d', sel: '', zoom: 100, scaleOn: false, scalePts: [], edit: false, model: null, btab: 'all', busy: false };
const CONF = { High: 'var(--vnk-ok)', Medium: 'var(--vnk-warn)', Low: 'var(--vnk-err)' }, LAYER = { 2: 'Text Extraction', 3: 'Vector Analysis', 4: 'VL Detection', 5: 'Parametric Rules' };
const DISCS = [['auto', 'Auto-detect (recommended)'], ['hvac', 'HVAC'], ['plumbing', 'Plumbing'], ['electrical', 'Electrical'], ['fire_protection', 'Fire Protection'], ['structural', 'Structural'], ['civil', 'Civil / Architectural'], ['pid', 'P&ID']];
const mbReset = () => Object.assign(MB, { review: false, book: '', price: null, tool: '', pts: [], hide: false, sel: '', zoom: 100, scaleOn: false, scalePts: [], edit: false, view: '2d' });
acts['mb-mode'] = el => { MB.mode = el.dataset.v; MB.files = []; rerender(); };
acts['mb-pick'] = async () => { const fs = [...await pickAny(MB.mode === 'batch', '.pdf')].map(f => ({ name: f.name, size: f.size })); if (!fs.length) return; const bad = fs.filter(f => !/\.pdf$/i.test(f.name)); if (bad.length && MB.mode === 'single') return toast('PDF only. Multi-page supported.', 'err'); MB.files = MB.mode === 'batch' ? [...MB.files, ...fs] : fs.slice(0, 1); rerender(); };
acts['mb-clear'] = () => { MB.files = []; rerender(); };
ins['mb-opt'] = el => { MB[el.dataset.k] = el.type === 'checkbox' ? el.checked : el.value; };
acts['mb-start'] = async () => { if (!MB.files.length) return toast(MB.mode === 'batch' ? 'Drop at least one PDF drawing.' : 'Drop a PDF drawing first.', 'err'); MB.busy = true; rerender(); const o = { discipline: MB.disc, scaleRoom: MB.room, scaleDim: MB.dim, vlVerify: MB.vl }; try { if (MB.mode === 'batch') { const r = await api('POST', '/api/measurebook/analyze-batch', { ...o, files: MB.files }); MB.files = []; go('#/app/measurebook/batch/' + r.batch_job_id); } else { const r = await api('POST', '/api/measurebook/analyze', { ...o, file: MB.files[0] }); MB.files = []; mbReset(); go('#/app/measurebook/job/' + r.job_id); } } catch (e) { toast(e.message, 'err'); } MB.busy = false; rerender(); };
acts['mb-tool'] = el => { menu(el, [['count', 'Point count'], ['line', 'Line length (RMT)'], ['area', 'Area (SQMT)'], ['', 'Off']].map(t => ({ label: t[1], run: () => { MB.tool = t[0]; MB.pts = []; MB.scaleOn = false; rerender(); } }))); };
acts['mb-scale'] = () => { MB.scaleOn = !MB.scaleOn; MB.scalePts = []; MB.tool = ''; rerender(); };
acts['mb-apply-scale'] = async () => { const mm = +($('#mb-mm') || {}).value; if (MB.scalePts.length < 2 || !(mm > 0)) return toast('Need two clicked points and a distance value', 'err'); const j = await put('mbJob', 'PUT', `/api/measurebook/jobs/${P.mbJob.id}/scale`, { sheet: 1, a: MB.scalePts[0], b: MB.scalePts[1], mm }); if (j) { MB.scaleOn = false; MB.scalePts = []; rerender(); } };
acts['mb-click'] = (el, e) => { if (!MB.tool && !MB.scaleOn) return; const svg = el.closest('svg'), r = svg.getBoundingClientRect(), pt = [Math.round((e.clientX - r.left) * 800 / r.width), Math.round((e.clientY - r.top) * 520 / r.height)]; if (MB.scaleOn) MB.scalePts = [...MB.scalePts, pt].slice(-2); else MB.pts = [...MB.pts, pt]; rerender(); };
acts['mb-undo'] = () => { MB.pts = []; rerender(); };
acts['mb-flag'] = el => { MB[el.dataset.k] = !MB[el.dataset.k]; rerender(); };
acts['mb-view'] = el => { MB.view = el.dataset.v; rerender(); };
acts['mb-zoom'] = el => { MB.zoom = Math.max(50, Math.min(200, MB.zoom + +el.dataset.v)); rerender(); };
acts['mb-row'] = el => { MB.sel = MB.sel === el.dataset.tag ? '' : el.dataset.tag; rerender(); };
acts['mb-check'] = el => put('mbJob', 'PUT', `/api/measurebook/jobs/${P.mbJob.id}/items/${encodeURIComponent(el.dataset.tag)}`, { sheet: 1, checked: !el.dataset.on });
ins['mb-book'] = async el => { MB.book = el.value; MB.price = el.value ? await api('POST', '/api/measurebook/estimate', { job_id: P.mbJob.id, rate_book: el.value }) : null; rerender(); };
acts['mb-approve'] = async el => { const j = await put('mbJob', 'POST', `/api/measurebook/jobs/${P.mbJob.id}/approve`, { reopen: !!el.dataset.re }); if (j) { toast(j.approved ? 'Approved and locked.' : 'Reopened.'); fresh('mbJobs'); } };
acts['mb-log'] = () => modal({ title: 'Corrections', cancel: 'Close', body: P.mbJob.log.length ? P.mbJob.log.map(l => `<div class="set-row"><div class="grow"><b>${esc(l.tag)}</b> ${l.from ?? 'none'} to ${l.to ?? 'none'}<div class="small muted">${esc(l.by)}</div></div><span class="small faint">${ago(l.at)}</span></div>`).join('') : '<p class="muted">No quantity has been changed.</p>' });
ins['mb-qty'] = el => put('mbJob', 'PUT', `/api/measurebook/jobs/${P.mbJob.id}/items/${encodeURIComponent(el.dataset.tag)}`, { sheet: 1, qty: el.value });
acts['mb-export'] = async () => { const r = await api('GET', `/api/measurebook/jobs/${P.mbJob.id}/download`); downloadText(r.name, r.text); };
acts['mb-bexport'] = async () => { const r = await api('GET', `/api/measurebook/batch/${P.mbBatch.id}/download`); downloadText(r.name, r.text); };
acts['mb-btab'] = el => { MB.btab = el.dataset.v; rerender(); };
acts['mb-model'] = async el => { const f = (await pickAny(false, '.ifc,.glb,.gltf,.obj'))[0]; if (!f) return; const ext = (f.name.split('.').pop() || '').toLowerCase(); if (!['ifc', 'glb', 'gltf', 'obj'].includes(ext)) return toast(`Unsupported file format: .${ext}. Supported: .ifc, .glb, .gltf, .obj`, 'err'); MB.model = { name: f.name, size: f.size, format: ext.toUpperCase() }; rerender(); };
const dist = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]);
function mbDrawing(s) {
  const dim = t => MB.sel && MB.sel !== t ? 0.15 : 1, items = MB.hide ? [] : s.items;
  const find = items.map(it => { const c = CONF[it.conf], o = dim(it.tag), hot = MB.sel === it.tag; return (it.polys || []).map(p => `<polygon points="${p.map(q => q.join(',')).join(' ')}" fill="${c}" fill-opacity="${hot ? 0.35 : 0.12}" stroke="${c}" stroke-width="${hot ? 3 : 1.5}" opacity="${o}"/>`).join('') + (it.paths || []).map(p => `<polyline points="${p.map(q => q.join(',')).join(' ')}" fill="none" stroke="${c}" stroke-width="${hot ? 7 : 4}" stroke-linecap="round" stroke-linejoin="round" opacity="${o * 0.8}"/>`).join('') + (it.pts || []).map(q => `<g opacity="${o}"><circle cx="${q[0]}" cy="${q[1]}" r="${hot ? 11 : 8}" fill="${c}" fill-opacity=".25" stroke="${c}" stroke-width="2"/><text x="${q[0]}" y="${q[1] - 12}" text-anchor="middle" font-size="9" fill="${c}">${esc(it.tag)}</text></g>`).join(''); }).join('');
  const base = s.line ? `<polyline points="${s.line.map(q => q.join(',')).join(' ')}" fill="none" stroke="currentColor" stroke-width="2.5"/><polyline points="230,220 230,290" fill="none" stroke="currentColor" stroke-width="2"/><text x="90" y="330" font-size="11" fill="currentColor">100-CW-101-A1A</text>` : s.rooms.map(r => `<rect x="${r[1]}" y="${r[2]}" width="${r[3]}" height="${r[4]}" fill="none" stroke="currentColor" stroke-width="2"/><text x="${r[1] + r[3] / 2}" y="${r[2] + r[4] / 2 - 4}" text-anchor="middle" font-size="11" fill="currentColor" opacity=".7">${r[0]}</text><text x="${r[1] + r[3] / 2}" y="${r[2] + r[4] / 2 + 10}" text-anchor="middle" font-size="9" fill="currentColor" opacity=".45">${r[5]}</text>`).join('');
  const mark = (pts, closed) => pts.length ? `<${closed && pts.length > 2 ? 'polygon' : 'polyline'} points="${pts.map(q => q.join(',')).join(' ')}" fill="${closed ? 'var(--vnk-accent)' : 'none'}" fill-opacity=".15" stroke="var(--vnk-accent)" stroke-width="2" stroke-dasharray="6 4"/>${pts.map((q, i) => `<circle cx="${q[0]}" cy="${q[1]}" r="5" fill="var(--vnk-accent)"/><text x="${q[0] + 8}" y="${q[1] - 6}" font-size="10" fill="var(--vnk-accent)">${i + 1}</text>`).join('')}` : '';
  return `<svg viewBox="0 0 800 520" style="width:${MB.zoom}%;cursor:${MB.tool || MB.scaleOn ? 'crosshair' : 'default'}" data-act="mb-click" role="img" aria-label="Drawing sheet"><rect x="0" y="0" width="800" height="520" fill="var(--vnk-surface)"/><g style="color:var(--vnk-ink-2)">${base}<rect x="600" y="490" width="190" height="24" fill="none" stroke="currentColor"/><text x="606" y="506" font-size="9" fill="currentColor">${esc(s.title.slice(0, 34))}</text></g>${find}${mark(MB.scalePts)}${mark(MB.pts, MB.tool === 'area')}</svg>`;
}
function mbJob(id) {
  const j = get('mbJob', id, '/api/measurebook/jobs/' + id);
  if (!j || j.status !== 'done') { if (j) setTimeout(() => { if (on('#/app/measurebook/job/' + id)) { fresh('mbJob'); rerender(); } }, 700); return appShell('measurebook', 'MeasureBook', `<div class="empty" style="margin-top:60px">${icon('auto_awesome')}<b>AI is reading your drawing</b><br>${esc(j ? j.step : 'Uploading file...')}<br><span class="small faint">${esc(j ? j.filename : '')}</span></div>`); }
  const s = j.sheets[0], k = s.mmPerPx, m = MB.pts, meas = MB.tool === 'count' ? `${m.length} point${m.length === 1 ? '' : 's'}` : MB.tool === 'line' ? (k ? (m.slice(1).reduce((a, q, i) => a + dist(m[i], q), 0) * k / 1000).toFixed(2) + ' RMT' : 'Scale not set') : MB.tool === 'area' ? (k ? (Math.abs(m.reduce((a, q, i) => a + q[0] * m[(i + 1) % m.length][1] - m[(i + 1) % m.length][0] * q[1], 0)) / 2 * k * k / 1e6).toFixed(2) + ' SQMT' : 'Scale not set') : '';
  const RANK = { Low: 0, Medium: 1, High: 2 }, rows = MB.review ? [...s.items].sort((a, b) => RANK[a.conf] - RANK[b.conf]) : MB.group ? [...s.items].sort((a, b) => a.layer - b.layer) : s.items; let last = 0;
  const pr = MB.price && Object.fromEntries(MB.price.rows.map(r => [r.tag, r])), left = s.items.filter(it => it.conf === 'Low' && !j.checked[it.tag]).length, done = s.items.filter(it => j.checked[it.tag]).length, lock = !!j.approved;
  const table = `<div class="card" style="padding:0;overflow:auto"><div class="card-head" style="padding:14px 16px 0"><h3>Extracted Data</h3><span class="small muted">Click a row to locate on drawing</span></div><table class="list"><tr>${MB.review ? '<th></th>' : ''}<th>S.No</th><th>Tag</th><th>Description</th><th>Qty</th><th>Unit</th><th>Spec</th><th>Conf.</th>${pr ? '<th>Rate</th><th>Amount</th>' : ''}</tr>${!rows.length ? '<tr><td colspan="7" class="muted" style="text-align:center">No data for this sheet</td></tr>' : rows.map(it => `${MB.group && !MB.review && it.layer !== last ? `<tr><td colspan="7" class="cap">Layer ${last = it.layer} · ${LAYER[it.layer]}</td></tr>` : ''}<tr class="${MB.sel === it.tag ? 'sel' : ''}" style="cursor:pointer" data-act="mb-row" data-tag="${esc(it.tag)}">${MB.review ? `<td><button class="icon-btn sm" data-act="mb-check" data-stop data-tag="${esc(it.tag)}" ${j.checked[it.tag] ? 'data-on="1"' : ''} ${lock ? 'disabled' : ''} aria-label="Checked">${icon(j.checked[it.tag] ? 'check_circle' : 'radio_button_unchecked')}</button></td>` : ''}<td class="mono">${it.sno}</td><td><b>${esc(it.tag)}</b></td><td>${esc(it.desc)}${it.edited ? ' <span class="small faint">edited</span>' : ''}</td><td>${MB.edit && !lock ? `<input class="input" style="width:80px;padding:3px 6px" value="${it.qty ?? ''}" data-change="mb-qty" data-tag="${esc(it.tag)}" aria-label="Quantity">` : it.qty == null ? '<span class="faint">set scale</span>' : `<b>${it.qty}</b>`}</td><td>${it.unit}</td><td class="small muted">${esc(it.spec)}</td><td><span class="chip" style="color:${CONF[it.conf]}">${it.conf}</span></td>${pr ? `<td class="mono">${pr[it.tag] ? pr[it.tag].rate.toLocaleString('en-IN') : ''}</td><td class="mono">${pr[it.tag] && pr[it.tag].amount != null ? pr[it.tag].amount.toLocaleString('en-IN') : ''}</td>` : ''}</tr>`).join('')}${pr ? `<tr><td colspan="${MB.review ? 8 : 7}" style="text-align:right"><b>Total, ${esc(MB.price.rate_book)}</b></td><td></td><td class="mono"><b>${MB.price.total.toLocaleString('en-IN')}</b></td></tr>` : ''}</table></div>`;
  const three = `<div class="card"><div class="row wrap" style="gap:6px;margin-bottom:12px">${['Load IFC', 'Load GLB', 'Load OBJ'].map(b => `<button class="btn ghost" data-act="mb-model">${b}</button>`).join('')}<span class="grow"></span><button class="btn ghost" disabled>Reset</button><button class="btn ghost" disabled>Grid</button><button class="btn ghost" disabled>Axes</button><button class="btn ghost" disabled>Wire</button></div>
    <div class="empty" style="min-height:300px;display:grid;place-content:center">${icon('view_in_ar')}${MB.model ? `<b>${esc(MB.model.format)} · ${esc(MB.model.name)}</b><br><span class="small muted">Triangles: 0 · Meshes: 0 · Size: ${size(MB.model.size)}</span>` : `<b>3D Model View</b><br>Load an IFC, GLB, or OBJ file to view in 3D<br><span class="small faint">.ifc · .glb / .gltf · .obj</span>`}</div></div>`;
  const tb = (act, ic, label, on2, extra = '') => `<button class="btn ghost ${on2 ? 'on' : ''}" data-act="${act}" ${extra}>${icon(ic)}${label}</button>`;
  return appShell('measurebook', `<a href="#/app/measurebook">MeasureBook</a> / ${esc(j.filename)}`, `<div class="page-head"><div class="grow"><h1>${esc(j.filename)}</h1><p class="sub">Drawing workspace · ${j.sheets.length} open sheet${j.sheets.length === 1 ? '' : 's'}</p></div>${chip('AI reading done', 'ok')}${chip('Saved', '', false)}<a class="btn ghost" href="#/app/measurebook">${icon('add')}New</a><button class="btn" data-act="mb-export">${icon('download')}Export</button></div>
    <div class="row wrap" style="gap:6px;margin-bottom:10px">${tb('mb-tool', 'straighten', 'Measure' + (MB.tool ? ': ' + { count: 'Point count', line: 'Line length', area: 'Area' }[MB.tool] : ''), !!MB.tool)}${tb('mb-flag', 'draw', 'Markup', false, 'data-k="markup" disabled')}${tb('mb-flag', 'edit', 'Edit', MB.edit, 'data-k="edit"')}${tb('mb-scale', 'square_foot', 'Set scale', MB.scaleOn)}${tb('mb-flag', MB.hide ? 'visibility' : 'visibility_off', MB.hide ? 'Show all findings' : 'Hide all findings', MB.hide, 'data-k="hide"')}<span class="grow"></span>${tb('mb-flag', 'vertical_split', 'Side by side', MB.side, 'data-k="side"')}${tb('mb-flag', 'segment', MB.group ? 'Grouped view' : 'Ungrouped view', MB.group, 'data-k="group"')}<div class="seg"><button class="${MB.view === '2d' ? 'on' : ''}" data-act="mb-view" data-v="2d">2D</button><button class="${MB.view === '3d' ? 'on' : ''}" data-act="mb-view" data-v="3d">3D</button></div></div>
    <div class="row wrap" style="gap:8px;margin-bottom:12px"><span class="tag on">Sheet 1</span><span class="tag">${esc(j.disciplineName)}</span><span class="tag">${k ? `${k} mm per px · ${esc(s.scaleFrom)}` : 'Scale not set'}</span>${meas ? `<span class="chip ok">${meas}</span><button class="btn ghost" data-act="mb-undo">Clear</button>` : ''}<span class="grow"></span><span class="small muted">1 / 1</span><button class="icon-btn sm" data-act="mb-zoom" data-v="-25" aria-label="Zoom out">${icon('remove')}</button><span class="small mono">${MB.zoom}%</span><button class="icon-btn sm" data-act="mb-zoom" data-v="25" aria-label="Zoom in">${icon('add')}</button></div>
    <div class="card" style="margin-bottom:12px;padding:12px 16px"><div class="row wrap" style="gap:10px"><button class="toggle ${MB.review ? 'on' : ''}" data-act="mb-flag" data-k="review">Review, least certain first</button><span class="small muted">${done} of ${s.items.length} checked${left ? ` · ${left} low-confidence left` : ''}</span><button class="btn text" data-act="mb-log">Corrections ${j.log.length ? `<span class="mono">${j.log.length}</span>` : ''}</button><span class="grow"></span><select class="input" style="width:auto;height:30px" data-change="mb-book" aria-label="Rate book"><option value="">No prices</option><option value="cpwd_2024" ${MB.book === 'cpwd_2024' ? 'selected' : ''}>Price with CPWD Delhi 2024</option><option value="mes_2024" ${MB.book === 'mes_2024' ? 'selected' : ''}>Price with MES 2024</option></select>${lock ? `${chip('Approved by ' + j.approved.by, 'ok')}<button class="btn text" data-act="mb-approve" data-re="1">Reopen</button>` : `<button class="btn" data-act="mb-approve">${icon('verified')}Approve</button>`}</div></div>
    ${MB.scaleOn ? `<div class="card" style="margin-bottom:12px"><div class="card-head"><h3>Calibrate Drawing Scale</h3></div><p class="small muted">Click two points on the drawing, then enter the real-world distance between them.</p><div class="row wrap" style="gap:8px;margin-top:10px"><span class="small">${MB.scalePts.length < 2 ? 'Click two points on the drawing to set scale...' : 'Two points selected. Enter distance (mm) and click Apply Scale.'}</span><span class="grow"></span><input class="input" id="mb-mm" style="width:150px" type="number" placeholder="Distance (mm)"><button class="btn" data-act="mb-apply-scale">Apply Scale</button></div></div>` : ''}
    <div class="${MB.side ? 'mb-ws' : 'stack'}" style="gap:16px">${MB.view === '3d' ? three : `<div class="card mb-draw" style="padding:10px;overflow:auto">${mbDrawing(s)}</div>`}${table}</div>`);
}
function mbBatch(id) {
  const b = get('mbBatch', id, '/api/measurebook/batch/' + id);
  if (!b || b.status !== 'done') { if (b) setTimeout(() => { if (on('#/app/measurebook/batch/' + id)) { fresh('mbBatch'); rerender(); } }, 600); return appShell('measurebook', 'MeasureBook', `<div class="empty" style="margin-top:60px">${icon('auto_awesome')}<b>Processing tender set</b><br>${b ? `${b.done} / ${b.total}` : 'Starting...'}<div class="sbar" style="margin:12px auto"><i style="width:${b ? Math.round(100 * b.done / b.total) : 0}%"></i></div><span class="small faint">${esc(b ? b.current : '')}</span></div>`); }
  const st = b.stats, rows = b.boq.filter(r => MB.btab === 'all' || r.discipline === MB.btab);
  return appShell('measurebook', `<a href="#/app/measurebook">MeasureBook</a> / Tender set`, `<div class="page-head"><div class="grow"><h1>Tender Set Takeoff</h1><p class="sub">${st.files} files · ${st.pages} pages · ${st.disciplines} disciplines</p></div><a class="btn ghost" href="#/app/measurebook">${icon('add')}New</a><button class="btn" data-act="mb-bexport">${icon('download')}Export Unified BOQ</button></div>
    <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;margin-bottom:16px">${[['Files', st.files], ['Pages', st.pages], ['Disciplines', st.disciplines], ['Component Types', st.types], ['Total Items', st.items]].map(x => `<div class="card stat"><span class="small muted">${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
    <div class="card" style="margin-bottom:16px"><div class="card-head"><h3>By Discipline</h3></div><div class="row wrap" style="gap:6px">${b.byDiscipline.map(d => `<span class="tag">${esc(d.name)} <b>${d.n}</b></span>`).join('')}</div>
      <div class="card-head" style="margin-top:16px"><h3>Drawings in Set</h3></div><div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px">${b.files.map(f => f.error ? `<div class="card" style="text-align:center;border-color:var(--vnk-err)"><span class="chip err">Error</span><div class="small muted" style="margin-top:8px;overflow-wrap:anywhere">${esc(f.name)}</div></div>` : `<a class="card" style="text-align:center" href="#/app/measurebook/job/${f.jobId}">${icon('picture_as_pdf')}<div class="small" style="margin-top:6px;overflow-wrap:anywhere">${esc(f.name)}</div><div class="small faint">${esc((DISCS.find(d => d[0] === f.discipline) || ['', ''])[1])}</div></a>`).join('')}</div></div>
    <div class="card" style="padding:0;overflow:auto"><div class="card-head" style="padding:14px 16px 0"><h3>Unified BOQ (All Trades)</h3></div><div class="row wrap" style="gap:6px;padding:10px 16px"><button class="tag ${MB.btab === 'all' ? 'on' : ''}" data-act="mb-btab" data-v="all">All</button>${b.byDiscipline.map(d => `<button class="tag ${MB.btab === d.id ? 'on' : ''}" data-act="mb-btab" data-v="${d.id}">${esc(d.name)}</button>`).join('')}</div>
      <table class="list"><tr><th>S.No</th><th>Tag</th><th>Description</th><th>Qty</th><th>Unit</th><th>Sources</th></tr>${rows.map(r => `<tr><td class="mono">${r.sno}</td><td><b>${esc(r.tag)}</b></td><td>${esc(r.desc)}</td><td><b>${r.qty}</b></td><td>${r.unit}</td><td class="small muted">${esc(r.sources.slice(0, 2).join(', '))}${r.sources.length > 2 ? ` +${r.sources.length - 2} more` : ''}</td></tr>`).join('')}</table></div>`);
}
export function mbPage(sub, id) {
  if (sub === 'job' && id) return mbJob(id);
  if (sub === 'batch' && id) return mbBatch(id);
  const recent = get('mbJobs', 'l', '/api/measurebook/jobs'), L = [['LAYER 2', 'Text Extraction', 'Tags & annotations', 'High confidence'], ['LAYER 3', 'Vector Analysis', 'CAD color layers', 'Medium confidence'], ['LAYER 4', 'VL Detection', 'Unlabeled symbols', 'Low confidence'], ['LAYER 5', 'Parametric Rules', 'Standard sizes', 'Inference']], batch = MB.mode === 'batch';
  return appShell('measurebook', 'MeasureBook', `<div style="max-width:860px;margin:0 auto"><div style="text-align:center;margin:10px 0 22px"><div class="cap">MEASUREBOOK</div><h1 style="margin-top:6px">Drop in the drawing set.</h1><p class="muted" style="margin-top:8px">Any discipline: HVAC, plumbing, electrical, structural, P&amp;ID, fire protection. The engine reads it the way your best estimator would.</p>
      <div class="seg" style="margin-top:16px"><button class="${!batch ? 'on' : ''}" data-act="mb-mode" data-v="single">Single Drawing</button><button class="${batch ? 'on' : ''}" data-act="mb-mode" data-v="batch">Tender Set (Batch)</button></div></div>
    <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin-bottom:16px">${L.map(x => `<div class="card"><div class="cap">${x[0]}</div><b>${x[1]}</b><div class="small muted">${x[2]}</div><div class="small faint" style="margin-top:6px">${x[3]}</div></div>`).join('')}</div>
    <button class="empty" style="width:100%" data-act="mb-pick">${icon('upload_file')}<b>${batch ? 'Drop multiple PDF drawings here' : 'Drop PDF drawing here'}</b><br><span class="small faint">${batch ? 'Upload an entire tender set: Vol 1-8, all disciplines' : 'or click to browse · PDF only · Multi-page supported'}</span></button>
    ${MB.files.length ? `<div class="card" style="margin-top:12px"><div class="row"><b>${MB.files.length} file${MB.files.length === 1 ? '' : 's'} selected</b><span class="grow"></span><button class="btn ghost" data-act="mb-clear">Clear all</button></div>${MB.files.map(f => `<div class="set-row">${icon('picture_as_pdf')}<div class="grow lbl">${esc(f.name)}</div><span class="small faint">${size(f.size)}</span></div>`).join('')}</div>` : ''}
    <div class="card" style="margin-top:16px"><div class="card-head"><h3>Analysis Options</h3></div><div class="row wrap" style="gap:12px"><label class="field grow"><span>Discipline</span><select class="input" data-change="mb-opt" data-k="disc">${DISCS.map(d => `<option value="${d[0]}" ${MB.disc === d[0] ? 'selected' : ''}>${d[1]}</option>`).join('')}</select></label><label class="field grow"><span>Scale Reference Room (optional)</span><input class="input" data-on="mb-opt" data-k="room" value="${esc(MB.room)}"></label><label class="field grow"><span>Scale Reference Dimension (optional)</span><input class="input" data-on="mb-opt" data-k="dim" value="${esc(MB.dim)}"></label></div>
      <label class="row" style="gap:8px;margin-top:12px"><input type="checkbox" data-change="mb-opt" data-k="vl" ${MB.vl ? 'checked' : ''}><span>Enable VL model verification (slower, detects unlabeled symbols)</span></label>
      <button class="btn" style="margin-top:16px;width:100%" data-act="mb-start" ${MB.busy ? 'disabled' : ''}>${batch ? 'Process Tender Set' : 'Start Takeoff'}</button></div>
    ${recent && recent.length ? `<div class="card" style="margin-top:16px"><div class="card-head"><h3>Your takeoffs</h3>${info('Only you see these until you share the exported bill.')}</div>${recent.map(r => `<a class="set-row" href="#/app/measurebook/job/${r.id}">${icon('picture_as_pdf')}<div class="grow"><div class="lbl">${esc(r.filename)}</div><div class="small muted">${esc(r.discipline)} · ${r.rows} rows · ${ago(r.at)}</div></div>${r.approved ? chip('Approved', 'ok') : chip('Draft', '', false)}</a>`).join('')}</div>` : ''}</div>`);
}

// =====================================================================================================================
// Vanik Echo
// =====================================================================================================================
acts['ec-start'] = async () => { try { const m = await api('POST', '/api/echo/meetings', { title: ($('#ec-title') || { value: '' }).value }); fresh('ecList'); go('#/app/echo/' + m.id); } catch (e) { toast(e.message, 'err'); } };
acts['ec-end'] = async el => { await put('ecMeet', 'POST', `/api/echo/meetings/${el.dataset.id}/end`); fresh('ecList'); toast('Transcript saved on the appliance.'); };
acts['ec-dl'] = () => { const m = P.ecMeet; downloadText(m.title.replace(/[^\wऀ-ॿ ]+/g, '').trim() + '.txt', m.lines.map(l => `[${l.t}] ${l.speaker}: ${l.text}`).join('\n')); };
acts['ec-del'] = el => confirmBox('Delete this transcript?', 'It is removed from the appliance.', 'Delete', async () => { await api('DELETE', '/api/echo/meetings/' + el.dataset.id); fresh('ecList'); go('#/app/echo'); }, true);
acts['ec-sense'] = async el => { const m = await put('ecMeet', 'POST', `/api/echo/meetings/${el.dataset.id}/to-sense`); if (m) toast('Sent. The meeting is now in Vanik Sense.'); };
let ecTimer = 0;
export function echoPage(id) {
  if (id) {
    const m = get('ecMeet', id, '/api/echo/meetings/' + id); if (!m) return appShell('echo', 'Echo', loading);
    if (m.live && m.more && !ecTimer) ecTimer = setTimeout(async () => { ecTimer = 0; if (!on('#/app/echo/' + id)) return; try { P.ecMeet = await api('POST', `/api/echo/meetings/${id}/utterance`); rerender(); const sc = $('#scroll'); if (sc) sc.scrollTop = sc.scrollHeight; } catch (e) { /* ended elsewhere */ } }, 2400);
    return appShell('echo', `<a href="#/app/echo">Echo</a> / ${esc(m.title)}`, `<a class="back" href="#/app/echo">${icon('arrow_back')}Meetings</a><div class="page-head"><div class="grow"><h1>${esc(m.title)}</h1><p class="sub">${day(m.startedAt)} · ${m.count} utterances · ${m.speakers} speakers · ${m.language}</p></div>${m.live ? `${chip(m.more ? 'Listening' : 'Waiting for speech', 'ok')}<button class="btn" data-act="ec-end" data-id="${m.id}">${icon('stop_circle')}End meeting</button>` : `${m.sentTo ? `<a class="btn ghost" href="#/app/sense/meetings/${m.sentTo}">Open in Vanik Sense</a>` : `<button class="btn" data-act="ec-sense" data-id="${m.id}">${icon('send')}Send to Vanik Sense</button>`}<button class="btn ghost" data-act="ec-dl">${icon('download')}Download</button><button class="icon-btn" data-act="ec-del" data-id="${m.id}" aria-label="Delete">${icon('delete')}</button>`}</div>
      <div class="card" style="max-width:860px">${m.lines.length ? m.lines.map(l => `<div class="set-row" style="align-items:flex-start;gap:12px"><span class="tag ${['on', '', 'on bad'][(+l.speaker.split(' ')[1] - 1) % 3] || ''}" style="flex:none">${esc(l.speaker)}</span><div class="grow" lang="hi" style="font-size:15px;line-height:1.7">${esc(l.text)}</div><span class="small faint mono">${l.t}</span></div>`).join('') : '<p class="muted">Start talking. Each utterance appears after a pause, labelled with who said it.</p>'}</div>`);
  }
  const L = get('ecList', 'l', '/api/echo'), live = L && L.meetings.find(m => m.live);
  return appShell('echo', 'Echo', `<div class="page-head"><div class="grow"><h1>Echo</h1><p class="sub">A live transcript of a meeting in a room, with who said what.</p></div></div>
    <div class="card" style="max-width:760px;margin-bottom:16px">${live ? `<div class="row"><div class="grow"><b>${esc(live.title)}</b><div class="small muted">A meeting is running</div></div><a class="btn" href="#/app/echo/${live.id}">Open</a></div>` : `<div class="row wrap" style="gap:8px"><input class="input grow" id="ec-title" data-enter="ec-start" placeholder="Meeting title (optional)"><button class="btn" data-act="ec-start">${icon('mic')}Start a meeting</button></div><p class="small faint" style="margin-top:10px">Hindi only for now. Audio is segmented on pauses and transcribed utterance by utterance. Transcripts are saved on the device when the meeting ends.</p>`}</div>
    ${!L ? loading : !L.meetings.filter(m => !m.live).length ? `<div class="empty" style="max-width:760px">${icon('graphic_eq')}No transcripts yet.</div>` : `<div class="card" style="max-width:760px"><div class="card-head"><h3>Saved transcripts</h3></div>${L.meetings.filter(m => !m.live).map(m => `<a class="set-row" href="#/app/echo/${m.id}"><div class="grow"><div class="lbl" lang="hi">${esc(m.title)}</div><div class="small muted">${day(m.startedAt)} · ${m.count} utterances · ${m.speakers} speakers</div></div>${icon('chevron_right')}</a>`).join('')}</div>`}`);
}
