// The four apps that could be read on the testing appliance, screen for screen: Vanik Scout, Vanik MeasureBook, Vanik mBot, and
// Vanik Echo as its catalogue entry describes it. Tabs, controls and words follow ../apps/*.md. Server side: real.js.
import { $, esc, icon, info, chip, go, ago, api, rerender, acts, ins, toast, modal, confirmBox, menu, downloadText } from './core.js';
import { appShell, get, put, P, readFiles } from './suite.js';

const loading = '<p class="muted">Loading…</p>';
const menuD = (el, items) => menu(el, items.filter(i => i && !i.disabled));
const pickAny = (multiple, accept) => new Promise(ok => { const i = document.createElement('input'); i.type = 'file'; i.multiple = multiple; i.accept = accept; i.onchange = () => ok([...i.files]); i.click(); });
const tabs = (base, list, on) => `<nav class="tabs">${list.map(t => `<a class="${t[0] === on ? 'on' : ''}" href="${base}${t[0] ? '/' + t[0] : ''}">${t[1]}</a>`).join('')}</nav>`;
const sw = (on, act, label, extra = '') => `<button class="switch ${on ? 'on' : ''}" role="switch" aria-checked="${!!on}" aria-label="${esc(label)}" data-act="${act}" ${extra}></button>`;
const day = iso => new Date(iso).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
const size = n => n > 1e6 ? (n / 1e6).toFixed(1) + ' MB' : Math.max(1, Math.round(n / 1000)) + ' KB';
const fresh = (...slots) => slots.forEach(s => { P[s + 'Key'] = ''; });
const on = h => location.hash === h || location.hash.startsWith(h + '/');
document.addEventListener('keydown', e => { if (e.key !== 'Enter' || e.shiftKey || !e.target.dataset || !e.target.dataset.enter) return; e.preventDefault(); const f = acts[e.target.dataset.enter]; if (f) f(e.target, e); });

// =====================================================================================================================
// Vanik Scout
// =====================================================================================================================
const SC = { q: '', res: null, busy: false, strict: false, allV: false, col: '', F: {}, sel: '', cand: null, why: 'summary', picks: [], page: 1, role: 'all', showRej: true, scope: 'mine', upCol: '' };
const SCTABS = [['', 'Search'], ['shortlist', 'Shortlist'], ['uploads', 'My uploads'], ['collections', 'Collections'], ['index', 'Index admin'], ['admin', 'Admin']];
const SOON = { collections: ['Collections', 'Job postings you upload résumés into and scope search to'], index: ['Index admin', 'Create, inspect and edit the résumé index'], admin: ['Admin', 'Approve access requests and manage the live model endpoints'] };
async function scRun(mode, extra) {
  SC.busy = true; rerender();
  const base = { collectionId: SC.col, strict: SC.strict, allVersions: SC.allV, filters: SC.F, page: SC.page };
  try {
    SC.res = mode === 'q' ? await api('POST', '/api/scout/search', { ...base, q: SC.q }) : mode === 'refine' ? await api('POST', '/api/scout/refine', { ...base, parsed: SC.res.parsed, text: extra }) : await api('POST', '/api/scout/search/parsed', { ...base, parsed: SC.res.parsed });
    if (!SC.res.hits.some(h => h.id === SC.sel)) { SC.sel = ''; SC.cand = null; }
  } catch (e) { toast(e.message, 'err'); }
  SC.busy = false; rerender();
}
ins['sc-q'] = el => { SC.q = el.value; };
ins['sc-col'] = el => { SC.col = el.value; if (SC.res) { SC.page = 1; scRun(SC.res.browse ? 'q' : 'p'); } };
acts['sc-find'] = () => { SC.q = ($('#sc-q') || { value: SC.q }).value; SC.F = {}; SC.page = 1; SC.picks = []; scRun('q'); };
acts['sc-refine'] = () => { const el = $('#sc-refine'), t = el ? el.value.trim() : ''; if (!t) return; SC.page = 1; scRun('refine', t); };
acts['sc-strict'] = () => { SC.strict = !SC.strict; SC.page = 1; scRun('p'); };
acts['sc-allv'] = () => { SC.allV = !SC.allV; SC.page = 1; scRun('p'); };
acts['sc-page'] = el => { SC.page = +el.dataset.v; scRun('p'); };
acts['sc-facet'] = el => { const k = el.dataset.k, v = el.dataset.v, L = SC.F[k] = SC.F[k] || []; SC.F[k] = L.includes(v) ? L.filter(x => x !== v) : [...L, v]; SC.page = 1; scRun('p'); };
acts['sc-chip'] = el => { const p = SC.res.parsed, s = el.dataset.v, k = el.dataset.k; menu(el, [k === 'must' ? { label: 'Make this a nice-to-have', icon: 'south', run: () => { p.must = p.must.filter(x => x !== s); p.nice.push(s); scRun('p'); } } : { label: 'Make this a must-have', icon: 'north', run: () => { p.nice = p.nice.filter(x => x !== s); p.must.push(s); scRun('p'); } }, { label: 'Remove', icon: 'close', run: () => { p[k] = p[k].filter(x => x !== s); scRun('p'); } }]); };
acts['sc-pref'] = el => { const p = SC.res.parsed, k = el.dataset.k; if (k === 'minYears') p.minYears = 0; else if (k === 'also') p.also = p.also.filter(x => x !== el.dataset.v); else p[k] = k === 'location' ? (p.also.shift() || '') : ''; scRun('p'); };
ins['sc-add'] = el => { if (!el.value) return; const p = SC.res.parsed; if (!p.must.includes(el.value) && !p.nice.includes(el.value)) p.must.push(el.value); scRun('p'); };
acts['sc-drop'] = el => { const p = SC.res.parsed; p.must = p.must.filter(x => x !== el.dataset.v); scRun('p'); };
acts['sc-open'] = async el => { SC.sel = el.dataset.id; SC.cand = null; SC.why = 'summary'; rerender(); try { SC.cand = await api('GET', '/api/scout/candidate/' + SC.sel); rerender(); } catch (e) { toast(e.message, 'err'); } };
acts['sc-why'] = el => { SC.why = el.dataset.v; rerender(); };
acts['sc-full'] = () => modal({ title: SC.cand.profile.name, wide: true, body: `<pre class="code" style="white-space:pre-wrap;max-height:60vh;overflow:auto">${esc(SC.cand.text)}</pre>`, cancel: 'Close' });
const scMark = async (key, status, reason) => { try { await api('POST', '/api/scout/shortlist', { key, status, reason, role: SC.col }); fresh('scList'); await scRun(SC.res && !SC.res.browse ? 'p' : 'q'); } catch (e) { toast(e.message, 'err'); } };
acts['sc-star'] = el => el.dataset.on ? api('DELETE', '/api/scout/shortlist/' + encodeURIComponent(el.dataset.key)).then(() => { fresh('scList'); scRun(SC.res && !SC.res.browse ? 'p' : 'q'); }) : scMark(el.dataset.key, 'shortlisted');
acts['sc-reject'] = el => { const h = P.scHealth; if (el.dataset.on) return acts['sc-star']({ dataset: { on: '1', key: el.dataset.key } }); menu(el, [{ heading: 'Why not?' }, ...((h && h.reasons) || ['Other']).map(r => ({ label: r, run: () => scMark(el.dataset.key, 'rejected', r) }))]); };
acts['sc-pick'] = el => { const k = el.dataset.key; SC.picks = SC.picks.includes(k) ? SC.picks.filter(x => x !== k) : [...SC.picks, k]; rerender(); };
acts['sc-pick-page'] = () => { const ks = SC.res.hits.map(h => h.key); SC.picks = ks.every(k => SC.picks.includes(k)) ? [] : ks; rerender(); };
acts['sc-bulk'] = async el => { const all = el.dataset.v === 'all', n = all ? SC.res.total : SC.picks.length; if (!n) return toast('Select a candidate first.', 'err'); confirmBox(`Shortlist ${all ? 'all ' + n + ' matching' : n} candidate${n === 1 ? '' : 's'}?`, all ? 'Every ranked match for this search.' : 'The ones you ticked on this page.', 'Shortlist', async () => { const r = await api('POST', '/api/scout/shortlist/bulk', { parsed: SC.res.parsed, collectionId: SC.col, strict: SC.strict, allVersions: SC.allV, filters: SC.F, scope: all ? 'all' : 'keys', keys: SC.picks }); toast(r.capped ? `Shortlisted the first ${r.added} (capped at ${r.cap}).` : `Shortlisted ${r.added}.`); SC.picks = []; fresh('scList'); scRun('p'); }); };
ins['sc-role'] = el => { SC.role = el.value; fresh('scList'); rerender(); };
acts['sc-rej-toggle'] = () => { SC.showRej = !SC.showRej; rerender(); };
acts['sc-unlist'] = async el => { await api('DELETE', '/api/scout/shortlist/' + encodeURIComponent(el.dataset.key)); fresh('scList'); rerender(); };
acts['sc-export'] = async el => { const r = await api('GET', '/api/scout/shortlist/export' + (el.dataset.v === 'zip' ? '?kind=zip' : '')); downloadText(r.name, r.text); };
acts['sc-clear'] = () => confirmBox('Clear this list?', 'Rejections are kept.', 'Clear this list', async () => { const r = await api('POST', '/api/scout/shortlist/bulk-remove', { all: true, ...(SC.role === 'all' ? {} : { role: SC.role }) }); toast(`Removed ${r.removed} from the shortlist.`); fresh('scList'); rerender(); }, true);
ins['sc-upcol'] = el => { SC.upCol = el.value; };
acts['sc-newcol'] = () => modal({ title: 'New collection', text: 'The job posting these résumés belong to', body: `<input class="input" id="sc-colname" placeholder="New collection name">`, actions: [{ label: 'Create', run: async o => { const c = await api('POST', '/api/scout/collections', { name: $('#sc-colname', o).value }); SC.upCol = c.id; fresh('scCols'); rerender(); } }] });
acts['sc-upload'] = async () => { if (!SC.upCol) return toast('Pick a collection first. Every résumé is filed under one.', 'err'); const files = await readFiles(); if (!files.length) return; try { const r = await api('POST', '/api/scout/uploads', { collectionId: SC.upCol, files: files.map(f => ({ name: f.name, text: f.text, size: f.text.length })) }); r.rejected.forEach(x => toast(`${x.file}: ${x.rejected}`, 'err')); if (r.accepted.length) toast(`${r.accepted.length} uploaded.`); fresh('scUps', 'scHealth'); rerender(); } catch (e) { toast(e.message, 'err'); } };
acts['sc-bulk-up'] = async el => { try { await api('POST', '/api/scout/uploads/bulk', { kind: el.dataset.v, collectionId: SC.upCol }); } catch (e) { toast(e.message, 'err'); } };
acts['sc-scope'] = el => { SC.scope = el.dataset.v; fresh('scUps'); rerender(); };
acts['sc-retry'] = async el => { await api('POST', `/api/scout/uploads/${el.dataset.id}/retry`); fresh('scUps'); rerender(); };
acts['sc-del'] = el => confirmBox('Delete?', 'Delete this upload and its file.', 'Yes, delete it', async () => { await api('DELETE', '/api/scout/uploads/' + el.dataset.id); fresh('scUps', 'scHealth'); rerender(); }, true);
acts['sc-insearch'] = el => { SC.q = el.dataset.name; SC.F = {}; SC.page = 1; go('#/app/scout'); scRun('q'); };
const foundLine = (h, long) => !h.found ? '' : h.found.kind === 'both' ? (long ? `Found by both keyword (#${h.found.kw}) and semantic (#${h.found.sem}) search. The résumé uses your terms and describes the same work.` : 'Found by keyword + semantic search.') : h.found.kind === 'semantic' ? (long ? `Found by semantic similarity (#${h.found.sem}). The résumé describes this kind of work even without your exact keywords.` : 'Found by semantic similarity.') : (long ? `Found by keyword match (#${h.found.kw}). The résumé literally mentions your search terms.` : 'Found by keyword match.');
function scSearch(cols, h) {
  const r = SC.res, p = r && r.parsed, sel = r && r.hits.find(x => x.id === SC.sel), c = SC.cand;
  const chips = (k, list) => list.map(s => `<button class="tag ${k === 'must' ? 'on' : ''}" data-act="sc-chip" data-k="${k}" data-v="${esc(s)}">${esc(s)}</button>`).join('');
  const pref = (k, label, v = '') => `<button class="tag" data-act="sc-pref" data-k="${k}" data-v="${esc(v)}" data-tip="Remove">${esc(label)} ${icon('close')}</button>`;
  const read = !r || r.browse ? '' : `<div class="card" style="margin-bottom:16px"><div class="card-head"><h3>How this was read</h3>${info('Click a chip to change it. The search re-runs on your edit. The model does not get a second opinion.')}</div>
    <div class="row wrap" style="gap:6px"><span class="cap">Must have</span>${chips('must', p.must) || '<span class="small muted">none: all candidates considered</span>'}<select class="input" style="width:auto;padding:2px 8px" data-change="sc-add" aria-label="Add a skill"><option value="">+ skill</option>${((h && h.skills) || []).filter(s => !p.must.includes(s) && !p.nice.includes(s)).map(s => `<option>${esc(s)}</option>`).join('')}</select></div>
    ${p.nice.length ? `<div class="row wrap" style="gap:6px;margin-top:8px"><span class="cap">Nice to have</span>${chips('nice', p.nice)}</div>` : ''}
    ${p.minYears || p.location || p.seniority || p.also.length ? `<div class="row wrap" style="gap:6px;margin-top:8px"><span class="cap">Preferences</span>${p.minYears ? pref('minYears', p.minYears + '+ years') : ''}${p.location ? pref('location', p.location) : ''}${p.also.map(a => pref('also', 'also ' + a, a)).join('')}${p.seniority ? pref('seniority', p.seniority) : ''}</div>` : ''}
    <div class="row" style="gap:8px;margin-top:14px"><input class="input grow" id="sc-refine" data-enter="sc-refine" placeholder="Refine in plain English: also Pune · drop AutoCAD · more senior…"><button class="btn ghost" data-act="sc-refine">Refine</button></div>
    <div class="set-row" style="margin-top:10px"><div class="grow"><div class="lbl">Strict requirements ${info('Off by default. A location the résumé never stated, or a skill the extractor missed, would otherwise delete an ideal candidate with nothing on screen telling you it happened.')}</div><div class="small muted">Exclude anyone missing a must-have, the location, or the years${r.hidden ? ` · ${r.hidden} hidden now` : ''}</div></div>${sw(SC.strict, 'sc-strict', 'Strict requirements')}</div>
    <div class="set-row"><div class="grow"><div class="lbl">Every version, not just the latest résumé ${info('By default each person is ranked on their newest résumé only.')}</div></div>${sw(SC.allV, 'sc-allv', 'Every version')}</div></div>`;
  const facet = (k, label) => { const L = r.facets[k] || []; return !L.length ? '' : `<div style="margin-bottom:14px"><div class="cap" style="margin-bottom:6px">${label}</div>${L.map(f => `<button class="check ${(SC.F[k] || []).includes(f.value) ? 'on' : ''}" style="display:flex;width:100%;gap:6px;padding:3px 6px;border-radius:6px;font-size:12.5px;text-align:left" data-act="sc-facet" data-k="${k}" data-v="${esc(f.value)}">${icon((SC.F[k] || []).includes(f.value) ? 'check_box' : 'check_box_outline_blank')}<span class="grow">${esc(f.value)}</span><span class="faint">${f.n}</span></button>`).join('')}</div>`; };
  const row = x => `<div class="set-row hit ${x.id === SC.sel ? 'sel' : ''}" style="align-items:flex-start;gap:10px"><button class="icon-btn sm" data-act="sc-pick" data-key="${esc(x.key)}" aria-label="Select">${icon(SC.picks.includes(x.key) ? 'check_box' : 'check_box_outline_blank')}</button>
    <button class="grow" style="text-align:left;min-width:0" data-act="sc-open" data-id="${x.id}"><div class="row" style="gap:8px"><b>${esc(x.name)}</b>${x.mark === 'shortlisted' ? chip('Shortlisted', 'ok', false) : x.mark === 'rejected' ? chip('Rejected', 'err', false) : ''}${x.fit != null ? `<span class="mono" style="margin-left:auto" data-tip="Rank within your results (top ≈ 100%), weighted by requirement coverage. Not an absolute score.">${x.fit}%</span>` : ''}</div>
      <div class="small muted">${esc(x.title)}${x.years ? ` · ${x.years} yrs` : ''}${x.location ? ' · ' + esc(x.location) : ''}</div>
      ${x.has.length || x.missing.length ? `<div class="row wrap" style="gap:4px;margin-top:6px">${x.has.map(s => `<span class="tag on">${esc(s)}</span>`).join('')}${x.missing.map(s => `<span class="tag" style="text-decoration:line-through">${esc(s)}</span>`).join('')}</div>` : ''}${x.found ? `<div class="small faint" style="margin-top:4px">${foundLine(x)}</div>` : ''}</button>
    <button class="icon-btn sm" data-act="sc-star" data-key="${esc(x.key)}" ${x.mark === 'shortlisted' ? 'data-on="1"' : ''} data-tip="${x.mark === 'shortlisted' ? 'Remove from shortlist' : 'Add to shortlist'}" aria-label="Shortlist">${icon(x.mark === 'shortlisted' ? 'star' : 'star_border')}</button><button class="icon-btn sm" data-act="sc-reject" data-key="${esc(x.key)}" ${x.mark === 'rejected' ? 'data-on="1"' : ''} data-tip="${x.mark === 'rejected' ? 'Undo rejection' : 'Not a fit'}" aria-label="Not a fit">${icon(x.mark === 'rejected' ? 'undo' : 'thumb_down_off_alt')}</button></div>`;
  let pane = `<div class="empty">${icon('person')}Select a candidate to see their profile.</div>`;
  if (sel) {
    const need = p.must.length, met = sel.has.length, ev = c ? c.text.split('\n').filter(l => [...sel.has, ...sel.nice].some(s => l.toLowerCase().includes(s))).slice(0, 6) : [];
    const why = sel.found ? `<div class="card-head" style="margin-top:14px"><h3>Why this match</h3></div><div class="seg" style="margin-bottom:10px">${['summary', 'requirements', 'evidence'].map(t => `<button class="${SC.why === t ? 'on' : ''}" data-act="sc-why" data-v="${t}">${t[0].toUpperCase() + t.slice(1)}</button>`).join('')}</div>
      ${SC.why === 'summary' ? `<p><b>${!need ? 'Ranked by overall similarity' : met === need ? `Meets every requirement (${need})` : `Meets ${met} of ${need} requirements`}</b></p><p class="small muted" style="margin-top:6px">${foundLine(sel, true)}</p><p class="small faint" style="margin-top:6px">The ${sel.fit}% is this candidate's rank within your results (the top match ≈ 100%), weighted by requirement coverage. Not an absolute score.</p>`
      : SC.why === 'requirements' ? `<div class="stack" style="gap:6px">${!need ? '<p class="small muted">No must-haves in this profile, so nothing to check against.</p>' : ''}${p.must.map(s => `<div class="row small">${icon(sel.has.includes(s) ? 'check' : 'close')}<span>${esc(s)}</span></div>`).join('')}${need && met === need ? '<p class="small muted">Nothing missing from your requirements.</p>' : ''}${sel.nice.length ? `<p class="small muted">Also brings nice-to-have: ${esc(sel.nice.join(', '))}.</p>` : ''}${p.minYears ? `<div class="row small">${icon(sel.yearsOk ? 'check' : 'close')}<span>${sel.years} years stated, ${p.minYears} asked</span></div>` : ''}${p.location ? `<div class="row small">${icon(sel.locOk ? 'check' : 'close')}<span>${esc(sel.location || 'Location not stated')}, ${esc([p.location, ...p.also].join(' or '))} asked</span></div>` : ''}</div>`
      : ev.length ? ev.map(l => `<p class="small" style="margin-bottom:6px">${esc(l)}</p>`).join('') : '<p class="small muted">No line in the résumé names these skills directly.</p>'}` : '';
    pane = `<div class="card"><div class="row"><div class="grow"><h3>${esc(sel.name)}</h3><div class="small muted">${esc(sel.title)}${sel.years ? ` · ${sel.years} yrs` : ''}${sel.location ? ' · ' + esc(sel.location) : ''}</div></div></div>${why}
      ${!c ? loading : `<div class="cap" style="margin:16px 0 4px">Summary</div><p class="small">${esc(c.profile.summary)}</p><div class="cap" style="margin:14px 0 6px">Skills</div><div class="row wrap" style="gap:4px">${c.profile.skills.map(s => `<span class="tag">${esc(s)}</span>`).join('')}</div>
        <div class="cap" style="margin:14px 0 4px">Experience</div>${c.profile.experience.map(e => `<p class="small">${esc(e)}</p>`).join('')}<div class="cap" style="margin:14px 0 4px">Education</div>${c.profile.education.map(e => `<p class="small">${esc(e)}</p>`).join('')}
        <p class="small faint" style="margin-top:12px">${esc(c.collection)}${c.versions > 1 ? ` · ${c.versions} versions on file` : ''}</p><button class="btn ghost" style="margin-top:10px" data-act="sc-full">${icon('description')}Open full résumé</button>`}</div>`;
  }
  return `<div class="card" style="margin-bottom:16px"><div class="row wrap" style="gap:8px;margin-bottom:8px"><select class="input" style="width:auto" data-change="sc-col" aria-label="Search within a collection, or all résumés"><option value="">All résumés</option>${(cols || []).map(x => `<option value="${x.id}" ${SC.col === x.id ? 'selected' : ''}>${esc(x.name)}</option>`).join('')}</select></div>
      <textarea class="input" id="sc-q" rows="2" data-on="sc-q" data-enter="sc-find" placeholder="solar project manager, Bangalore, 6+ years…">${esc(SC.q)}</textarea>
      <div class="row" style="margin-top:8px"><span class="small faint grow">A few words (solar PM pune 8 years) or a whole job description. Leave empty to browse everyone. Shift + Enter for a new line</span><button class="btn" data-act="sc-find" ${SC.busy ? 'disabled' : ''}>${SC.busy ? 'Searching…' : r ? 'Search again' : 'Find candidates'}</button></div></div>
    ${read}${!r ? '' : `<div class="sc-grid"><div>${r.total ? `<div class="cap" style="margin-bottom:10px">Filters ${info('Ticking two skills finds people who have both.')}</div>${facet('skills', 'Skills')}${facet('seniority', 'Seniority')}${facet('location', 'Location')}${facet('domain', 'Domain')}${facet('employer', 'Employer')}` : ''}</div>
      <div><div class="row" style="margin-bottom:8px"><b>${r.total}</b><span class="muted small">&nbsp;candidates · ${r.browse ? 'newest first' : 'ranked by fit'}</span><span class="grow"></span>${r.total ? `<button class="btn ghost" data-act="sc-pick-page">This page</button><button class="btn ghost" data-act="sc-bulk" data-v="keys">Shortlist selected${SC.picks.length ? ' (' + SC.picks.length + ')' : ''}</button><button class="btn ghost" data-act="sc-bulk" data-v="all" data-tip="${r.browse ? 'Every candidate matching these filters' : 'Every ranked match for this search'}">All matches</button>` : ''}</div>
        ${r.mode === 'keyword' ? `<div class="banner" style="margin-bottom:10px">${icon('warning')}Keyword-only results. The embedding service is unavailable, so this search ran without semantic matching.</div>` : ''}
        ${!r.total ? `<div class="empty">${icon('search_off')}<b>${r.browse ? 'No résumés match these filters' : 'No candidates matched'}</b><br>${r.blocker && !r.blocker.count ? `No candidate has "${esc(r.blocker.skill)}". This is what's shrinking your results. Drop it to widen them.<br><button class="btn" style="margin-top:10px" data-act="sc-drop" data-v="${esc(r.blocker.skill)}">Drop '${esc(r.blocker.skill)}' and search again</button>` : r.browse ? 'Try clearing a filter.' : 'Drop a must-have, loosen a filter, or turn off strict requirements.'}</div>` : `<div class="card" style="padding:4px 14px">${r.hits.map(row).join('')}</div>
        ${r.pages > 1 ? `<div class="row" style="margin-top:10px;gap:8px;justify-content:center"><button class="btn ghost" data-act="sc-page" data-v="${r.page - 1}" ${r.page < 2 ? 'disabled' : ''}>Prev</button><span class="small muted">Page ${r.page} of ${r.pages}</span><button class="btn ghost" data-act="sc-page" data-v="${r.page + 1}" ${r.page >= r.pages ? 'disabled' : ''}>Next</button></div>` : ''}`}</div>
      <div>${pane}</div></div>`}`;
}
function scShortlist(cols) {
  const L = get('scList', SC.role, '/api/scout/shortlist?role=' + encodeURIComponent(SC.role)); if (!L) return loading;
  const tr = (x, rej) => `<tr><td><b>${esc(x.name)}</b><div class="small muted">${esc(x.title)}</div></td><td>${x.years ? x.years + ' yrs' : ''}${x.location ? ' · ' + esc(x.location) : ''}</td><td class="small">${esc(x.email)}<br>${esc(x.phone)}</td><td>${esc(x.role)}${rej ? `<div class="small muted">${esc(x.reason)}</div>` : ''}</td><td class="act"><button class="icon-btn sm" data-act="sc-unlist" data-key="${esc(x.key)}" data-tip="${rej ? 'Undo rejection' : 'Remove from the shortlist'}" aria-label="Remove">${icon(rej ? 'undo' : 'close')}</button></td></tr>`;
  return `<div class="row wrap" style="gap:8px;margin-bottom:14px"><select class="input" style="width:auto" data-change="sc-role" aria-label="Role"><option value="all">All roles</option><option value="" ${SC.role === '' ? 'selected' : ''}>General</option>${(cols || []).map(c => `<option value="${c.id}" ${SC.role === c.id ? 'selected' : ''}>${esc(c.name)}</option>`).join('')}</select><span class="grow"></span><button class="btn ghost" data-act="sc-export" data-v="csv">${icon('download')}Export CSV</button><button class="btn ghost" data-act="sc-export" data-v="zip">${icon('folder_zip')}Export résumés (ZIP)</button><button class="btn ghost" data-act="sc-clear">Clear this list</button></div>
    ${!L.shortlisted.length ? `<div class="empty">${icon('star_border')}<b>Nothing shortlisted yet</b><br>Star a candidate from the Search tab and they'll collect here.</div>` : `<div class="card"><table class="list"><tr><th>Candidate</th><th>Experience</th><th>Contact</th><th>Role</th><th></th></tr>${L.shortlisted.map(x => tr(x)).join('')}</table></div>`}
    ${L.rejected.length ? `<div class="card" style="margin-top:16px"><div class="card-head"><h3>Rejected <span class="mono">${L.rejected.length}</span></h3>${info('Rejection reasons are kept deliberately: they are the only labelled data this system gets for free, and every future ranking improvement needs them.')}<span class="grow"></span><button class="btn ghost" data-act="sc-rej-toggle">${SC.showRej ? 'Hide' : 'Show'}</button></div>${SC.showRej ? `<table class="list"><tr><th>Candidate</th><th>Experience</th><th>Contact</th><th>Role and reason</th><th></th></tr>${L.rejected.map(x => tr(x, true)).join('')}</table>` : ''}</div>` : ''}`;
}
function scUploads(cols) {
  const U = get('scUps', SC.scope, '/api/scout/uploads?scope=' + SC.scope);
  if (U && U.some(x => !['Searchable', 'Failed'].includes(x.stage))) setTimeout(() => { if (on('#/app/scout/uploads')) { fresh('scUps', 'scHealth'); rerender(); } }, 1300);
  const st = { Searchable: 'ok', Failed: 'err' };
  return `<div class="card" style="margin-bottom:16px"><div class="row wrap" style="gap:8px"><select class="input" style="width:auto" data-change="sc-upcol" aria-label="Collection"><option value="">Choose a collection…</option>${(cols || []).map(c => `<option value="${c.id}" ${SC.upCol === c.id ? 'selected' : ''}>${esc(c.name)}</option>`).join('')}</select><button class="btn ghost" data-act="sc-newcol">${icon('add')}New collection</button><span class="grow"></span><span class="small muted">Bulk:</span><button class="btn ghost" data-act="sc-bulk-up" data-v="zip">Upload a .zip</button><button class="btn ghost" data-act="sc-bulk-up" data-v="sheet" data-tip="An .xlsx or .csv of Google Drive links. The server fetches each file">Upload a link sheet</button></div>
      <button class="empty" style="width:100%;margin-top:12px" data-act="sc-upload">${icon('upload_file')}Drop résumés here, or browse<br><span class="small faint">25 MB each · PDF, Word or text</span></button></div>
    <div class="row" style="margin-bottom:10px"><div class="seg"><button class="${SC.scope === 'mine' ? 'on' : ''}" data-act="sc-scope" data-v="mine">Mine</button><button class="${SC.scope === 'all' ? 'on' : ''}" data-act="sc-scope" data-v="all">Everyone</button></div></div>
    ${!U ? loading : !U.length ? `<div class="empty">${icon('inbox')}Nothing uploaded yet.</div>` : `<div class="card"><table class="list"><tr><th>File</th><th>Stage</th><th>Size</th><th>Uploaded</th><th>Actions</th></tr>${U.map(x => `<tr><td><b>${esc(x.file)}</b><div class="small muted">${esc(x.collection)}${SC.scope === 'all' ? ' · ' + esc(x.by) : ''}</div></td><td>${chip(x.stage, st[x.stage] || 'warn')}${x.attempts > 1 ? `<div class="small faint">Processing attempts so far: ${x.attempts}</div>` : ''}</td><td>${size(x.size)}</td><td class="small muted">${ago(x.at)}</td><td class="act">${x.stage === 'Searchable' ? `<button class="icon-btn sm" data-act="sc-insearch" data-name="${esc(x.file.replace(/\.\w+$/, '').replace(/_/g, ' '))}" data-tip="Open in search" aria-label="Open in search">${icon('search')}</button>` : ''}<button class="icon-btn sm" data-act="sc-retry" data-id="${x.id}" data-tip="Process it again" aria-label="Process it again">${icon('refresh')}</button><button class="icon-btn sm" data-act="sc-del" data-id="${x.id}" data-tip="Delete this upload and its file" aria-label="Delete">${icon('delete')}</button></td></tr>`).join('')}</table></div>`}`;
}
export function scoutPage(tab = '') {
  if (!SCTABS.some(t => t[0] === tab)) tab = '';
  const h = get('scHealth', 'h', '/api/scout/health'), cols = get('scCols', 'c', '/api/scout/collections');
  const body = SOON[tab] ? `<div class="empty">${icon('construction')}<b>${SOON[tab][0]}</b><br>${SOON[tab][1]}<br><span class="chip warn" style="margin-top:10px">Coming soon</span><br><span class="small faint">Not yet ported to Angular. The API behind it is live and unchanged.</span></div>` : tab === 'shortlist' ? scShortlist(cols) : tab === 'uploads' ? scUploads(cols) : scSearch(cols, h);
  const subs = { '': 'Ranked matches from the indexed backlog', shortlist: 'Candidates you have kept, and the ones you passed on', uploads: 'Résumés you have added, and what the pipeline has done with them' };
  return appShell('scout', 'Scout', `<div class="page-head"><div class="grow"><h1>Scout</h1><p class="sub">Applicant backlog${h ? ` · ${h.indexed} résumés indexed` : ''}${subs[tab] ? ' · ' + subs[tab] : ''}</p></div></div>
    ${h && h.stub ? `<div class="banner" style="margin-bottom:14px">${icon('science')}<span><b>Stub backends active.</b> Extraction and/or embeddings are heuristic placeholders, not model output.</span></div>` : ''}${tabs('#/app/scout', SCTABS, tab)}${body}`);
}

// =====================================================================================================================
// Vanik MeasureBook
// =====================================================================================================================
const MB = { mode: 'single', files: [], disc: 'auto', room: '', dim: '', vl: false, tool: '', pts: [], hide: false, group: false, side: true, view: '2d', sel: '', zoom: 100, scaleOn: false, scalePts: [], edit: false, model: null, btab: 'all', busy: false };
const CONF = { High: 'var(--vnk-ok)', Medium: 'var(--vnk-warn)', Low: 'var(--vnk-err)' }, LAYER = { 2: 'Text Extraction', 3: 'Vector Analysis', 4: 'VL Detection', 5: 'Parametric Rules' };
const DISCS = [['auto', 'Auto-detect (recommended)'], ['hvac', 'HVAC'], ['plumbing', 'Plumbing'], ['electrical', 'Electrical'], ['fire_protection', 'Fire Protection'], ['structural', 'Structural'], ['civil', 'Civil / Architectural'], ['pid', 'P&ID']];
const mbReset = () => Object.assign(MB, { tool: '', pts: [], hide: false, sel: '', zoom: 100, scaleOn: false, scalePts: [], edit: false, view: '2d' });
acts['mb-mode'] = el => { MB.mode = el.dataset.v; MB.files = []; rerender(); };
acts['mb-pick'] = async () => { const fs = [...await pickAny(MB.mode === 'batch', '.pdf')].map(f => ({ name: f.name, size: f.size })); if (!fs.length) return; const bad = fs.filter(f => !/\.pdf$/i.test(f.name)); if (bad.length && MB.mode === 'single') return toast('PDF only. Multi-page supported.', 'err'); MB.files = MB.mode === 'batch' ? [...MB.files, ...fs] : fs.slice(0, 1); rerender(); };
acts['mb-clear'] = () => { MB.files = []; rerender(); };
ins['mb-opt'] = el => { MB[el.dataset.k] = el.type === 'checkbox' ? el.checked : el.value; };
acts['mb-start'] = async () => { if (!MB.files.length) return toast(MB.mode === 'batch' ? 'Drop at least one PDF drawing.' : 'Drop a PDF drawing first.', 'err'); MB.busy = true; rerender(); const o = { discipline: MB.disc, scaleRoom: MB.room, scaleDim: MB.dim, vlVerify: MB.vl }; try { if (MB.mode === 'batch') { const r = await api('POST', '/api/measurebook/analyze-batch', { ...o, files: MB.files }); MB.files = []; go('#/app/measurebook/batch/' + r.batch_job_id); } else { const r = await api('POST', '/api/measurebook/analyze', { ...o, file: MB.files[0] }); MB.files = []; mbReset(); go('#/app/measurebook/job/' + r.job_id); } } catch (e) { toast(e.message, 'err'); } MB.busy = false; rerender(); };
acts['mb-tool'] = el => { menu(el, [['count', 'Point count'], ['line', 'Line length (RMT)'], ['area', 'Area (SQMT)'], ['', 'Off']].map(t => ({ label: t[1], run: () => { MB.tool = t[0]; MB.pts = []; MB.scaleOn = false; rerender(); } }))); };
acts['mb-scale'] = () => { MB.scaleOn = !MB.scaleOn; MB.scalePts = []; MB.tool = ''; rerender(); };
acts['mb-apply-scale'] = async () => { const mm = +($('#mb-mm') || {}).value; if (MB.scalePts.length < 2 || !(mm > 0)) return toast('Need two clicked points and a distance value', 'err'); const j = await put('mbJob', 'PUT', `/api/measurebook/jobs/${P.mbJob.id}/scale`, { sheet: 1, a: MB.scalePts[0], b: MB.scalePts[1], mm }); if (j) { MB.scaleOn = false; MB.scalePts = []; rerender(); } };
acts['mb-click'] = (el, e) => { if (!MB.tool && !MB.scaleOn) return; const svg = el.closest('svg'), r = svg.getBoundingClientRect(), pt = [Math.round((e.clientX - r.left) * 800 / r.width), Math.round((e.clientY - r.top) * 520 / r.height)]; if (MB.scaleOn) MB.scalePts = [...MB.scalePts, pt].slice(-2); else MB.pts = [...MB.pts, pt]; rerender(); };
acts['mb-undo'] = () => { MB.pts = []; rerender(); };
acts['mb-flag'] = el => { MB[el.dataset.k] = !MB[el.dataset.k]; rerender(); };
acts['mb-view'] = el => { MB.view = el.dataset.v; rerender(); };
acts['mb-zoom'] = el => { MB.zoom = Math.max(50, Math.min(200, MB.zoom + +el.dataset.v)); rerender(); };
acts['mb-row'] = el => { MB.sel = MB.sel === el.dataset.tag ? '' : el.dataset.tag; rerender(); };
ins['mb-qty'] = el => put('mbJob', 'PUT', `/api/measurebook/jobs/${P.mbJob.id}/items/${encodeURIComponent(el.dataset.tag)}`, { sheet: 1, qty: el.value });
acts['mb-export'] = async () => { const r = await api('GET', `/api/measurebook/jobs/${P.mbJob.id}/download`); downloadText(r.name, r.text); };
acts['mb-bexport'] = async () => { const r = await api('GET', `/api/measurebook/batch/${P.mbBatch.id}/download`); downloadText(r.name, r.text); };
acts['mb-btab'] = el => { MB.btab = el.dataset.v; rerender(); };
acts['mb-model'] = async el => { const f = (await pickAny(false, '.ifc,.glb,.gltf,.obj'))[0]; if (!f) return; const ext = (f.name.split('.').pop() || '').toLowerCase(); if (!['ifc', 'glb', 'gltf', 'obj'].includes(ext)) return toast(`Unsupported file format: .${ext}. Supported: .ifc, .glb, .gltf, .obj`, 'err'); MB.model = { name: f.name, size: f.size, format: ext.toUpperCase() }; rerender(); };
const dist = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]);
function mbDrawing(s) {
  const dim = t => MB.sel && MB.sel !== t ? 0.15 : 1, items = MB.hide ? [] : s.items;
  const find = items.map(it => { const c = CONF[it.conf], o = dim(it.tag), hot = MB.sel === it.tag; return (it.polys || []).map(p => `<polygon points="${p.map(q => q.join(',')).join(' ')}" fill="${c}" fill-opacity="${hot ? 0.35 : 0.12}" stroke="${c}" stroke-width="${hot ? 3 : 1.5}" opacity="${o}"/>`).join('') + (it.paths || []).map(p => `<polyline points="${p.map(q => q.join(',')).join(' ')}" fill="none" stroke="${c}" stroke-width="${hot ? 7 : 4}" stroke-linecap="round" stroke-linejoin="round" opacity="${o * 0.8}"/>`).join('') + (it.pts || []).map(q => `<g opacity="${o}"><circle cx="${q[0]}" cy="${q[1]}" r="${hot ? 11 : 8}" fill="${c}" fill-opacity=".25" stroke="${c}" stroke-width="2"/><text x="${q[0]}" y="${q[1] - 12}" text-anchor="middle" font-size="9" fill="${c}">${esc(it.tag)}</text></g>`).join(''); }).join('');
  const base = s.line ? `<polyline points="${s.line.map(q => q.join(',')).join(' ')}" fill="none" stroke="currentColor" stroke-width="2.5"/><polyline points="230,220 230,290" fill="none" stroke="currentColor" stroke-width="2"/><text x="90" y="330" font-size="11" fill="currentColor">100-CW-101-A1A</text>` : s.rooms.map(r => `<rect x="${r[1]}" y="${r[2]}" width="${r[3]}" height="${r[4]}" fill="none" stroke="currentColor" stroke-width="2"/><text x="${r[1] + r[3] / 2}" y="${r[2] + r[4] / 2 - 4}" text-anchor="middle" font-size="11" fill="currentColor" opacity=".7">${r[0]}</text><text x="${r[1] + r[3] / 2}" y="${r[2] + r[4] / 2 + 10}" text-anchor="middle" font-size="9" fill="currentColor" opacity=".45">${r[5]}</text>`).join('');
  const mark = (pts, closed) => pts.length ? `<${closed && pts.length > 2 ? 'polygon' : 'polyline'} points="${pts.map(q => q.join(',')).join(' ')}" fill="${closed ? 'var(--vnk-accent)' : 'none'}" fill-opacity=".15" stroke="var(--vnk-accent)" stroke-width="2" stroke-dasharray="6 4"/>${pts.map((q, i) => `<circle cx="${q[0]}" cy="${q[1]}" r="5" fill="var(--vnk-accent)"/><text x="${q[0] + 8}" y="${q[1] - 6}" font-size="10" fill="var(--vnk-accent)">${i + 1}</text>`).join('')}` : '';
  return `<svg viewBox="0 0 800 520" style="width:${MB.zoom}%;cursor:${MB.tool || MB.scaleOn ? 'crosshair' : 'default'}" data-act="mb-click" role="img" aria-label="Drawing sheet"><rect x="0" y="0" width="800" height="520" fill="var(--vnk-surface)"/><g style="color:var(--vnk-ink-2)">${base}<rect x="600" y="490" width="190" height="24" fill="none" stroke="currentColor"/><text x="606" y="506" font-size="9" fill="currentColor">${esc(s.title.slice(0, 34))}</text></g>${find}${mark(MB.scalePts)}${mark(MB.pts, MB.tool === 'area')}</svg>`;
}
function mbJob(id) {
  const j = get('mbJob', id, '/api/measurebook/jobs/' + id);
  if (!j || j.status !== 'done') { if (j) setTimeout(() => { if (on('#/app/measurebook/job/' + id)) { fresh('mbJob'); rerender(); } }, 700); return appShell('measurebook', 'MeasureBook', `<div class="empty" style="margin-top:60px">${icon('auto_awesome')}<b>AI is reading your drawing</b><br>${esc(j ? j.step : 'Uploading file...')}<br><span class="small faint">${esc(j ? j.filename : '')}</span></div>`); }
  const s = j.sheets[0], k = s.mmPerPx, m = MB.pts, meas = MB.tool === 'count' ? `${m.length} point${m.length === 1 ? '' : 's'}` : MB.tool === 'line' ? (k ? (m.slice(1).reduce((a, q, i) => a + dist(m[i], q), 0) * k / 1000).toFixed(2) + ' RMT' : 'Scale not set') : MB.tool === 'area' ? (k ? (Math.abs(m.reduce((a, q, i) => a + q[0] * m[(i + 1) % m.length][1] - m[(i + 1) % m.length][0] * q[1], 0)) / 2 * k * k / 1e6).toFixed(2) + ' SQMT' : 'Scale not set') : '';
  const rows = MB.group ? [...s.items].sort((a, b) => a.layer - b.layer) : s.items; let last = 0;
  const table = `<div class="card" style="padding:0;overflow:auto"><div class="card-head" style="padding:14px 16px 0"><h3>Extracted Data</h3><span class="small muted">Click a row to locate on drawing</span></div><table class="list"><tr><th>S.No</th><th>Tag</th><th>Description</th><th>Qty</th><th>Unit</th><th>Spec</th><th>Conf.</th></tr>${!rows.length ? '<tr><td colspan="7" class="muted" style="text-align:center">No data for this sheet</td></tr>' : rows.map(it => `${MB.group && it.layer !== last ? `<tr><td colspan="7" class="cap">Layer ${last = it.layer} · ${LAYER[it.layer]}</td></tr>` : ''}<tr class="${MB.sel === it.tag ? 'sel' : ''}" style="cursor:pointer" data-act="mb-row" data-tag="${esc(it.tag)}"><td class="mono">${it.sno}</td><td><b>${esc(it.tag)}</b></td><td>${esc(it.desc)}${it.edited ? ' <span class="small faint">edited</span>' : ''}</td><td>${MB.edit ? `<input class="input" style="width:80px;padding:3px 6px" value="${it.qty ?? ''}" data-change="mb-qty" data-tag="${esc(it.tag)}" aria-label="Quantity">` : it.qty == null ? '<span class="faint">set scale</span>' : `<b>${it.qty}</b>`}</td><td>${it.unit}</td><td class="small muted">${esc(it.spec)}</td><td><span class="chip" style="color:${CONF[it.conf]}">${it.conf}</span></td></tr>`).join('')}</table></div>`;
  const three = `<div class="card"><div class="row wrap" style="gap:6px;margin-bottom:12px">${['Load IFC', 'Load GLB', 'Load OBJ'].map(b => `<button class="btn ghost" data-act="mb-model">${b}</button>`).join('')}<span class="grow"></span><button class="btn ghost" disabled>Reset</button><button class="btn ghost" disabled>Grid</button><button class="btn ghost" disabled>Axes</button><button class="btn ghost" disabled>Wire</button></div>
    <div class="empty" style="min-height:300px;display:grid;place-content:center">${icon('view_in_ar')}${MB.model ? `<b>${esc(MB.model.format)} · ${esc(MB.model.name)}</b><br><span class="small muted">Triangles: 0 · Meshes: 0 · Size: ${size(MB.model.size)}</span>` : `<b>3D Model View</b><br>Load an IFC, GLB, or OBJ file to view in 3D<br><span class="small faint">.ifc · .glb / .gltf · .obj</span>`}</div></div>`;
  const tb = (act, ic, label, on2, extra = '') => `<button class="btn ghost ${on2 ? 'on' : ''}" data-act="${act}" ${extra}>${icon(ic)}${label}</button>`;
  return appShell('measurebook', `<a href="#/app/measurebook">MeasureBook</a> / ${esc(j.filename)}`, `<div class="page-head"><div class="grow"><h1>${esc(j.filename)}</h1><p class="sub">Drawing workspace · ${j.sheets.length} open sheet${j.sheets.length === 1 ? '' : 's'}</p></div>${chip('AI reading done', 'ok')}${chip('Saved', '', false)}<a class="btn ghost" href="#/app/measurebook">${icon('add')}New</a><button class="btn" data-act="mb-export">${icon('download')}Export</button></div>
    <div class="row wrap" style="gap:6px;margin-bottom:10px">${tb('mb-tool', 'straighten', 'Measure' + (MB.tool ? ': ' + { count: 'Point count', line: 'Line length', area: 'Area' }[MB.tool] : ''), !!MB.tool)}${tb('mb-flag', 'draw', 'Markup', false, 'data-k="markup" disabled')}${tb('mb-flag', 'edit', 'Edit', MB.edit, 'data-k="edit"')}${tb('mb-scale', 'square_foot', 'Set scale', MB.scaleOn)}${tb('mb-flag', MB.hide ? 'visibility' : 'visibility_off', MB.hide ? 'Show all findings' : 'Hide all findings', MB.hide, 'data-k="hide"')}<span class="grow"></span>${tb('mb-flag', 'vertical_split', 'Side by side', MB.side, 'data-k="side"')}${tb('mb-flag', 'segment', MB.group ? 'Grouped view' : 'Ungrouped view', MB.group, 'data-k="group"')}<div class="seg"><button class="${MB.view === '2d' ? 'on' : ''}" data-act="mb-view" data-v="2d">2D</button><button class="${MB.view === '3d' ? 'on' : ''}" data-act="mb-view" data-v="3d">3D</button></div></div>
    <div class="row wrap" style="gap:8px;margin-bottom:12px"><span class="tag on">Sheet 1</span><span class="tag">${esc(j.disciplineName)}</span><span class="tag">${k ? `${k} mm per px · ${esc(s.scaleFrom)}` : 'Scale not set'}</span>${meas ? `<span class="chip ok">${meas}</span><button class="btn ghost" data-act="mb-undo">Clear</button>` : ''}<span class="grow"></span><span class="small muted">1 / 1</span><button class="icon-btn sm" data-act="mb-zoom" data-v="-25" aria-label="Zoom out">${icon('remove')}</button><span class="small mono">${MB.zoom}%</span><button class="icon-btn sm" data-act="mb-zoom" data-v="25" aria-label="Zoom in">${icon('add')}</button></div>
    ${MB.scaleOn ? `<div class="card" style="margin-bottom:12px"><div class="card-head"><h3>Calibrate Drawing Scale</h3></div><p class="small muted">Click two points on the drawing, then enter the real-world distance between them.</p><div class="row wrap" style="gap:8px;margin-top:10px"><span class="small">${MB.scalePts.length < 2 ? 'Click two points on the drawing to set scale...' : 'Two points selected. Enter distance (mm) and click Apply Scale.'}</span><span class="grow"></span><input class="input" id="mb-mm" style="width:150px" type="number" placeholder="Distance (mm)"><button class="btn" data-act="mb-apply-scale">Apply Scale</button></div></div>` : ''}
    <div class="${MB.side ? 'mb-ws' : 'stack'}" style="gap:16px">${MB.view === '3d' ? three : `<div class="card mb-draw" style="padding:10px;overflow:auto">${mbDrawing(s)}</div>`}${table}</div>`);
}
function mbBatch(id) {
  const b = get('mbBatch', id, '/api/measurebook/batch/' + id);
  if (!b || b.status !== 'done') { if (b) setTimeout(() => { if (on('#/app/measurebook/batch/' + id)) { fresh('mbBatch'); rerender(); } }, 600); return appShell('measurebook', 'MeasureBook', `<div class="empty" style="margin-top:60px">${icon('auto_awesome')}<b>Processing tender set</b><br>${b ? `${b.done} / ${b.total}` : 'Starting...'}<div class="sbar" style="margin:12px auto"><i style="width:${b ? Math.round(100 * b.done / b.total) : 0}%"></i></div><span class="small faint">${esc(b ? b.current : '')}</span></div>`); }
  const st = b.stats, rows = b.boq.filter(r => MB.btab === 'all' || r.discipline === MB.btab);
  return appShell('measurebook', `<a href="#/app/measurebook">MeasureBook</a> / Tender set`, `<div class="page-head"><div class="grow"><h1>Tender Set Takeoff</h1><p class="sub">${st.files} files · ${st.pages} pages · ${st.disciplines} disciplines</p></div><a class="btn ghost" href="#/app/measurebook">${icon('add')}New</a><button class="btn" data-act="mb-bexport">${icon('download')}Export Unified BOQ</button></div>
    <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;margin-bottom:16px">${[['Files', st.files], ['Pages', st.pages], ['Disciplines', st.disciplines], ['Component Types', st.types], ['Total Items', st.items]].map(x => `<div class="card stat"><span class="small muted">${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>
    <div class="card" style="margin-bottom:16px"><div class="card-head"><h3>By Discipline</h3></div><div class="row wrap" style="gap:6px">${b.byDiscipline.map(d => `<span class="tag">${esc(d.name)} <b>${d.n}</b></span>`).join('')}</div>
      <div class="card-head" style="margin-top:16px"><h3>Drawings in Set</h3></div><div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px">${b.files.map(f => f.error ? `<div class="card" style="text-align:center;border-color:var(--vnk-err)"><span class="chip err">Error</span><div class="small muted" style="margin-top:8px;overflow-wrap:anywhere">${esc(f.name)}</div></div>` : `<a class="card" style="text-align:center" href="#/app/measurebook/job/${f.jobId}">${icon('picture_as_pdf')}<div class="small" style="margin-top:6px;overflow-wrap:anywhere">${esc(f.name)}</div><div class="small faint">${esc((DISCS.find(d => d[0] === f.discipline) || ['', ''])[1])}</div></a>`).join('')}</div></div>
    <div class="card" style="padding:0;overflow:auto"><div class="card-head" style="padding:14px 16px 0"><h3>Unified BOQ (All Trades)</h3></div><div class="row wrap" style="gap:6px;padding:10px 16px"><button class="tag ${MB.btab === 'all' ? 'on' : ''}" data-act="mb-btab" data-v="all">All</button>${b.byDiscipline.map(d => `<button class="tag ${MB.btab === d.id ? 'on' : ''}" data-act="mb-btab" data-v="${d.id}">${esc(d.name)}</button>`).join('')}</div>
      <table class="list"><tr><th>S.No</th><th>Tag</th><th>Description</th><th>Qty</th><th>Unit</th><th>Sources</th></tr>${rows.map(r => `<tr><td class="mono">${r.sno}</td><td><b>${esc(r.tag)}</b></td><td>${esc(r.desc)}</td><td><b>${r.qty}</b></td><td>${r.unit}</td><td class="small muted">${esc(r.sources.slice(0, 2).join(', '))}${r.sources.length > 2 ? ` +${r.sources.length - 2} more` : ''}</td></tr>`).join('')}</table></div>`);
}
export function mbPage(sub, id) {
  if (sub === 'job' && id) return mbJob(id);
  if (sub === 'batch' && id) return mbBatch(id);
  const L = [['LAYER 2', 'Text Extraction', 'Tags & annotations', 'High confidence'], ['LAYER 3', 'Vector Analysis', 'CAD color layers', 'Medium confidence'], ['LAYER 4', 'VL Detection', 'Unlabeled symbols', 'Low confidence'], ['LAYER 5', 'Parametric Rules', 'Standard sizes', 'Inference']], batch = MB.mode === 'batch';
  return appShell('measurebook', 'MeasureBook', `<div style="max-width:860px;margin:0 auto"><div style="text-align:center;margin:10px 0 22px"><div class="cap">MEASUREBOOK</div><h1 style="margin-top:6px">Drop in the drawing set.</h1><p class="muted" style="margin-top:8px">Any discipline: HVAC, plumbing, electrical, structural, P&amp;ID, fire protection. The engine reads it the way your best estimator would.</p>
      <div class="seg" style="margin-top:16px"><button class="${!batch ? 'on' : ''}" data-act="mb-mode" data-v="single">Single Drawing</button><button class="${batch ? 'on' : ''}" data-act="mb-mode" data-v="batch">Tender Set (Batch)</button></div></div>
    <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px;margin-bottom:16px">${L.map(x => `<div class="card"><div class="cap">${x[0]}</div><b>${x[1]}</b><div class="small muted">${x[2]}</div><div class="small faint" style="margin-top:6px">${x[3]}</div></div>`).join('')}</div>
    <button class="empty" style="width:100%" data-act="mb-pick">${icon('upload_file')}<b>${batch ? 'Drop multiple PDF drawings here' : 'Drop PDF drawing here'}</b><br><span class="small faint">${batch ? 'Upload an entire tender set: Vol 1-8, all disciplines' : 'or click to browse · PDF only · Multi-page supported'}</span></button>
    ${MB.files.length ? `<div class="card" style="margin-top:12px"><div class="row"><b>${MB.files.length} file${MB.files.length === 1 ? '' : 's'} selected</b><span class="grow"></span><button class="btn ghost" data-act="mb-clear">Clear all</button></div>${MB.files.map(f => `<div class="set-row">${icon('picture_as_pdf')}<div class="grow lbl">${esc(f.name)}</div><span class="small faint">${size(f.size)}</span></div>`).join('')}</div>` : ''}
    <div class="card" style="margin-top:16px"><div class="card-head"><h3>Analysis Options</h3></div><div class="row wrap" style="gap:12px"><label class="field grow"><span>Discipline</span><select class="input" data-change="mb-opt" data-k="disc">${DISCS.map(d => `<option value="${d[0]}" ${MB.disc === d[0] ? 'selected' : ''}>${d[1]}</option>`).join('')}</select></label><label class="field grow"><span>Scale Reference Room (optional)</span><input class="input" data-on="mb-opt" data-k="room" value="${esc(MB.room)}"></label><label class="field grow"><span>Scale Reference Dimension (optional)</span><input class="input" data-on="mb-opt" data-k="dim" value="${esc(MB.dim)}"></label></div>
      <label class="row" style="gap:8px;margin-top:12px"><input type="checkbox" data-change="mb-opt" data-k="vl" ${MB.vl ? 'checked' : ''}><span>Enable VL model verification (slower, detects unlabeled symbols)</span></label>
      <button class="btn" style="margin-top:16px;width:100%" data-act="mb-start" ${MB.busy ? 'disabled' : ''}>${batch ? 'Process Tender Set' : 'Start Takeoff'}</button></div></div>`);
}

// =====================================================================================================================
// Vanik mBot
// =====================================================================================================================
const BT = { filter: 'mine', scope: '', q: '', transcript: false, focus: false, from: '', to: '', chat: [], tq: '', tsp: '' };
const BTTABS = [['', 'Home'], ['meetings', 'Meetings'], ['chat', 'Chat'], ['settings', 'Settings']];
const dueChip = a => a.status === 'done' ? chip('Done', 'ok', false) : !a.due ? chip('No date', '', false) : a.overdue ? chip(Math.max(1, Math.round((Date.now() - new Date(a.due).getTime()) / 864e5)) + 'd overdue', 'err', false) : a.due === new Date().toISOString().slice(0, 10) ? chip('Due today', 'warn', false) : chip(day(a.due), '', false);
const btFresh = () => fresh('btHome', 'btTasks', 'btMeet', 'btList');
acts['bt-filter'] = el => { BT.filter = el.dataset.v; fresh('btTasks'); rerender(); };
acts['bt-done'] = async el => { try { await api('PUT', '/api/mbot/tasks/' + el.dataset.id, { status: el.dataset.on ? 'open' : 'done' }); toast(el.dataset.on ? 'Marked as open' : 'Marked as done'); btFresh(); rerender(); } catch (e) { toast(e.message, 'err'); } };
acts['bt-act'] = el => { const a = JSON.parse(el.dataset.a); menuD(el, [{ label: a.due ? 'Change due date' : 'Set due date', icon: 'event', disabled: !a.canEdit, run: () => modal({ title: 'Due date', body: `<input class="input" type="date" id="bt-due" value="${a.due}">`, actions: [{ label: 'Set', run: async o => { await api('PUT', '/api/mbot/tasks/' + a.id, { due: $('#bt-due', o).value }); btFresh(); rerender(); } }] }) }, { label: 'Reassign', icon: 'swap_horiz', disabled: !a.canEdit, run: async () => { const m = await api('GET', '/api/mbot/meetings/' + a.meetingId); modal({ title: 'Reassign to', body: `<select class="input" id="bt-owner">${m.people.map(p => `<option value="${esc(p.email)}" ${p.name === a.owner ? 'selected' : ''}>${esc(p.name)}${p.name === a.owner ? ' · current' : ''}</option>`).join('')}</select>`, actions: [{ label: 'Reassign', run: async o => { const r = await api('PUT', '/api/mbot/tasks/' + a.id, { owner: $('#bt-owner', o).value }); toast(r.mine ? 'Reassigned to you. It is now in My actions.' : `Reassigned to ${r.owner}. They will see it in their actions.`); btFresh(); rerender(); } }] }); } }, { label: a.due ? 'Ask for update' : 'Ask for date', icon: 'notifications_active', disabled: !a.canNudge, run: async () => { try { const r = await api('POST', `/api/mbot/tasks/${a.id}/nudge`); toast(r.text); btFresh(); rerender(); } catch (e) { toast(e.message, 'err'); } } }]); };
const actRow = a => `<div class="set-row" style="align-items:flex-start;gap:10px"><button class="icon-btn sm" data-act="bt-done" data-id="${a.id}" ${a.status === 'done' ? 'data-on="1"' : ''} data-tip="${a.status === 'done' ? 'Undo' : 'Mark done'}" aria-label="Mark done">${icon(a.status === 'done' ? 'check_circle' : 'radio_button_unchecked')}</button><div class="grow" style="min-width:0"><div style="${a.status === 'done' ? 'text-decoration:line-through;opacity:.6' : ''}">${esc(a.task)}</div><div class="small muted"><a href="#/app/mbot/meetings/${a.meetingId}">${esc(a.meeting)}</a> · ${a.mine ? 'You' : esc(a.owner)}${!a.matched ? ` <span class="faint" data-tip="This owner wasn't matched to a meeting participant, so mbot can't email them">· Owner not matched</span>` : ''}${a.from ? ` · Reassigned from ${esc(a.from)}` : ''}${a.nudgedAt ? ' · Nudged' : ''}</div></div>${dueChip(a)}<button class="icon-btn sm" data-act="bt-act" data-a="${esc(JSON.stringify({ id: a.id, due: a.due, owner: a.owner, meetingId: a.meetingId, canEdit: a.canEdit, canNudge: a.canNudge }))}" aria-label="More">${icon('more_vert')}</button></div>`;
function btHome() {
  const h = get('btHome', 'h', '/api/mbot/home'), T = get('btTasks', BT.filter, '/api/mbot/tasks?filter=' + BT.filter); if (!h) return loading;
  const hr = new Date().getHours(), c = h.counts, bits = [c.overdue && `${c.overdue} overdue`, c.week && `${c.week} due this week`, c.waiting && `${c.waiting} waiting on others`].filter(Boolean);
  const cards = [['overdue', 'Overdue', c.overdue, 'Assigned to you'], ['week', 'Due this week', c.week, 'Including today'], ['waiting', 'Waiting on others', c.waiting, 'From your meetings'], ['missing', 'Missing details', c.missing, 'No due date or owner']];
  return `<h1>${hr < 12 ? 'Good morning' : hr < 17 ? 'Good afternoon' : 'Good evening'}, ${esc(h.name)}</h1><p class="sub" style="margin:6px 0 18px">${bits.length ? 'You have ' + bits.join(' · ') + '.' : 'You are all caught up.'}</p>
    <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin-bottom:18px">${cards.map(x => `<button class="card stat ${BT.filter === x[0] ? 'next' : ''}" style="text-align:left" data-act="bt-filter" data-v="${x[0]}"><span class="small muted">${x[1]}</span><b>${x[2]}</b><span class="small faint">${x[3]}</span></button>`).join('')}<a class="card stat" href="#/app/mbot/meetings"><span class="small muted">Focus meetings</span><b>${c.focus}</b><span class="small faint">With important contacts</span></a></div>
    <div class="card"><div class="card-head"><h3>My actions</h3><span class="grow"></span><div class="seg">${[['mine', 'Assigned to me'], ['all', 'All'], ['done', 'Completed']].map(f => `<button class="${BT.filter === f[0] ? 'on' : ''}" data-act="bt-filter" data-v="${f[0]}">${f[1]}</button>`).join('')}</div></div>${!T ? loading : T.length ? T.map(actRow).join('') : `<p class="muted">${BT.filter === 'mine' ? 'No open actions' : 'Nothing here. Clear the filter to see all actions.'}</p>`}</div>
    <div class="card" style="margin-top:16px"><div class="card-head"><h3>Meetings</h3><span class="grow"></span><a class="btn ghost" href="#/app/mbot/meetings">All meetings</a></div>${h.meetings.map(m => `<a class="set-row" href="#/app/mbot/meetings/${m.id}"><div class="grow"><div class="lbl">${m.focus ? icon('flag') : ''}${esc(m.title)}</div><div class="small muted">${day(m.at)} · ${m.mins} min · Host: ${esc(m.organizer)}</div></div><span class="small faint">${m.open} open${m.done ? `, ${m.done} done` : ''}</span></a>`).join('') || '<p class="muted">No meetings found.</p>'}</div>`;
}
ins['bt-q'] = el => { BT[el.dataset.k] = el.value; };
acts['bt-apply'] = () => { ['q', 'from', 'to'].forEach(k => { const el = $('#bt-' + k); if (el) BT[k] = el.value; }); fresh('btList'); rerender(); };
acts['bt-scope'] = el => { BT.scope = el.dataset.v; fresh('btList'); rerender(); };
acts['bt-tog'] = el => { BT[el.dataset.k] = !BT[el.dataset.k]; fresh('btList'); rerender(); };
acts['bt-clear'] = () => { Object.assign(BT, { scope: '', q: '', transcript: false, focus: false, from: '', to: '' }); fresh('btList'); rerender(); };
function btMeetings() {
  const qs = new URLSearchParams({ scope: BT.scope, q: BT.q, transcript: BT.transcript ? '1' : '', focus: BT.focus ? '1' : '', from: BT.from, to: BT.to }).toString(), L = get('btList', qs, '/api/mbot/meetings?' + qs);
  const stat = { Completed: 'ok', Processing: 'warn', Pending: '', Removed: 'err' };
  return `<div class="card" style="margin-bottom:14px"><div class="row wrap" style="gap:8px"><div class="seg">${[['', 'All Meetings'], ['organized', 'Organized by Me'], ['participated', 'Participated']].map(s => `<button class="${BT.scope === s[0] ? 'on' : ''}" data-act="bt-scope" data-v="${s[0]}">${s[1]}</button>`).join('')}</div><input class="input grow" id="bt-q" data-enter="bt-apply" value="${esc(BT.q)}" placeholder="Search by title, email, summary or action item..." style="min-width:200px"></div>
      <div class="row wrap" style="gap:8px;margin-top:10px"><input class="input" id="bt-from" type="date" value="${BT.from}" style="width:auto" aria-label="From"><input class="input" id="bt-to" type="date" value="${BT.to}" style="width:auto" aria-label="To"><button class="tag ${BT.transcript ? 'on' : ''}" data-act="bt-tog" data-k="transcript">With transcript</button><button class="tag ${BT.focus ? 'on' : ''}" data-act="bt-tog" data-k="focus">Focus only</button><span class="grow"></span><button class="btn ghost" data-act="bt-clear">Clear All</button><button class="btn" data-act="bt-apply">Apply</button></div></div>
    ${!L ? loading : !L.length ? `<div class="empty">${icon('event_busy')}No meetings found.</div>` : `<div class="card" style="padding:0;overflow:auto"><table class="list"><tr><th>Title</th><th>Organizer Email</th><th>Important Participants</th><th>Meeting Time (in IST)</th><th>Participants</th><th>Status</th><th>Transcript</th></tr>${L.map(m => `<tr><td><a href="#/app/mbot/meetings/${m.id}"><b>${m.focus ? `<span data-tip="This meeting includes a focus contact marked by the CEO office">${icon('flag')}</span>` : ''}${esc(m.title)}</b></a></td><td class="small">${esc(m.organizerEmail)}</td><td class="small">${esc(m.important.join(', '))}</td><td class="small">${new Date(m.at).toLocaleString('en-IN', { weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Kolkata' })}</td><td>${m.participants}</td><td>${chip(m.status, stat[m.status] || '')}</td><td class="act">${m.hasTranscript ? `<a class="btn ghost" href="#/app/mbot/meetings/${m.id}">View</a>` : ''}</td></tr>`).join('')}</table></div>`}`;
}
acts['bt-note'] = async el => { const t = $('#bt-note').value.trim(); if (!t) return; try { await api('POST', `/api/mbot/meetings/${el.dataset.id}/notes`, { text: t }); toast('Note added'); fresh('btMeet'); rerender(); } catch (e) { toast(e.message, 'err'); } };
acts['bt-more'] = el => { const m = P.btMeet; menuD(el, [{ label: 'Forward', icon: 'forward_to_inbox', run: () => modal({ title: 'Forward summary', text: `Sends the "${m.title}" summary email to people who weren't in the meeting.`, body: `<input class="input" id="bt-fwd" placeholder="name@${esc(m.domain)}">`, actions: [{ label: 'Send', run: async o => { await api('POST', `/api/mbot/meetings/${m.id}/forward-summary`, { email: $('#bt-fwd', o).value }); toast('Summary sent.'); } }] }) },
  { label: 'Add someone who should have been here', icon: 'person_add', run: () => modal({ title: 'Add a participant', text: `For someone who should have been on the call. They'll be added to "${m.title}" and can then be assigned actions.`, body: `<div class="stack" style="gap:10px"><input class="input" id="bt-pn" placeholder="e.g. Rohit Mehra"><input class="input" id="bt-pe" placeholder="Work email"></div>`, actions: [{ label: 'Add participant', run: async o => { const n = $('#bt-pn', o).value; await api('POST', `/api/mbot/meetings/${m.id}/participants`, { name: n, email: $('#bt-pe', o).value }); toast(`${n} added. You can now assign actions to them.`); fresh('btMeet'); rerender(); } }] }) },
  { label: 'Who can edit actions', icon: 'lock_person', disabled: !m.host, run: () => modal({ title: 'Who can edit actions?', text: "You're the host, so you can always reassign or edit any action.", body: `<div class="stack" style="gap:8px">${[['host', 'Only me', 'Participants can view actions but not change them.'], ['owners', 'Action owners', 'Owners can update the date and status of their own actions.'], ['all', 'All participants', 'Anyone in the meeting can edit any action.']].map(x => `<label class="row" style="gap:10px;align-items:flex-start"><input type="radio" name="bt-er" value="${x[0]}" ${m.editRights === x[0] ? 'checked' : ''}><span><b>${x[1]}</b><br><span class="small muted">${x[2]}</span></span></label>`).join('')}</div>`, actions: [{ label: 'Save', run: async o => { await api('PUT', '/api/mbot/meetings/' + m.id, { editRights: o.querySelector('input[name=bt-er]:checked').value }); toast('Editing rights updated'); fresh('btMeet'); rerender(); } }] }) },
  { label: m.status === 'Summary turned off' ? 'Turn summary back on' : 'Turn off summary', icon: 'visibility_off', disabled: !m.host, run: () => confirmBox(m.status === 'Summary turned off' ? 'Turn summary back on?' : 'Turn off summary?', `mbot won't record a transcript or generate a summary and actions for "${m.title}".`, m.status === 'Summary turned off' ? 'Turn on' : 'Turn off summary', async () => { await api('PUT', '/api/mbot/meetings/' + m.id, { summaryOff: m.status !== 'Summary turned off' }); toast('Summary turned off for this meeting'); btFresh(); rerender(); }) },
  { label: 'Remove summary', icon: 'delete', danger: true, disabled: !m.host, run: () => confirmBox('Remove summary?', `This permanently deletes the summary, transcript and actions for "${m.title}". It can't be undone.`, 'Remove summary', async () => { await api('DELETE', `/api/mbot/meetings/${m.id}/summary`); toast('Summary, transcript and actions removed'); btFresh(); rerender(); }, true) }]); };
ins['bt-tq'] = el => { BT[el.dataset.k] = el.value; const box = $('#bt-lines'); if (box) box.innerHTML = btLines(P.btMeet); };
const btLines = m => { const L = m.transcript.filter(l => (!BT.tsp || l.who === BT.tsp) && (!BT.tq || l.text.toLowerCase().includes(BT.tq.toLowerCase()))); return L.length ? L.map(l => `<div class="set-row" style="align-items:flex-start;gap:10px"><span class="avatar" style="flex:none">${esc(l.who.split(' ').map(w => w[0]).join('').slice(0, 2))}</span><div class="grow"><div class="small"><b>${esc(l.who)}</b> <span class="faint mono">${l.t}</span></div><div>${esc(l.text)}</div></div></div>`).join('') : `<p class="muted">No lines match “${esc(BT.tq)}”</p>`; };
acts['bt-transcript'] = () => { const m = P.btMeet; BT.tq = ''; BT.tsp = ''; modal({ title: 'Meeting Transcript', wide: true, cancel: 'Close', body: `<div class="row wrap" style="gap:8px;margin-bottom:10px"><input class="input grow" data-on="bt-tq" data-k="tq" placeholder="Search the transcript"><select class="input" style="width:auto" data-change="bt-tq" data-k="tsp"><option value="">All Speakers</option>${[...new Set(m.transcript.map(l => l.who))].map(w => `<option>${esc(w)}</option>`).join('')}</select></div><div id="bt-lines" style="max-height:52vh;overflow:auto">${btLines(m)}</div>` }); };
function btMeeting(id) {
  const m = get('btMeet', id, '/api/mbot/meetings/' + id); if (!m) return loading;
  const sec = (t, list) => `<div class="card"><div class="card-head"><h3>${t}</h3></div>${list}</div>`, s = m.summary;
  return `<a class="back" href="#/app/mbot/meetings">${icon('arrow_back')}All meetings</a><div class="page-head"><div class="grow"><h1>${m.focus ? icon('flag') : ''}${esc(m.title)}</h1><p class="sub">${day(m.at)} · ${m.mins} min · Host: ${esc(m.organizer)} · ${m.participants} participants${m.focus ? ' · Includes a focus contact marked by the CEO office' : ''}</p></div>${m.hasTranscript ? `<button class="btn ghost" data-act="bt-transcript">${icon('notes')}Meeting Transcript</button>` : ''}<button class="icon-btn" data-act="bt-more" aria-label="More">${icon('more_vert')}</button></div>
    <div class="stack" style="gap:16px;max-width:900px">${!s ? `<div class="empty">${icon('visibility_off')}${m.status === 'Removed' ? 'Summary, transcript and actions removed' : 'Summary turned off'}</div>` : `${sec('Outcome', s.overall ? `<p>${esc(s.overall)}</p>` : "<p class=\"muted\">The summary isn't ready yet. It appears here once mbot has processed the recording.</p>")}
      ${sec('Key discussion points', s.points.length ? s.points.map(p => `<div class="row small" style="margin-bottom:6px;align-items:flex-start">${icon('chevron_right')}<span>${esc(p)}</span></div>`).join('') : '<p class="muted">No key points captured.</p>')}
      ${sec('Key Decisions', s.decisions.length ? s.decisions.map(p => `<div class="row small" style="margin-bottom:6px;align-items:flex-start">${icon('gavel')}<span>${esc(p)}</span></div>`).join('') : '<p class="muted">No decisions captured.</p>')}
      ${sec(`Actions · ${m.open} open${m.done ? `, ${m.done} done` : ''}`, m.actions.length ? m.actions.map(actRow).join('') : '<p class="muted">No actions captured.</p>')}`}
      ${sec(`Your notes ${info('Only you can see these')}`, `${m.notes.map(n => `<div class="set-row"><div class="grow" style="white-space:pre-wrap">${esc(n.text)}</div><span class="small faint">${ago(n.at)}</span></div>`).join('')}<textarea class="input" id="bt-note" rows="2" style="margin-top:8px" placeholder="Add context mbot missed, decisions made off-call, or things to raise next time."></textarea><button class="btn ghost" style="margin-top:8px" data-act="bt-note" data-id="${m.id}">${m.notes.length ? 'Add another note' : 'Add note'}</button>`)}
      ${sec('Participants', m.people.map(p => `<div class="set-row"><span class="avatar">${esc(p.name.split(' ').map(w => w[0]).join('').slice(0, 2))}</span><div class="grow"><div class="lbl">${esc(p.name)}</div><div class="small muted">${esc(p.email)}</div></div>${p.host ? chip('Host', '', false) : ''}${p.focus ? chip('Focus contact', 'warn', false) : ''}${p.added ? chip('Added by you', '', false) : ''}</div>`).join(''))}</div>`;
}
acts['bt-ask'] = async () => { const el = $('#bt-chat'), q = el.value.trim(); if (!q) return; BT.chat.push({ q, a: null }); rerender(); try { BT.chat[BT.chat.length - 1].a = await api('POST', '/api/mbot/chat', { q }); } catch (e) { BT.chat[BT.chat.length - 1].a = { answer: e.message, sources: [] }; } rerender(); };
acts['bt-inc'] = async () => { const s = P.btSet; await api('PUT', '/api/mbot/settings', { includeTranscript: !s.includeTranscript }); fresh('btSet'); rerender(); };
acts['bt-focus-add'] = () => modal({ title: 'Add a focus contact', text: 'Meetings that include this person will be flagged as visible to the CEO office.', body: `<div class="stack" style="gap:10px"><input class="input" id="bf-n" placeholder="Name, e.g. Priya Nair"><input class="input" id="bf-e" placeholder="Email, name@company.com"><input class="input" id="bf-d" placeholder="Designation (optional), e.g. VP Operations"><input class="input" id="bf-c" placeholder="Company (optional), e.g. Partner Co"></div>`, actions: [{ label: 'Add contact', run: async o => { const n = $('#bf-n', o).value; await api('POST', '/api/mbot/focus', { name: n, email: $('#bf-e', o).value, designation: $('#bf-d', o).value, company: $('#bf-c', o).value }); toast(`${n} added to your focus contacts`); fresh('btSet', 'btList', 'btHome'); rerender(); } }] });
acts['bt-focus-del'] = el => confirmBox('Remove focus contact?', `${el.dataset.name} (${el.dataset.email}) will no longer be a focus contact. Meetings with them stop being flagged for the CEO office.`, 'Remove', async () => { await api('DELETE', '/api/mbot/focus/' + el.dataset.id); toast(`${el.dataset.name} removed from your focus contacts`); fresh('btSet', 'btList', 'btHome'); rerender(); }, true);
export function mbotPage(tab = '', id) {
  if (!BTTABS.some(t => t[0] === tab)) tab = '';
  let body;
  if (tab === 'meetings') body = id ? btMeeting(id) : btMeetings();
  else if (tab === 'chat') body = `<div class="card" style="max-width:820px">${BT.chat.length ? BT.chat.map(c => `<div style="margin-bottom:16px"><p><b>${esc(c.q)}</b></p>${!c.a ? loading : `<p style="margin-top:6px">${esc(c.a.answer)}</p>${c.a.sources.map(s => `<a class="tag" style="margin:6px 6px 0 0" href="#/app/mbot/meetings/${s.meetingId}">${esc(s.meeting)} · ${esc(s.who)} ${s.t}</a>`).join('')}`}</div>`).join('') : '<p class="muted">Ask a question across your past meetings. Answers come from their transcripts.</p>'}<div class="row" style="gap:8px;margin-top:10px"><input class="input grow" id="bt-chat" data-enter="bt-ask" placeholder="Search meetings, actions, people…"><button class="btn" data-act="bt-ask">Ask</button></div></div>`;
  else if (tab === 'settings') { const s = get('btSet', 's', '/api/mbot/settings'); body = !s ? loading : `<div class="stack" style="gap:16px;max-width:760px"><div class="card"><div class="set-row"><div class="grow"><div class="lbl">Include Transcript</div><div class="small muted">Turn the meeting transcript on or off</div></div>${sw(s.includeTranscript, 'bt-inc', 'Include Transcript')}</div></div>
      <div class="card"><div class="card-head"><h3>Focus contacts</h3>${info('Meetings with these people are flagged as visible to the CEO office.')}<span class="grow"></span><button class="btn ghost" data-act="bt-focus-add">${icon('add')}Add contact</button></div><p class="small muted">People whose meetings you want highlighted. Add or remove the contacts you've set up.</p>${s.focus.length ? s.focus.map(f => `<div class="set-row"><div class="grow"><div class="lbl">${esc(f.name)}</div><div class="small muted">${esc(f.email)}${f.designation ? ' · ' + esc(f.designation) : ''}${f.company ? ' · ' + esc(f.company) : ''}</div></div><button class="btn ghost" data-act="bt-focus-del" data-id="${f.id}" data-name="${esc(f.name)}" data-email="${esc(f.email)}">Remove</button></div>`).join('') : "<p class=\"muted\" style=\"margin-top:10px\">You haven't added any focus contacts yet.</p>"}</div></div>`; }
  else body = btHome();
  return appShell('mbot', 'mBot', `${tab === 'meetings' && id ? '' : tabs('#/app/mbot', BTTABS, tab)}${body}`);
}

// =====================================================================================================================
// Vanik Echo
// =====================================================================================================================
acts['ec-start'] = async () => { try { const m = await api('POST', '/api/echo/meetings', { title: ($('#ec-title') || { value: '' }).value }); fresh('ecList'); go('#/app/echo/' + m.id); } catch (e) { toast(e.message, 'err'); } };
acts['ec-end'] = async el => { await put('ecMeet', 'POST', `/api/echo/meetings/${el.dataset.id}/end`); fresh('ecList'); toast('Transcript saved on the appliance.'); };
acts['ec-dl'] = () => { const m = P.ecMeet; downloadText(m.title.replace(/[^\wऀ-ॿ ]+/g, '').trim() + '.txt', m.lines.map(l => `[${l.t}] ${l.speaker}: ${l.text}`).join('\n')); };
acts['ec-del'] = el => confirmBox('Delete this transcript?', 'It is removed from the appliance.', 'Delete', async () => { await api('DELETE', '/api/echo/meetings/' + el.dataset.id); fresh('ecList'); go('#/app/echo'); }, true);
let ecTimer = 0;
export function echoPage(id) {
  if (id) {
    const m = get('ecMeet', id, '/api/echo/meetings/' + id); if (!m) return appShell('echo', 'Echo', loading);
    if (m.live && m.more && !ecTimer) ecTimer = setTimeout(async () => { ecTimer = 0; if (!on('#/app/echo/' + id)) return; try { P.ecMeet = await api('POST', `/api/echo/meetings/${id}/utterance`); rerender(); const sc = $('#scroll'); if (sc) sc.scrollTop = sc.scrollHeight; } catch (e) { /* ended elsewhere */ } }, 2400);
    return appShell('echo', `<a href="#/app/echo">Echo</a> / ${esc(m.title)}`, `<a class="back" href="#/app/echo">${icon('arrow_back')}Meetings</a><div class="page-head"><div class="grow"><h1>${esc(m.title)}</h1><p class="sub">${day(m.startedAt)} · ${m.count} utterances · ${m.speakers} speakers · ${m.language}</p></div>${m.live ? `${chip(m.more ? 'Listening' : 'Waiting for speech', 'ok')}<button class="btn" data-act="ec-end" data-id="${m.id}">${icon('stop_circle')}End meeting</button>` : `<button class="btn ghost" data-act="ec-dl">${icon('download')}Download</button><button class="icon-btn" data-act="ec-del" data-id="${m.id}" aria-label="Delete">${icon('delete')}</button>`}</div>
      <div class="card" style="max-width:860px">${m.lines.length ? m.lines.map(l => `<div class="set-row" style="align-items:flex-start;gap:12px"><span class="tag ${['on', '', 'on bad'][(+l.speaker.split(' ')[1] - 1) % 3] || ''}" style="flex:none">${esc(l.speaker)}</span><div class="grow" lang="hi" style="font-size:15px;line-height:1.7">${esc(l.text)}</div><span class="small faint mono">${l.t}</span></div>`).join('') : '<p class="muted">Start talking. Each utterance appears after a pause, labelled with who said it.</p>'}</div>`);
  }
  const L = get('ecList', 'l', '/api/echo'), live = L && L.meetings.find(m => m.live);
  return appShell('echo', 'Echo', `<div class="page-head"><div class="grow"><h1>Echo</h1><p class="sub">Live meeting transcription with speaker labels, on your own Vanik Appliance.</p></div></div>
    <div class="card" style="max-width:760px;margin-bottom:16px">${live ? `<div class="row"><div class="grow"><b>${esc(live.title)}</b><div class="small muted">A meeting is running</div></div><a class="btn" href="#/app/echo/${live.id}">Open</a></div>` : `<div class="row wrap" style="gap:8px"><input class="input grow" id="ec-title" data-enter="ec-start" placeholder="Meeting title (optional)"><button class="btn" data-act="ec-start">${icon('mic')}Start a meeting</button></div><p class="small faint" style="margin-top:10px">Hindi only for now. Audio is segmented on pauses and transcribed utterance by utterance. Transcripts are saved on the device when the meeting ends.</p>`}</div>
    ${!L ? loading : !L.meetings.filter(m => !m.live).length ? `<div class="empty" style="max-width:760px">${icon('graphic_eq')}No transcripts yet.</div>` : `<div class="card" style="max-width:760px"><div class="card-head"><h3>Saved transcripts</h3></div>${L.meetings.filter(m => !m.live).map(m => `<a class="set-row" href="#/app/echo/${m.id}"><div class="grow"><div class="lbl" lang="hi">${esc(m.title)}</div><div class="small muted">${day(m.startedAt)} · ${m.count} utterances · ${m.speakers} speakers</div></div>${icon('chevron_right')}</a>`).join('')}</div>`}`);
}
