// Vanik Sense at its MVP: what each meeting decided and who owes what. Actions sit beside the minutes and are fixed in one
// click; filters look like filters; a meeting belongs to the people who were in it. Server side: sense.js.
import { S, $, esc, icon, info, chip, go, ago, api, rerender, acts, ins, toast, modal, confirmBox, menu } from './core.js';
import { appShell, get, P } from './suite.js';

const loading = '<p class="muted">Loading…</p>';
const SN = { filter: 'mine', picks: [], scope: '', q: '', transcript: false, focus: false, attention: false, contact: '', ask: [], mask: {}, tq: '', tsp: '' };
const TABS = [['', 'Home'], ['meetings', 'Meetings'], ['ask', 'Ask'], ['settings', 'Settings']];
const day = iso => new Date(iso).toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short' });
const fresh = (...s) => (s.length ? s : ['snHome', 'snTasks', 'snList', 'snMeet', 'snSet']).forEach(k => { P[k + 'Key'] = ''; });
const again = (...s) => { fresh(...s); rerender(); };
const sw = (on, act, label, extra = '') => `<button class="switch ${on ? 'on' : ''}" role="switch" aria-checked="${!!on}" aria-label="${esc(label)}" data-act="${act}" ${extra}></button>`;
const tog = (on, k, label) => `<button class="toggle ${on ? 'on' : ''}" data-act="sn-tog" data-k="${k}" aria-pressed="${!!on}">${label}</button>`;
const initials = n => esc(n.split(' ').map(w => w[0]).join('').slice(0, 2));

// ---------- actions: one row, everything on it
acts['sn-done'] = async el => { await api('PUT', '/api/sense/tasks/' + el.dataset.id, { status: el.dataset.on ? 'open' : 'done' }); again(); };
ins['sn-due'] = async el => { try { await api('PUT', '/api/sense/tasks/' + el.dataset.id, { due: el.value }); toast(el.value ? 'Date changed.' : 'Date removed.'); } catch (e) { toast(e.message, 'err'); } again(); };
acts['sn-owner'] = async el => { const m = await api('GET', '/api/sense/meetings/' + el.dataset.m); menu(el, [{ heading: 'From this meeting' }, ...m.people.map(p => ({ label: p.name, sub: p.email, on: p.name === el.dataset.owner, run: async () => { await api('PUT', '/api/sense/tasks/' + el.dataset.id, { owner: p.email }); toast(`${p.name} owns this now.`); again(); } }))]); };
acts['sn-confirm'] = async el => { await api('POST', `/api/sense/tasks/${el.dataset.id}/confirm`); toast('Owner confirmed.'); again(); };
acts['sn-more'] = el => { const a = JSON.parse(el.dataset.a); menu(el, [a.canNudge && { label: 'Remind the owner', icon: 'notifications_active', run: async () => { const r = await api('POST', `/api/sense/tasks/${a.id}/nudge`); toast(r.text); again(); } }, { label: 'History', icon: 'history', run: () => modal({ title: 'What changed', cancel: 'Close', body: a.trail.length ? a.trail.map(t => `<div class="set-row"><div class="grow">${esc(t.what)}<div class="small muted">${esc(t.by)}</div></div><span class="small faint">${ago(t.at)}</span></div>`).join('') : '<p class="muted">Nothing has changed since the meeting.</p>' }) }, a.canEdit && { label: 'Delete this action', icon: 'delete', danger: true, run: () => confirmBox('Delete this action?', 'Use this when the action is wrong or not needed.', 'Delete', async () => { await api('DELETE', '/api/sense/tasks/' + a.id); again(); }, true) }].filter(Boolean)); };
acts['sn-pick'] = el => { const id = el.dataset.id; SN.picks = SN.picks.includes(id) ? SN.picks.filter(x => x !== id) : [...SN.picks, id]; rerender(); };
acts['sn-bulk'] = async el => { const op = el.dataset.v, run = async due => { const r = await api('POST', '/api/sense/tasks/bulk', { ids: SN.picks, op, due }); toast(`${r.changed} changed${r.skipped ? `, ${r.skipped} skipped` : ''}.`); SN.picks = []; again(); }; if (op === 'clear') { SN.picks = []; return rerender(); } if (op === 'due') return modal({ title: 'Set a date for ' + SN.picks.length, body: '<input class="input" type="date" id="sn-bdue">', actions: [{ label: 'Set', run: o => run($('#sn-bdue', o).value) }] }); if (op === 'delete') return confirmBox(`Delete ${SN.picks.length} actions?`, 'Only the ones you may change are deleted.', 'Delete', () => run(), true); run(); };
const row = (a, where) => {
  const owner = !a.matched ? `${a.owner ? `<span class="tag" data-tip="Not in your company, so they cannot be reminded">${esc(a.owner)}, outside</span>` : '<span class="chip err">No owner</span>'}${a.suggest && a.suggest.userId && a.canEdit ? `<button class="btn ghost" style="height:26px;padding:0 10px" data-act="sn-confirm" data-id="${a.id}">${esc(a.suggest.name.split(' ')[0])}? Confirm</button>` : ''}${a.canEdit ? `<button class="btn text" style="height:26px" data-act="sn-owner" data-id="${a.id}" data-m="${a.meetingId}" data-owner="">Pick</button>` : ''}`
    : a.canEdit ? `<button class="tag" data-act="sn-owner" data-id="${a.id}" data-m="${a.meetingId}" data-owner="${esc(a.owner)}" data-tip="Change the owner">${a.mine ? 'You' : esc(a.owner)} ${icon('expand_more')}</button>` : `<span class="tag">${a.mine ? 'You' : esc(a.owner)}</span>`;
  const due = a.status === 'done' ? chip('Done', 'ok', false) : a.canEdit ? `<input class="input sn-date ${a.overdue ? 'warn' : ''}" type="date" value="${a.due}" data-change="sn-due" data-id="${a.id}" aria-label="Due date">` : chip(a.due ? day(a.due) : 'No date', a.overdue ? 'err' : '', false);
  return `<div class="set-row sn-act">${where !== 'ro' ? `<button class="icon-btn sm" data-act="sn-pick" data-id="${a.id}" aria-label="Select">${icon(SN.picks.includes(a.id) ? 'check_box' : 'check_box_outline_blank')}</button>` : ''}
    <div class="grow" style="min-width:180px"><div style="${a.status === 'done' ? 'text-decoration:line-through;opacity:.55' : ''}">${esc(a.task)}</div>${where === 'home' ? `<a class="small muted" href="#/app/sense/meetings/${a.meetingId}">${esc(a.meeting)}</a>` : ''}${a.overdue ? ' <span class="small" style="color:var(--vnk-err)">overdue</span>' : ''}${a.nudged ? ' <span class="small faint">reminded</span>' : ''}</div>
    <div class="row wrap" style="gap:6px;justify-content:flex-end">${owner}${due}${where !== 'ro' ? `<button class="icon-btn sm" data-act="sn-done" data-id="${a.id}" ${a.status === 'done' ? 'data-on="1"' : ''} data-tip="${a.status === 'done' ? 'Reopen' : 'Mark done'}" aria-label="Mark done">${icon(a.status === 'done' ? 'undo' : 'check_circle')}</button><button class="icon-btn sm" data-act="sn-more" data-a="${esc(JSON.stringify({ id: a.id, trail: a.trail, canEdit: a.canEdit, canNudge: a.canNudge }))}" aria-label="More">${icon('more_vert')}</button>` : ''}</div></div>`;
};
const bulkBar = () => SN.picks.length ? `<div class="banner" style="background:var(--vnk-accent-weak);color:var(--vnk-ink);margin-bottom:10px"><b>${SN.picks.length} selected</b><span class="grow"></span>${[['done', 'Mark done'], ['nudge', 'Remind'], ['due', 'Set date'], ['delete', 'Delete'], ['clear', 'Clear']].map(b => `<button class="btn ${b[0] === 'clear' ? 'text' : 'ghost'}" style="height:28px;margin:0" data-act="sn-bulk" data-v="${b[0]}">${b[1]}</button>`).join('')}</div>` : '';

// ---------- home
acts['sn-filter'] = el => { SN.filter = el.dataset.v; SN.picks = []; again('snTasks'); };
acts['sn-intro'] = async () => { await api('POST', '/api/sense/intro'); again('snHome'); };
function home() {
  const h = get('snHome', 'h', '/api/sense/home'), T = get('snTasks', SN.filter, '/api/sense/tasks?filter=' + SN.filter); if (!h) return loading;
  const hr = new Date().getHours(), c = h.counts, d = h.digest, stat = (k, label, n) => `<button class="card stat ${SN.filter === k ? 'next' : ''}" style="text-align:left" data-act="sn-filter" data-v="${k}"><span class="small muted">${label}</span><b>${n}</b></button>`;
  return `${h.intro ? `<div class="card next" style="margin-bottom:18px"><div class="card-head"><h3>How Vanik Sense works</h3></div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:14px">
      ${[['event', 'Which meetings', 'Every Teams meeting on your calendar, picked up by itself. You do not add it to anything.'], ['visibility', 'What it sees', 'The meeting\'s transcript and the links and files shared in its chat. Nothing else.'], ['lock', 'Who can read it', 'Only the people who were in the meeting. Not admins. You can forward a read-only summary.']].map(x => `<div>${icon(x[0])}<div class="lbl" style="font-weight:600;margin-top:4px">${x[1]}</div><div class="small muted">${x[2]}</div></div>`).join('')}</div><button class="btn" style="margin-top:16px" data-act="sn-intro">Got it</button></div>` : ''}
    <h1>${hr < 12 ? 'Good morning' : hr < 17 ? 'Good afternoon' : 'Good evening'}, ${esc(h.name)}</h1><p class="sub" style="margin:8px 0 18px">${c.overdue || c.week ? `You owe ${c.overdue ? `${c.overdue} overdue` : ''}${c.overdue && c.week ? ' and ' : ''}${c.week ? `${c.week} this week` : ''}.` : 'You are all caught up.'} ${c.meetings} meetings.</p>
    <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin-bottom:16px">${stat('overdue', 'Overdue', c.overdue)}${stat('week', 'Due this week', c.week)}${stat('waiting', 'Waiting on others', c.waiting)}${stat('missing', 'No owner or date', c.missing)}</div>
    <div class="card"><div class="card-head"><h3>Actions</h3><span class="grow"></span><div class="seg">${[['mine', 'Mine'], ['all', 'Everyone\'s'], ['done', 'Done']].map(f => `<button class="${SN.filter === f[0] ? 'on' : ''}" data-act="sn-filter" data-v="${f[0]}">${f[1]}</button>`).join('')}</div></div>${bulkBar()}${!T ? loading : T.length ? T.map(a => row(a, 'home')).join('') : `<p class="muted">Nothing here.</p>`}</div>
    <p class="small muted" style="margin:10px 2px 18px">${d.on ? `${icon('mail')} Your daily email today: ${d.overdue} overdue, ${d.tomorrow} due tomorrow, ${d.week} due this week.` : `${icon('notifications_off')} Your daily email is off.`} <a href="#/app/sense/settings" style="text-decoration:underline">Change</a></p>
    <div class="card"><div class="card-head"><h3>Latest meetings</h3><span class="grow"></span><a class="btn ghost" href="#/app/sense/meetings">All ${c.meetings}</a></div>${h.recent.map(m => `<a class="set-row" href="#/app/sense/meetings/${m.id}"><div class="grow"><div class="lbl">${esc(m.title)}</div><div class="small muted">${day(m.at)} · ${m.mins} min · ${esc(m.organizer)}</div></div>${m.attention ? chip('Needs attention', 'warn') : ''}<span class="small faint">${m.open} open</span></a>`).join('') || '<p class="muted">Your meetings appear here after they end.</p>'}</div>`;
}

// ---------- meetings
acts['sn-tog'] = el => { SN[el.dataset.k] = !SN[el.dataset.k]; again('snList'); };
acts['sn-scope'] = el => { SN.scope = el.dataset.v; again('snList'); };
acts['sn-search'] = () => { SN.q = $('#sn-q').value; again('snList'); };
ins['sn-contact'] = el => { SN.contact = el.value; again('snList'); };
acts['sn-open'] = el => go('#/app/sense/meetings/' + el.dataset.id);
const setOff = async (id, off, scope) => { const r = await api('PUT', '/api/sense/meetings/' + id, { off, scope }); toast(off ? (r.changed > 1 ? `Transcription is off for all ${r.changed} in the series.` : 'This meeting will not be transcribed.') : 'Transcription is on.'); again(); };
acts['sn-off'] = el => { const off = !el.dataset.off; if (off && el.dataset.series) return modal({ title: 'Stop transcribing', text: 'This meeting repeats. Stop for this one, or for the whole series?', actions: [{ label: 'The whole series', run: () => setOff(el.dataset.id, true, 'all') }, { label: 'Only this one', run: () => setOff(el.dataset.id, true, 'one') }] }); setOff(el.dataset.id, off, el.dataset.series && !off ? 'all' : 'one'); };
function meetings() {
  const qs = new URLSearchParams({ scope: SN.scope, q: SN.q, transcript: SN.transcript ? '1' : '', focus: SN.focus ? '1' : '', attention: SN.attention ? '1' : '', contact: SN.contact }).toString(), R = get('snList', qs, '/api/sense/meetings?' + qs), L = R && R.list;
  return `<div class="row wrap" style="gap:8px;margin-bottom:10px"><input class="input grow" id="sn-q" data-enter="sn-search" value="${esc(SN.q)}" placeholder="Search a title, a person or an action" style="min-width:220px"><div class="seg">${[['', 'All'], ['organized', 'I hosted'], ['participated', 'I joined']].map(s => `<button class="${SN.scope === s[0] ? 'on' : ''}" data-act="sn-scope" data-v="${s[0]}">${s[1]}</button>`).join('')}</div></div>
    <div class="row wrap" style="gap:8px;margin-bottom:16px"><span class="cap">Show only</span>${tog(SN.transcript, 'transcript', 'With transcript')}${tog(SN.focus, 'focus', 'Focus contacts')}${tog(SN.attention, 'attention', 'Needs attention')}${R && R.contacts.length ? `<select class="input" style="width:auto;height:30px" data-change="sn-contact" aria-label="One focus contact"><option value="">Any contact</option>${R.contacts.map(c => `<option value="${esc(c.email)}" ${SN.contact === c.email ? 'selected' : ''}>${esc(c.name)}</option>`).join('')}</select>` : ''}</div>
    ${!L ? loading : !L.length ? `<div class="empty">${icon('event_busy')}No meetings match. Turn a filter off.</div>` : `<div class="card" style="padding:0;overflow:auto"><table class="list"><tr><th>Meeting</th><th>When</th><th>Host</th><th>Actions</th><th>Transcribe</th></tr>${L.map(m => `<tr style="cursor:pointer" data-act="sn-open" data-id="${m.id}"><td><b>${esc(m.title)}</b>${m.series ? ` <span class="tag">${esc(m.series)}</span>` : ''}${m.focus.length ? ` <span class="tag on" data-tip="Includes ${esc(m.focus.join(', '))}">Focus</span>` : ''}${m.readOnly ? ' <span class="tag">Forwarded to you</span>' : ''}<div class="small muted">${m.participants} people${m.attention ? ' · needs attention' : ''}</div></td><td class="small">${day(m.at)}<br><span class="faint">${m.mins} min</span></td><td class="small">${m.host ? 'You' : esc(m.organizer)}</td><td>${m.on ? `${m.open} open${m.done ? `, ${m.done} done` : ''}` : chip(m.status, '', false)}</td><td>${m.host && m.status !== 'Removed' ? sw(m.on, 'sn-off', 'Transcribe this meeting', `data-stop data-id="${m.id}" ${m.on ? '' : 'data-off="1"'} ${m.series ? 'data-series="1"' : ''}`) : `<span class="small faint">${m.on ? 'On' : 'Off'}</span>`}</td></tr>`).join('')}</table></div>`}`;
}

// ---------- one meeting: minutes on the left, actions on the right
acts['sn-note'] = async el => { const t = $('#sn-note').value.trim(); if (!t) return; await api('POST', `/api/sense/meetings/${el.dataset.id}/notes`, { text: t }); again('snMeet'); };
acts['sn-forward'] = () => { const m = P.snMeet; modal({ title: 'Forward the summary', text: 'They get every key point and decision by email. The link opens this meeting read-only.', body: `<input class="input" id="sn-fwd" placeholder="name@${esc(m.domain)}">`, actions: [{ label: 'Send', run: async o => { const r = await api('POST', `/api/sense/meetings/${m.id}/forward`, { email: $('#sn-fwd', o).value }); toast(`Sent with ${r.points} points. Opens ${r.opens}.`); } }] }); };
acts['sn-menu'] = el => { const m = P.snMeet, mine = m.people.filter(p => p.userId && !p.host); menu(el, [{ label: 'Add someone who should have been here', icon: 'person_add', run: () => modal({ title: 'Add a participant', text: 'They can then be given actions.', body: '<div class="stack" style="gap:10px"><input class="input" id="sn-pn" placeholder="Name"><input class="input" id="sn-pe" placeholder="Work email"></div>', actions: [{ label: 'Add', run: async o => { await api('POST', `/api/sense/meetings/${m.id}/participants`, { name: $('#sn-pn', o).value, email: $('#sn-pe', o).value }); again('snMeet'); } }] }) },
  m.host && { label: 'Who can change actions', icon: 'edit', run: () => modal({ title: 'Who can change actions?', body: `<div class="stack" style="gap:10px">${[['host', 'Only me'], ['owners', 'Each owner, their own'], ['all', 'Everyone in the meeting']].map(x => `<label class="row" style="gap:10px"><input type="radio" name="sn-er" value="${x[0]}" ${m.editRights === x[0] ? 'checked' : ''}><span>${x[1]}</span></label>`).join('')}</div>`, actions: [{ label: 'Save', run: async o => { await api('PUT', '/api/sense/meetings/' + m.id, { editRights: o.querySelector('input[name=sn-er]:checked').value }); again('snMeet'); } }] }) },
  m.host && { label: 'Who can delete the minutes', icon: 'shield', run: () => modal({ title: 'Who can delete the minutes?', text: 'You always can. Tick anyone else.', body: `<div class="stack" style="gap:10px">${mine.map(p => `<label class="row" style="gap:10px"><input type="checkbox" value="${p.userId}" ${m.deleters.includes(p.userId) ? 'checked' : ''}><span>${esc(p.name)}</span></label>`).join('') || '<p class="muted">Nobody else from your company was in this meeting.</p>'}</div>`, actions: [{ label: 'Save', run: async o => { await api('PUT', '/api/sense/meetings/' + m.id, { deleters: [...o.querySelectorAll('input:checked')].map(i => i.value) }); again('snMeet'); } }] }) },
  m.canDelete && { label: 'Delete the minutes', icon: 'delete', danger: true, run: () => confirmBox('Delete the minutes?', 'The minutes, transcript and actions are removed for everyone. This cannot be undone.', 'Delete', async () => { await api('DELETE', `/api/sense/meetings/${m.id}/summary`); again(); }, true) }].filter(Boolean)); };
ins['sn-tq'] = el => { SN[el.dataset.k] = el.value; const box = $('#sn-lines'); if (box) box.innerHTML = lines(P.snMeet); };
const lines = m => { const L = m.transcript.filter(l => (!SN.tsp || l.who === SN.tsp) && (!SN.tq || l.text.toLowerCase().includes(SN.tq.toLowerCase()))); return L.length ? L.map(l => `<div class="set-row" style="align-items:flex-start"><span class="avatar">${initials(l.who)}</span><div class="grow"><div class="small"><b>${esc(l.who)}</b> <span class="faint mono">${l.t}</span></div><div>${esc(l.text)}</div></div></div>`).join('') : '<p class="muted">No lines match.</p>'; };
acts['sn-transcript'] = () => { const m = P.snMeet; SN.tq = ''; SN.tsp = ''; modal({ title: 'Transcript', wide: true, cancel: 'Close', body: `<div class="row wrap" style="gap:8px;margin-bottom:10px"><input class="input grow" data-on="sn-tq" data-k="tq" placeholder="Search the transcript"><select class="input" style="width:auto" data-change="sn-tq" data-k="tsp"><option value="">Everyone</option>${[...new Set(m.transcript.map(l => l.who))].map(w => `<option>${esc(w)}</option>`).join('')}</select></div><div id="sn-lines" style="max-height:52vh;overflow:auto">${lines(m)}</div>` }); };
acts['sn-mask'] = async el => { const id = el.dataset.id, q = $('#sn-mq').value.trim(); if (!q) return; SN.mask[id] = { q, a: null }; rerender(); try { SN.mask[id].a = await api('POST', '/api/sense/ask', { q, meetingId: id }); } catch (e) { SN.mask[id].a = { answer: e.message, sources: [] }; } rerender(); };
function meeting(id) {
  const m = get('snMeet', id, '/api/sense/meetings/' + id); if (!m) return loading;
  const sec = (t, body, extra = '') => `<div class="card"><div class="card-head"><h3>${t}</h3>${extra}</div>${body}</div>`, s = m.summary, ro = m.readOnly, ans = SN.mask[id];
  const li = (ic, list, none) => list.length ? list.map(p => `<div class="row small" style="margin-bottom:8px;align-items:flex-start">${icon(ic)}<span>${esc(p)}</span></div>`).join('') : `<p class="muted">${none}</p>`;
  return `<a class="back" href="#/app/sense/meetings">${icon('arrow_back')}Meetings</a>${ro ? `<div class="banner" style="margin-bottom:14px">${icon('visibility')}This summary was forwarded to you. You can read it. You cannot change it.</div>` : ''}
    <div class="page-head"><div class="grow"><h1>${esc(m.title)}</h1><p class="sub">${day(m.at)} · ${m.mins} min · Host: ${esc(m.organizer)} · ${m.participants} people${m.series ? ' · ' + esc(m.series) : ''}</p></div>${m.on ? `<button class="btn ghost" data-act="sn-transcript">${icon('notes')}Transcript</button>` : ''}${!ro && m.on ? `<button class="btn" data-act="sn-forward">${icon('forward_to_inbox')}Forward</button>` : ''}${!ro ? `<button class="icon-btn" data-act="sn-menu" aria-label="More">${icon('more_vert')}</button>` : ''}</div>
    ${!s ? `<div class="empty">${icon('visibility_off')}${m.status === 'Removed' ? 'The minutes of this meeting were deleted.' : 'This meeting was not transcribed.'}</div>` : `<div class="sn-two"><div class="stack" style="gap:16px">
      ${sec('Outcome', `<p>${esc(s.overall)}</p>`)}${sec('Key points', li('chevron_right', s.points, 'None picked out.'))}${sec('Decisions', li('gavel', s.decisions, 'None recorded.'))}
      ${m.links.length ? sec('Shared in the chat', m.links.map(l => `<div class="set-row">${icon(l.kind === 'file' ? 'description' : 'link')}<div class="grow"><div class="lbl">${esc(l.title)}</div><div class="small muted">${esc(l.by)} · ${l.t}</div></div></div>`).join('')) : ''}
      ${m.earlier.length ? sec('Earlier in this series', m.earlier.map(e => `<a class="set-row" href="#/app/sense/meetings/${e.id}"><div class="grow lbl">${day(e.at)}</div><span class="small muted">${e.open} still open</span></a>`).join('')) : ''}
      ${sec('Ask about this meeting', `<div class="row" style="gap:8px"><input class="input grow" id="sn-mq" data-enter="sn-mask" data-id="${id}" value="${ans ? esc(ans.q) : ''}" placeholder="What was decided on the invoices?"><button class="btn ghost" data-act="sn-mask" data-id="${id}">Ask</button></div>${ans ? (ans.a ? `<p style="margin-top:12px">${esc(ans.a.answer)}</p>${ans.a.sources.map(x => `<span class="tag" style="margin:8px 6px 0 0">${esc(x.who)} ${x.t}</span>`).join('')}` : loading) : ''}`)}</div>
      <div class="stack" style="gap:16px">${sec(`Actions`, `${ro ? '' : bulkBar()}${m.actions.length ? m.actions.map(a => row(a, ro ? 'ro' : 'meet')).join('') : '<p class="muted">No actions came out of this meeting.</p>'}`, `<span class="small muted">${m.open} open${m.done ? `, ${m.done} done` : ''}</span>`)}
      ${ro ? '' : sec(`Your notes ${info('Only you can see these.')}`, `${m.notes.map(n => `<div class="set-row"><div class="grow" style="white-space:pre-wrap">${esc(n.text)}</div><span class="small faint">${ago(n.at)}</span></div>`).join('')}<textarea class="input" id="sn-note" rows="2" style="margin-top:8px" placeholder="Something decided after the meeting, or to raise next time"></textarea><button class="btn ghost" style="margin-top:8px" data-act="sn-note" data-id="${m.id}">Add note</button>`)}
      ${sec('People', m.people.map(p => `<div class="set-row"><span class="avatar">${initials(p.name)}</span><div class="grow"><div class="lbl">${esc(p.name)}</div><div class="small muted">${esc(p.email)}</div></div>${p.host ? chip('Host', '', false) : ''}${p.focus ? chip('Focus', 'warn', false) : ''}${p.added ? chip('Added later', '', false) : ''}</div>`).join(''))}</div></div>`}`;
}

// ---------- ask, settings
acts['sn-ask'] = async () => { const el = $('#sn-ask'), q = el.value.trim(); if (!q) return; SN.ask.push({ q, a: null }); rerender(); try { SN.ask[SN.ask.length - 1].a = await api('POST', '/api/sense/ask', { q }); } catch (e) { SN.ask[SN.ask.length - 1].a = { answer: e.message, sources: [] }; } rerender(); };
acts['sn-notif'] = async () => { await api('PUT', '/api/sense/settings', { notifications: !P.snSet.notifications }); again('snSet', 'snHome'); };
acts['sn-focus-add'] = () => modal({ title: 'Add a focus contact', text: 'Meetings with this person are marked for you, and you can filter by them. Only you see your list.', body: '<div class="stack" style="gap:10px"><input class="input" id="sf-n" placeholder="Name"><input class="input" id="sf-e" placeholder="Email"></div>', actions: [{ label: 'Add', run: async o => { await api('POST', '/api/sense/focus', { name: $('#sf-n', o).value, email: $('#sf-e', o).value }); again(); } }] });
acts['sn-focus-del'] = async el => { await api('DELETE', '/api/sense/focus/' + el.dataset.id); again(); };
export function sensePage(tab = '', id) {
  if (!TABS.some(t => t[0] === tab)) tab = '';
  let body;
  if (tab === 'meetings') body = id ? meeting(id) : meetings();
  else if (tab === 'ask') body = `<div class="card" style="max-width:820px">${SN.ask.length ? SN.ask.map(c => `<div style="margin-bottom:18px"><p><b>${esc(c.q)}</b></p>${!c.a ? loading : `<p style="margin-top:6px">${esc(c.a.answer)}</p>${c.a.sources.map(s => `<a class="tag" style="margin:8px 6px 0 0" href="#/app/sense/meetings/${s.meetingId}">${esc(s.meeting)} · ${esc(s.who)} ${s.t}</a>`).join('')}`}</div>`).join('') : '<p class="muted">Ask across every meeting you were in. Each answer shows the lines it came from.</p>'}<div class="row" style="gap:8px;margin-top:12px"><input class="input grow" id="sn-ask" data-enter="sn-ask" placeholder="What did we promise the supplier?"><button class="btn" data-act="sn-ask">Ask</button></div></div>`;
  else if (tab === 'settings') { const s = get('snSet', 's', '/api/sense/settings'); body = !s ? loading : `<div class="stack" style="gap:16px;max-width:720px"><div class="card"><div class="set-row"><div class="grow"><div class="lbl">Daily email</div><div class="small muted">One email each morning: overdue, due tomorrow, due this week. No tone, no rating.</div></div>${sw(s.notifications, 'sn-notif', 'Daily email')}</div>
      <div class="set-row"><div class="grow"><div class="lbl">Transcription</div><div class="small muted">On for your meetings. The host can switch a meeting off from the Meetings list.</div></div><a class="btn ghost" href="#/app/sense/meetings">Meetings</a></div></div>
      <div class="card"><div class="card-head"><h3>Focus contacts</h3>${info('Meetings with these people are marked for you. Only you see your list.')}<span class="grow"></span><button class="btn ghost" data-act="sn-focus-add">${icon('add')}Add</button></div>${s.focus.length ? s.focus.map(f => `<div class="set-row"><div class="grow"><div class="lbl">${esc(f.name)}</div><div class="small muted">${esc(f.email)}</div></div><button class="btn text" data-act="sn-focus-del" data-id="${f.id}">Remove</button></div>`).join('') : '<p class="muted">Nobody yet.</p>'}</div>
      ${S.boot.admin ? `<div class="card"><div class="set-row"><div class="grow"><div class="lbl">People and roles</div><div class="small muted">Who can use Vanik Sense is set in the console. Admins cannot open anyone's meetings.</div></div><a class="btn ghost" href="#/os/apps/sense/people">Open</a></div></div>` : ''}</div>`; }
  else body = home();
  return appShell('sense', 'Sense', `${tab === 'meetings' && id ? '' : `<nav class="tabs">${TABS.map(t => `<a class="${t[0] === tab ? 'on' : ''}" href="#/app/sense${t[0] ? '/' + t[0] : ''}">${t[1]}</a>`).join('')}</nav>`}${body}`);
}
