'use strict';
// The apps that could be read on the testing appliance on 9 Oct 2026, copied one to one: Vanik Scout, Vanik MeasureBook, Vanik mBot,
// and Vanik Echo as its catalogue entry describes it. Same screens, same words, same calls. What stands in for a model is said in the
// README: Scout reads resumes by plain rules, MeasureBook's sheets are stored samples, Echo plays a stored meeting. Loaded by server.js.
// The audit these follow is in ../apps/*.md.
const crypto = require('crypto');
module.exports = function install(ctx) {
  const { db, on, err, uid, now, audit, isAdmin, DEMO, need, roleOf, toSense } = ctx;
  const R = db.real = db.real || {};
  R.scout = R.scout || { collections: [], docs: [], marks: [] }; R.scout.reviews = R.scout.reviews || []; R.mb = R.mb || { jobs: {}, batches: {} };
  R.echo = R.echo || { meetings: [] };
  const sha = s => crypto.createHash('sha256').update(String(s)).digest('hex').slice(0, 24);
  const rx = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), word = (text, w) => new RegExp('(^|[^a-z0-9+#])' + rx(w) + '([^a-z0-9+#]|$)').test(text);
  const csv = rows => rows.map(r => r.map(c => /[",\n]/.test(String(c ?? '')) ? '"' + String(c).replace(/"/g, '""') + '"' : String(c ?? '')).join(',')).join('\n');
  const day = (d = 0) => new Date(Date.now() + d * 864e5).toISOString().slice(0, 10);

  // ================= Vanik Scout =================
  const SC = R.scout;
  const SKILLS = { solar: ['Energy', 'pv', 'photovoltaic', 'renewable'], epc: ['Energy'], 'project management': ['Management', 'project manager', 'pm', 'pmp'], autocad: ['Design', 'cad'], sap: ['ERP', 'sap mm'], excel: ['Analytics', 'spreadsheets'], 'power bi': ['Analytics', 'dashboards'], python: ['Software'], java: ['Software'], kafka: ['Software', 'event streaming'], sql: ['Software', 'postgres', 'mysql'], aws: ['Software', 'cloud'], react: ['Software', 'frontend'], 'vendor management': ['Procurement', 'supplier management'], negotiation: ['Procurement'], gst: ['Finance', 'indirect tax'], tally: ['Finance'], recruitment: ['HR', 'talent acquisition', 'hiring'], payroll: ['HR'], 'quality control': ['Manufacturing', 'qc', 'quality assurance'], lean: ['Manufacturing', 'six sigma', 'kaizen'], plc: ['Manufacturing', 'scada'], hvac: ['MEP'], 'site execution': ['Construction', 'site engineer', 'site management'], tendering: ['Construction', 'bidding', 'estimation'], logistics: ['Supply chain', 'warehousing', 'dispatch'], sales: ['Sales', 'business development'], crm: ['Sales', 'salesforce'] };
  const CITIES = { pune: 'Pune', mumbai: 'Mumbai', bengaluru: 'Bengaluru', bangalore: 'Bengaluru', delhi: 'Delhi', hyderabad: 'Hyderabad', chennai: 'Chennai', ahmedabad: 'Ahmedabad', noida: 'Noida', gurugram: 'Gurugram' };
  const REASONS = ['Missing a must-have skill', 'Too junior', 'Too senior', 'Wrong location', 'Wrong domain', 'Salary expectation', 'Other'];
  const STOP = new Set('a an the and or of in for with to at on from who has have is are we need looking candidate years yrs year experience plus also must should nice preferably good strong'.split(' '));
  const skillsIn = low => Object.keys(SKILLS).filter(k => word(low, k) || SKILLS[k].slice(1).some(s => word(low, s)));
  const cityIn = low => (Object.keys(CITIES).find(c => word(low, c)) || '') && CITIES[Object.keys(CITIES).find(c => word(low, c))];
  const senOf = y => y >= 12 ? 'Lead' : y >= 7 ? 'Senior' : y >= 3 ? 'Mid' : 'Junior';
  const domOf = sk => { const n = {}; sk.forEach(s => { const d = SKILLS[s][0]; n[d] = (n[d] || 0) + 1; }); return Object.keys(n).sort((a, b) => n[b] - n[a])[0] || 'General'; };
  // a resume read by plain rules. This is the "stub backend" the header warns about.
  function profileOf(text) {
    const lines = text.split(/\r?\n/).map(l => l.trim()), low = text.toLowerCase(), name = (lines.find(Boolean) || 'Unnamed').slice(0, 60), email = (text.match(/[\w.+-]+@[\w-]+\.[\w.]+/) || [''])[0], phone = (text.match(/\+?\d[\d\s-]{8,}\d/) || [''])[0];
    const sect = h => { const i = lines.findIndex(l => new RegExp('^' + h + ':?$', 'i').test(l)); if (i < 0) return []; const out = []; for (let j = i + 1; j < lines.length && lines[j].startsWith('-'); j++) out.push(lines[j].replace(/^-\s*/, '')); return out; };
    const experience = sect('Experience'), education = sect('Education'), years = Math.max(0, ...(text.match(/(\d{1,2})\+?\s*(?:years|yrs)/gi) || []).map(x => parseInt(x, 10)).filter(n => n < 45)), skills = skillsIn(low);
    return { name, email, phone, title: (lines.filter(Boolean)[2] || '').slice(0, 80), location: cityIn(lines.slice(0, 4).join(' ').toLowerCase()) || cityIn(low), years, seniority: senOf(years), skills, domain: domOf(skills), employers: [...new Set(experience.map(e => (e.match(/,\s*([^,(]+?)\s*(?:\(|$)/) || [])[1]).filter(Boolean))], experience, education, summary: ((lines.find(l => /^summary:/i.test(l)) || '').replace(/^summary:\s*/i, '') || lines.filter(Boolean).slice(3, 5).join(' ')).slice(0, 400) };
  }
  const STAGES = ['Waiting for a worker', 'Reading the document', 'Building the profile', 'Adding to the index', 'Searchable'];
  const stage = d => d.failed ? 'Failed' : STAGES[Math.min(4, Math.floor((Date.now() - new Date(d.queuedAt).getTime()) / 1200))];
  const indexed = () => SC.docs.filter(d => stage(d) === 'Searchable');
  const colName = id => (SC.collections.find(c => c.id === id) || { name: 'General' }).name;
  function addResume(u, file, text, size, collectionId, at) {
    const id = sha(text);
    if (SC.docs.some(d => d.id === id)) return { file, rejected: 'These exact bytes were already indexed' };
    if ((size || text.length) > 25 * 1024 * 1024) return { file, rejected: 'over 25MB' };
    const failed = text.trim().length < 40, pr = failed ? { name: file, skills: [], employers: [], experience: [], education: [], years: 0, seniority: 'Junior', domain: 'General', location: '', email: '', phone: '', title: '', summary: '' } : profileOf(text);
    const d = { id, key: (pr.email || pr.name).toLowerCase().replace(/[^a-z0-9@.]+/g, '-'), file, size: size || text.length, text, collectionId, by: u.id, byName: u.name, at: at || now(), queuedAt: at || now(), attempts: 1, failed, profile: pr };
    SC.docs.unshift(d); return d;
  }
  const upView = d => ({ id: d.id, file: d.file, size: d.size, at: d.at, by: d.byName, mine: undefined, stage: stage(d), attempts: d.attempts, collection: colName(d.collectionId), collectionId: d.collectionId, key: d.key });
  function parseQ(q) {
    const low = String(q || '').toLowerCase(), cut = low.search(/\b(nice to have|preferably|bonus|a plus|good to have)\b/), head = cut < 0 ? low : low.slice(0, cut), tail = cut < 0 ? '' : low.slice(cut);
    const must = skillsIn(head), nice = skillsIn(tail).filter(s => !must.includes(s)), yrs = +(low.match(/(\d{1,2})\s*\+?\s*(?:years|yrs|yr|y)\b/) || [])[1] || 0;
    return { q: String(q || '').slice(0, 4000), must, nice, minYears: yrs, location: cityIn(low), seniority: /\b(lead|head|principal)\b/.test(low) ? 'Lead' : /\bsenior\b/.test(low) ? 'Senior' : /\bjunior|fresher\b/.test(low) ? 'Junior' : '', domain: domOf(must), employer: '', also: [] };
  }
  const cleanP = p => ({ q: String(p.q || '').slice(0, 4000), must: [...new Set((p.must || []).map(s => String(s).toLowerCase().trim()).filter(Boolean))].slice(0, 12), nice: [...new Set((p.nice || []).map(s => String(s).toLowerCase().trim()).filter(Boolean))].slice(0, 12), minYears: Math.max(0, Math.min(40, +p.minYears || 0)), location: String(p.location || ''), seniority: String(p.seniority || ''), domain: String(p.domain || ''), employer: String(p.employer || ''), also: (p.also || []).map(String).slice(0, 4) });
  const has = (d, s) => d.profile.skills.includes(s) || word(d.text.toLowerCase(), s);
  function run(u, P, o = {}) {
    const mine = Object.fromEntries(SC.marks.filter(m => m.userId === u.id).map(m => [m.key, m]));
    let pool = indexed().filter(d => !o.collectionId || d.collectionId === o.collectionId);
    if (!o.allVersions) { const newest = {}; pool.forEach(d => { if (!newest[d.key] || d.at > newest[d.key].at) newest[d.key] = d; }); pool = Object.values(newest); }
    const terms = [...new Set([...P.must, ...P.nice, ...P.q.toLowerCase().split(/[^a-z0-9+#]+/).filter(t => t.length > 2 && !STOP.has(t) && !/^\d+$/.test(t))])], browse = !terms.length && !P.minYears && !P.location;
    const locs = [P.location, ...P.also].filter(Boolean);
    let rows = pool.map(d => {
      const low = d.text.toLowerCase(), pr = d.profile, mh = P.must.filter(s => has(d, s)), nh = P.nice.filter(s => has(d, s)), kw = terms.length ? terms.filter(t => word(low, t)).length / terms.length : 0;
      const sem = P.must.length + P.nice.length ? [...P.must, ...P.nice].reduce((a, s) => a + (has(d, s) ? 1 : SKILLS[s] && pr.skills.some(x => SKILLS[x][0] === SKILLS[s][0]) ? 0.5 : 0), 0) / (P.must.length + P.nice.length) : kw ? 0.5 : 0;
      const cov = P.must.length ? mh.length / P.must.length : 1, yOk = !P.minYears || pr.years >= P.minYears, lOk = !locs.length || locs.includes(pr.location);
      return { d, kw, sem, cov, yOk, lOk, mh, nh, score: browse ? 0 : 0.55 * cov + 0.2 * sem + 0.15 * kw + 0.05 * yOk + 0.05 * lOk };
    }).filter(r => browse || r.kw > 0 || r.sem > 0);
    const F = o.filters || {}, any = (list, v) => !list || !list.length || list.includes(v);
    rows = rows.filter(r => (F.skills || []).every(s => r.d.profile.skills.includes(s)) && any(F.seniority, r.d.profile.seniority) && any(F.location, r.d.profile.location) && any(F.domain, r.d.profile.domain) && (!F.employer || !F.employer.length || r.d.profile.employers.some(e => F.employer.includes(e))));
    const beforeStrict = rows.length; if (o.strict) rows = rows.filter(r => r.cov === 1 && r.yOk && r.lOk);
    const byKw = [...rows].filter(r => r.kw > 0).sort((a, b) => b.kw - a.kw), bySem = [...rows].filter(r => r.sem > 0).sort((a, b) => b.sem - a.sem);
    rows.sort(browse ? (a, b) => (a.d.at < b.d.at ? 1 : -1) : (a, b) => b.score - a.score || (a.d.at < b.d.at ? 1 : -1));
    const top = rows.length ? rows[0].score || 1 : 1, count = k => { const n = {}; rows.forEach(r => [].concat(k(r.d.profile)).filter(Boolean).forEach(v => { n[v] = (n[v] || 0) + 1; })); return Object.entries(n).sort((a, b) => b[1] - a[1]).slice(0, 12).map(([value, n]) => ({ value, n })); };
    const hits = rows.map(r => { const pr = r.d.profile, k = byKw.indexOf(r) + 1, s = bySem.indexOf(r) + 1, m = mine[r.d.key]; return { id: r.d.id, key: r.d.key, name: pr.name, title: pr.title, years: pr.years, location: pr.location, seniority: pr.seniority, collection: colName(r.d.collectionId), fit: browse ? null : Math.round(100 * r.score / top), found: browse ? null : { kind: k && s ? 'both' : s ? 'semantic' : 'keyword', kw: k, sem: s }, has: r.mh, missing: P.must.filter(x => !r.mh.includes(x)), nice: r.nh, yearsOk: r.yOk, locOk: r.lOk, mark: m ? m.status : '' }; });
    let blocker = null; if (!rows.length && P.must.length) { const n = P.must.map(s => [s, pool.filter(d => has(d, s)).length]).sort((a, b) => a[1] - b[1])[0]; blocker = { skill: n[0], count: n[1] }; }
    const size = 8, page = Math.max(1, Math.min(+o.page || 1, Math.ceil(hits.length / size) || 1));
    return { parsed: P, browse, total: hits.length, hidden: o.strict ? beforeStrict - rows.length : 0, page, pages: Math.ceil(hits.length / size) || 1, hits: hits.slice((page - 1) * size, page * size), all: hits, mode: 'hybrid', blocker, facets: { skills: count(p => p.skills), seniority: count(p => p.seniority), location: count(p => p.location), domain: count(p => p.domain), employer: count(p => p.employers) } };
  }
  const out = r => ({ ...r, all: undefined });
  on('GET', '/api/scout/health', ({ u }) => { need(u, 'scout'); return { ok: true, indexed: indexed().length, stub: true, warm: true, role: roleOf(u, 'scout'), reasons: REASONS, skills: Object.keys(SKILLS) }; });
  on('POST', '/api/scout/search', ({ u, body }) => { need(u, 'scout'); return out(run(u, parseQ(body.q), body)); });
  on('POST', '/api/scout/search/parsed', ({ u, body }) => { need(u, 'scout'); return out(run(u, cleanP(body.parsed || {}), body)); });
  on('POST', '/api/scout/refine', ({ u, body }) => {
    need(u, 'scout'); const P = cleanP(body.parsed || {}), t = String(body.text || '').toLowerCase(); if (!t.trim()) throw err(400, 'Say what to change, for example "also Pune" or "drop AutoCAD".');
    let changed = 0;
    for (const part of t.split(/[·;,]| and /)) {
      const drop = /\b(drop|remove|without|no)\b/.test(part), sk = skillsIn(part), city = cityIn(part);
      if (drop) { sk.forEach(s => { P.must = P.must.filter(x => x !== s); P.nice = P.nice.filter(x => x !== s); changed++; }); if (city) { if (P.location === city) P.location = P.also.shift() || ''; P.also = P.also.filter(c => c !== city); changed++; } if (/\byears?\b/.test(part)) { P.minYears = 0; changed++; } }
      else { if (/\balso\b/.test(part) && city) { if (!P.location) P.location = city; else if (P.location !== city && !P.also.includes(city)) P.also.push(city); changed++; } else if (city) { P.location = city; changed++; } sk.filter(s => !P.must.includes(s)).forEach(s => { /\b(nice|plus|prefer)/.test(part) ? P.nice.push(s) : P.must.push(s); P.nice = P.nice.filter(x => !P.must.includes(x)); changed++; }); const y = +(part.match(/(\d{1,2})\s*\+?\s*(?:years|yrs)/) || [])[1]; if (y) { P.minYears = y; changed++; } if (/more senior/.test(part)) { P.minYears = (P.minYears || 3) + 2; P.seniority = senOf(P.minYears); changed++; } if (/more junior|less senior/.test(part)) { P.minYears = Math.max(0, P.minYears - 2); P.seniority = ''; changed++; } }
    }
    if (!changed) throw err(400, 'Nothing in that could be applied. Try "also Pune", "drop AutoCAD" or "more senior".');
    return out(run(u, cleanP(P), body));
  });
  on('GET', '/api/scout/candidate/:id', ({ u, p }) => { need(u, 'scout'); const d = SC.docs.find(x => x.id === p.id); if (!d) throw err(404, 'Candidate not found'); return { id: d.id, key: d.key, file: d.file, at: d.at, collection: colName(d.collectionId), versions: SC.docs.filter(x => x.key === d.key).length, profile: d.profile, text: d.text }; });
  const pname = id => (db.users.find(x => x.id === id) || { name: '' }).name;
  on('GET', '/api/scout/collections', ({ u }) => { need(u, 'scout'); return SC.collections.map(c => ({ ...c, status: c.status || 'open', manager: pname(c.managerId), count: SC.docs.filter(d => d.collectionId === c.id).length, shortlisted: new Set(SC.marks.filter(m => m.role === c.id && m.status === 'shortlisted').map(m => m.key)).size })); });
  on('POST', '/api/scout/collections', ({ u, body }) => { need(u, 'scout'); const name = String(body.name || '').trim().slice(0, 80); if (name.length < 2) throw err(400, 'Give the collection a name.'); if (SC.collections.some(c => c.name.toLowerCase() === name.toLowerCase())) throw err(409, 'A collection with that name exists.'); const c = { id: uid('col'), name, by: u.name, byId: u.id, at: now(), managerId: db.users.some(x => x.id === body.managerId) ? body.managerId : '', status: 'open' }; SC.collections.push(c); audit(u, 'Made a resume collection', name, 'Vanik Scout'); return c; });
  on('DELETE', '/api/scout/collections/:id', ({ u, p }) => { need(u, 'scout'); if (roleOf(u, 'scout') !== 'Scout admin') throw err(403, 'Only a Scout admin can delete a collection.'); SC.collections = SC.collections.filter(c => c.id !== p.id); SC.docs.forEach(d => { if (d.collectionId === p.id) d.collectionId = ''; }); return { ok: true }; });
  on('GET', '/api/scout/uploads', ({ u, q }) => { need(u, 'scout'); const all = q && q.get && q.get('scope') === 'all'; return SC.docs.filter(d => all || d.by === u.id).map(upView); });
  on('POST', '/api/scout/uploads', ({ u, body }) => {
    need(u, 'scout'); const c = SC.collections.find(x => x.id === body.collectionId); if (!c) throw err(400, 'Pick a collection first. Every résumé is filed under one.');
    const res = (Array.isArray(body.files) ? body.files : []).slice(0, 40).map(f => addResume(u, String(f.name || 'resume').slice(0, 120), String(f.text || ''), +f.size || 0, c.id)), ok = res.filter(r => !r.rejected);
    if (ok.length) audit(u, 'Uploaded resumes', c.name, `${ok.length} file${ok.length === 1 ? '' : 's'} · Vanik Scout`);
    return { accepted: ok.map(upView), rejected: res.filter(r => r.rejected) };
  });
  on('POST', '/api/scout/uploads/bulk', ({ u, body }) => { need(u, 'scout'); if (!SC.collections.some(x => x.id === body.collectionId)) throw err(400, 'Pick a collection first.'); throw err(501, body.kind === 'sheet' ? 'This build has no route out to fetch linked files. Upload the resumes themselves.' : 'This build cannot unpack a .zip. Upload the resumes themselves.'); });
  on('POST', '/api/scout/uploads/:id/retry', ({ u, p }) => { need(u, 'scout'); const d = SC.docs.find(x => x.id === p.id); if (!d) throw err(404, 'Upload not found'); d.attempts++; d.queuedAt = now(); d.failed = d.text.trim().length < 40; return upView(d); });
  on('DELETE', '/api/scout/uploads/:id', ({ u, p }) => { need(u, 'scout'); const d = SC.docs.find(x => x.id === p.id); if (!d) throw err(404, 'Upload not found'); if (d.by !== u.id && roleOf(u, 'scout') !== 'Scout admin') throw err(403, 'You can delete only your own uploads.'); SC.docs = SC.docs.filter(x => x !== d); audit(u, 'Deleted a resume', d.file, 'Vanik Scout'); return { ok: true }; });
  on('DELETE', '/api/scout/person/:key', ({ u, p }) => { need(u, 'scout'); if (roleOf(u, 'scout') !== 'Scout admin') throw err(403, 'Only a Scout admin can erase a person.'); const n = SC.docs.filter(d => d.key === p.key).length; if (!n) throw err(404, 'Person not found'); SC.docs = SC.docs.filter(d => d.key !== p.key); SC.marks = SC.marks.filter(m => m.key !== p.key); audit(u, 'Erased a person', '', `${n} version${n === 1 ? '' : 's'} removed · Vanik Scout`); return { removed: n }; });
  const CAP = 50, mark = (u, key, status, reason, role) => { if (!SC.docs.some(d => d.key === key)) return false; SC.marks = SC.marks.filter(m => !(m.userId === u.id && m.key === key)); SC.marks.push({ userId: u.id, key, status: status === 'rejected' ? 'rejected' : 'shortlisted', reason: status === 'rejected' ? (REASONS.includes(reason) ? reason : 'Other') : '', role: role || '', at: now() }); return true; };
  on('POST', '/api/scout/shortlist', ({ u, body }) => { need(u, 'scout'); if (!mark(u, body.key, body.status, body.reason, body.role)) throw err(404, 'Candidate not found'); audit(u, body.status === 'rejected' ? 'Rejected a candidate' : 'Shortlisted a candidate', '', (body.status === 'rejected' ? (REASONS.includes(body.reason) ? body.reason : 'Other') + ' · ' : '') + 'Vanik Scout'); return { ok: true }; });
  on('DELETE', '/api/scout/shortlist/:key', ({ u, p }) => { need(u, 'scout'); SC.marks = SC.marks.filter(m => !(m.userId === u.id && m.key === p.key)); return { ok: true }; });
  on('POST', '/api/scout/shortlist/bulk', ({ u, body }) => { need(u, 'scout'); const r = run(u, cleanP(body.parsed || {}), { ...body, page: 1 }), keys = body.scope === 'all' ? r.all.map(h => h.key) : (body.keys || []), take = keys.slice(0, CAP); take.forEach(k => mark(u, k, 'shortlisted', '', body.collectionId)); audit(u, 'Shortlisted candidates in bulk', '', `${take.length} · Vanik Scout`); return { added: take.length, capped: keys.length > CAP, cap: CAP }; });
  on('POST', '/api/scout/shortlist/bulk-remove', ({ u, body }) => { need(u, 'scout'); const before = SC.marks.length; SC.marks = SC.marks.filter(m => !(m.userId === u.id && m.status === 'shortlisted' && (body.all ? (body.role === undefined || m.role === body.role) : (body.keys || []).includes(m.key)))); return { removed: before - SC.marks.length }; });
  const listView = (u, role) => SC.marks.filter(m => m.userId === u.id && (role === undefined || role === null || m.role === role)).map(m => { const d = SC.docs.filter(x => x.key === m.key).sort((a, b) => (a.at < b.at ? 1 : -1))[0]; return d && { key: m.key, id: d.id, status: m.status, reason: m.reason, at: m.at, role: colName(m.role), roleId: m.role, verdict: (SC.reviews.find(r => r.key === m.key && r.collectionId === m.role) || {}).verdict || '', name: d.profile.name, title: d.profile.title, years: d.profile.years, location: d.profile.location, email: d.profile.email, phone: d.profile.phone, file: d.file }; }).filter(Boolean);
  on('GET', '/api/scout/shortlist', ({ u, q }) => { need(u, 'scout'); const role = q && q.get && q.get('role'); const L = listView(u, role === 'all' || role == null ? undefined : role); return { shortlisted: L.filter(x => x.status === 'shortlisted'), rejected: L.filter(x => x.status === 'rejected') }; });
  on('GET', '/api/scout/shortlist/export', ({ u, q }) => { need(u, 'scout'); const zip = q && q.get && q.get('kind') === 'zip', L = listView(u).filter(x => x.status === 'shortlisted'); audit(u, zip ? 'Exported shortlisted resumes' : 'Exported a shortlist', '', `${L.length} people · Vanik Scout`); return zip ? { name: 'shortlist-resumes.txt', text: L.map(x => `===== ${x.file} =====\n${SC.docs.find(d => d.id === x.id).text}`).join('\n\n') } : { name: 'shortlist.csv', text: csv([['Candidate', 'Title', 'Experience (years)', 'Location', 'Email', 'Phone', 'Role', 'Shortlisted on'], ...L.map(x => [x.name, x.title, x.years, x.location, x.email, x.phone, x.role, x.at.slice(0, 10)])]) }; });

  const col = id => { const c = SC.collections.find(x => x.id === id); if (!c) throw err(404, 'Job posting not found'); return c; };
  const owns = (u, c) => c.byId === u.id || roleOf(u, 'scout') === 'Scout admin';
  on('PATCH', '/api/scout/collections/:id', ({ u, p, body }) => { need(u, 'scout'); const c = col(p.id); if (!owns(u, c)) throw err(403, 'Only the person who made this posting, or a Scout admin, can change it.'); if (body.name !== undefined) c.name = String(body.name).trim().slice(0, 80) || c.name; if (body.managerId !== undefined) c.managerId = db.users.some(x => x.id === body.managerId) ? body.managerId : ''; if (body.status !== undefined) c.status = body.status === 'closed' ? 'closed' : 'open'; return { ok: true }; });
  on('POST', '/api/scout/collections/:id/share', ({ u, p }) => { need(u, 'scout'); const c = col(p.id); if (!c.managerId) throw err(409, 'Name a hiring manager on the job posting first.'); const n = SC.marks.filter(m => m.role === c.id && m.status === 'shortlisted').length; if (!n) throw err(409, 'Nobody is shortlisted for this posting yet.'); c.sharedAt = now(); c.sharedBy = u.name; audit(u, 'Shared a shortlist with the hiring manager', c.name, `${n} people · ${pname(c.managerId)} · Vanik Scout`); return { ok: true, manager: pname(c.managerId), count: n }; });
  on('GET', '/api/scout/reviews', ({ u }) => { need(u, 'scout'); return SC.collections.filter(c => c.managerId === u.id && c.sharedAt).map(c => ({ id: c.id, name: c.name, sharedBy: c.sharedBy, sharedAt: c.sharedAt, people: [...new Set(SC.marks.filter(m => m.role === c.id && m.status === 'shortlisted').map(m => m.key))].map(key => { const d = SC.docs.filter(x => x.key === key).sort((a, b) => (a.at < b.at ? 1 : -1))[0], r = SC.reviews.find(x => x.key === key && x.collectionId === c.id); return d && { key, id: d.id, name: d.profile.name, title: d.profile.title, years: d.profile.years, location: d.profile.location, skills: d.profile.skills, summary: d.profile.summary, verdict: r ? r.verdict : '' }; }).filter(Boolean) })); });
  on('POST', '/api/scout/reviews', ({ u, body }) => { need(u, 'scout'); const c = col(body.collectionId); if (c.managerId !== u.id) throw err(403, 'Only the hiring manager can decide here.'); SC.reviews = SC.reviews.filter(r => !(r.key === body.key && r.collectionId === c.id)); if (['interview', 'pass'].includes(body.verdict)) SC.reviews.push({ collectionId: c.id, key: body.key, verdict: body.verdict, by: u.name, at: now() }); audit(u, body.verdict === 'interview' ? 'Asked to interview a candidate' : 'Passed on a candidate', c.name, 'Vanik Scout'); return { ok: true }; });
  on('GET', '/api/scout/admin', ({ u, q }) => { need(u, 'scout'); if (roleOf(u, 'scout') !== 'Scout admin') throw err(403, 'For Scout admins.'); const s = String((q && q.get && q.get('q')) || '').toLowerCase().trim(), seen = {}; SC.docs.forEach(d => { (seen[d.key] = seen[d.key] || { key: d.key, name: d.profile.name, email: d.profile.email, versions: 0 }).versions++; }); return { models: [{ role: 'Reading resumes', model: 'Plain rules (no model connected)' }, { role: 'Search by meaning', model: 'Skill groups (no model connected)' }], indexed: indexed().length, people: s.length < 2 ? [] : Object.values(seen).filter(x => (x.name + ' ' + x.email).toLowerCase().includes(s)).slice(0, 8) }; });
  on('POST', '/api/scout/admin/test', ({ u }) => { need(u, 'scout'); if (roleOf(u, 'scout') !== 'Scout admin') throw err(403, 'For Scout admins.'); const t0 = Date.now(), P0 = parseQ('solar project manager pune 8 years'); return { ok: true, ms: Date.now() - t0 + 3, sample: `Read "solar project manager pune 8 years" as must-have ${P0.must.join(', ')}; ${P0.location}; ${P0.minYears}+ years.` }; });

  // ================= Vanik MeasureBook =================
  const MB = R.mb;
  const DISC = { hvac: ['HVAC', ['HVAC', 'AIR CONDITIONING', 'VENTILATION', 'AHU', 'DUCT', 'MECHANICAL']], plumbing: ['Plumbing', ['PLUMBING', 'WATER', 'DRAINAGE', 'SANITARY', 'SEWERAGE']], electrical: ['Electrical', ['ELECTRICAL', 'POWER', 'LIGHTING', 'WIRING', 'CABLE', 'SINGLE LINE']], fire_protection: ['Fire Protection', ['FIRE', 'SPRINKLER']], structural: ['Structural', ['STRUCTURAL', 'STEEL', 'CONCRETE', 'FOUNDATION', 'FRAMING']], civil: ['Civil / Architectural', ['ARCHITECTURAL', 'CIVIL', 'FLOOR PLAN', 'LAYOUT', 'GENERAL ARRANGEMENT']], pid: ['P&ID', ['P&ID', 'PID', 'PIPING AND INSTRUMENTATION', 'PROCESS FLOW', 'PFD']] };
  const BOOKS = { cpwd_2024: { name: 'CPWD Delhi SR 2024', currency: 'INR', k: 1 }, mes_2024: { name: 'MES Schedule of Rates 2024', currency: 'INR', k: 1.06 } };
  const ROOMS = [['OFFICE 101', 60, 60, 300, 200, '9000 x 6000'], ['MEETING 102', 360, 60, 240, 200, '7200 x 6000'], ['STORE 103', 600, 60, 140, 200, '4200 x 6000'], ['CORRIDOR', 60, 260, 680, 60, '20400 x 1800'], ['LAB 104', 60, 320, 400, 160, '12000 x 4800'], ['PLANT 105', 460, 320, 280, 160, '8400 x 4800']];
  const grid = (i, nx, ny, pad = 0.5) => { const [, x, y, w, h] = ROOMS[i], o = []; for (let a = 0; a < nx; a++) for (let b = 0; b < ny; b++) o.push([Math.round(x + w * (a + pad) / nx), Math.round(y + h * (b + pad) / ny)]); return o; };
  const rect = i => { const [, x, y, w, h] = ROOMS[i]; return [[x, y], [x + w, y], [x + w, y + h], [x, y + h]]; };
  const I = (tag, desc, unit, spec, conf, layer, geo, rate) => ({ tag, desc, unit, spec, conf, layer, ...geo, rate });
  const SHEETS = {
    hvac: [I('SAD-1', 'Supply air duct, GI, rectangular', 'RMT', '600 x 400, 24 G', 'Medium', 3, { paths: [[[700, 400], [700, 290], [80, 290]]] }, 2450), I('SAD-2', 'Branch duct, GI, rectangular', 'RMT', '300 x 200, 24 G', 'Medium', 3, { paths: [[[210, 290], [210, 160]], [[480, 290], [480, 160]], [[260, 290], [260, 400]]] }, 1380), I('SD', 'Supply air diffuser, 4-way', 'Nos', '600 x 600', 'High', 2, { pts: [...grid(0, 2, 1), ...grid(1, 2, 1), ...grid(4, 3, 1)] }, 3200), I('RG', 'Return air grille', 'Nos', '600 x 300', 'Low', 4, { pts: [[110, 100], [410, 100], [110, 440]] }, 2100), I('VCD', 'Volume control damper', 'Nos', '300 x 200', 'Medium', 3, { pts: [[210, 275], [480, 275], [260, 305]] }, 4600), I('AHU-1', 'Air handling unit, floor mounted', 'Nos', '12000 CMH', 'High', 2, { pts: [[700, 420]] }, 485000), I('INS', 'Duct insulation, nitrile rubber', 'SQMT', '25 mm thick', 'Low', 5, { from: ['SAD-1', 2.0, 'SAD-2', 1.0] }, 640)],
    plumbing: [I('CW-25', 'CPVC pipe, cold water', 'RMT', '25 mm, SDR 11', 'Medium', 3, { paths: [[[720, 340], [720, 280], [640, 280], [640, 120]], [[640, 280], [120, 280], [120, 360]]] }, 310), I('SWR-110', 'uPVC soil and waste pipe', 'RMT', '110 mm, type B', 'Medium', 3, { paths: [[[660, 110], [660, 300], [100, 300], [100, 380]]] }, 520), I('WC', 'Water closet, wall hung', 'Nos', 'With concealed cistern', 'High', 2, { pts: [[630, 90], [680, 90], [720, 90]] }, 14500), I('WB', 'Wash basin with pedestal', 'Nos', '550 x 400', 'High', 2, { pts: [[630, 220], [700, 220]] }, 6200), I('GV-25', 'Gate valve, brass', 'Nos', '25 mm', 'Medium', 3, { pts: [[720, 310], [640, 200], [300, 280]] }, 980), I('FT', 'Floor trap, uPVC', 'Nos', '110 x 75', 'Low', 4, { pts: [[650, 150], [140, 400], [520, 400]] }, 420), I('SINK', 'Lab sink, stainless steel', 'Nos', '600 x 450', 'High', 2, { pts: [[120, 400], [220, 400]] }, 8800)],
    electrical: [I('CT-300', 'Cable tray, perforated GI', 'RMT', '300 mm wide', 'Medium', 3, { paths: [[[700, 340], [700, 290], [80, 290]]] }, 890), I('LP', 'LED panel light, recessed', 'Nos', '600 x 600, 36 W', 'High', 2, { pts: [...grid(0, 3, 2), ...grid(1, 2, 2), ...grid(4, 4, 2), ...grid(2, 1, 2)] }, 2350), I('S6', 'Socket outlet, 6 A', 'Nos', '5 pin', 'High', 2, { pts: [[70, 120], [70, 200], [350, 120], [370, 120], [590, 200], [70, 380], [70, 440], [450, 440]] }, 310), I('S16', 'Socket outlet, 16 A', 'Nos', '6 pin, with switch', 'Low', 4, { pts: [[470, 380], [730, 380], [450, 380]] }, 520), I('DB', 'Distribution board, TPN', 'Nos', '12 way', 'High', 2, { pts: [[730, 290]] }, 18500), I('CND', 'PVC conduit with wiring', 'RMT', '20 mm, 2.5 sq mm', 'Low', 5, { per: ['LP', 3.5, 'S6', 4, 'S16', 5] }, 165)],
    fire_protection: [I('SP-80', 'Sprinkler main, MS, ERW', 'RMT', '80 NB', 'Medium', 3, { paths: [[[720, 470], [720, 290], [80, 290]]] }, 1720), I('SP-25', 'Sprinkler branch, MS', 'RMT', '25 NB', 'Medium', 3, { paths: [[[150, 290], [150, 110]], [[300, 290], [300, 110]], [[480, 290], [480, 110]], [[200, 290], [200, 440]], [[400, 290], [400, 440]]] }, 480), I('SPR', 'Pendent sprinkler, quick response', 'Nos', '68 C, K 80', 'High', 2, { pts: [...grid(0, 2, 2), ...grid(1, 1, 2), ...grid(4, 2, 2), ...grid(5, 1, 2)] }, 650), I('SD', 'Smoke detector, addressable', 'Nos', 'Photoelectric', 'High', 2, { pts: [...grid(0, 1, 1), ...grid(1, 1, 1), ...grid(2, 1, 1), ...grid(4, 2, 1), ...grid(5, 1, 1)] }, 2900), I('FE', 'Fire extinguisher, ABC', 'Nos', '6 kg', 'Low', 4, { pts: [[90, 280], [400, 280], [710, 280]] }, 2400), I('HR', 'Hose reel with drum', 'Nos', '30 m, 20 mm', 'High', 2, { pts: [[740, 300]] }, 14800)],
    structural: [I('C1', 'RCC column', 'Nos', '450 x 450, M30', 'High', 2, { pts: [[60, 60], [360, 60], [600, 60], [740, 60], [60, 260], [360, 260], [600, 260], [740, 260], [60, 480], [460, 480], [740, 480], [460, 320]] }, 28500), I('B1', 'RCC beam', 'RMT', '300 x 600, M30', 'Medium', 3, { paths: [[[60, 60], [740, 60]], [[60, 260], [740, 260]], [[60, 480], [740, 480]], [[60, 60], [60, 480]], [[740, 60], [740, 480]], [[360, 60], [360, 260]], [[600, 60], [600, 260]], [[460, 320], [460, 480]]] }, 6900), I('S1', 'RCC slab', 'SQMT', '150 thick, M25', 'Medium', 3, { polys: [[[60, 60], [740, 60], [740, 480], [60, 480]]] }, 1950), I('F1', 'Isolated footing', 'Nos', '1800 x 1800 x 450', 'Low', 5, { per: ['C1', 1] }, 41000)],
    civil: [I('FL', 'Vitrified tile flooring', 'SQMT', '600 x 600, 10 mm', 'Medium', 3, { polys: [rect(0), rect(1), rect(3), rect(4)] }, 1450), I('EP', 'Epoxy flooring', 'SQMT', '2 mm self levelling', 'Medium', 3, { polys: [rect(2), rect(5)] }, 980), I('BW', 'Brick wall', 'RMT', '230 thick, CM 1:6', 'Medium', 3, { paths: [[[60, 60], [740, 60], [740, 480], [60, 480], [60, 60]], [[360, 60], [360, 260]], [[600, 60], [600, 260]], [[60, 260], [740, 260]], [[60, 320], [740, 320]], [[460, 320], [460, 480]]] }, 3150), I('D1', 'Flush door with frame', 'Nos', '1000 x 2100', 'High', 2, { pts: [[200, 260], [470, 260], [660, 260], [240, 320], [590, 320]] }, 16400), I('W1', 'Aluminium sliding window', 'Nos', '1500 x 1200', 'High', 2, { pts: [[150, 60], [270, 60], [480, 60], [60, 400], [250, 480], [600, 480]] }, 11800), I('PL', 'Cement plaster, both faces', 'SQMT', '12 mm, CM 1:4', 'Low', 5, { from: ['BW', 6.0] }, 310)],
    pid: [I('GV', 'Gate valve', 'Nos', '100 NB, class 150', 'High', 2, { pts: [[160, 300], [430, 120]] }, 18400), I('CV', 'Check valve', 'Nos', '100 NB, class 150', 'High', 2, { pts: [[600, 140]] }, 16900), I('FCV', 'Control valve with actuator', 'Nos', '80 NB, globe', 'Medium', 3, { pts: [[300, 180]] }, 96000), I('PG', 'Pressure gauge', 'Nos', '0 to 10 bar', 'High', 2, { pts: [[230, 220], [520, 60]] }, 2400), I('FT', 'Flow transmitter', 'Nos', 'Magnetic, 100 NB', 'Medium', 3, { pts: [[365, 120]] }, 74000), I('P-101', 'Centrifugal pump', 'Nos', '60 cu m/h, 40 m head', 'High', 2, { pts: [[80, 300]] }, 215000), I('RED', 'Concentric reducer', 'Nos', '100 x 80 NB', 'Low', 4, { pts: [[270, 220], [330, 220]] }, 1900)],
  };
  const PIDLINE = [[80, 300], [200, 300], [200, 220], [400, 220], [400, 120], [560, 120], [560, 60], [680, 60]];
  const dist = (a, b) => Math.hypot(a[0] - b[0], a[1] - b[1]), plen = p => p.slice(1).reduce((s, q, i) => s + dist(p[i], q), 0), parea = p => Math.abs(p.reduce((s, q, i) => s + q[0] * p[(i + 1) % p.length][1] - p[(i + 1) % p.length][0] * q[1], 0)) / 2;
  function measure(sheet) {
    const k = sheet.mmPerPx, by = {};
    for (const it of sheet.items) {
      if (it.edited != null) { it.qty = it.edited; by[it.tag] = it.qty; continue; }
      if (it.pts) it.qty = it.pts.length; else if (it.paths) it.qty = k ? +(it.paths.reduce((s, p) => s + plen(p), 0) * k / 1000).toFixed(1) : null; else if (it.polys) it.qty = k ? +(it.polys.reduce((s, p) => s + parea(p), 0) * k * k / 1e6).toFixed(1) : null;
      else { const src = it.from || it.per; let q = 0, ok = true; for (let i = 0; i < src.length; i += 2) { const v = by[src[i]]; if (v == null) ok = false; q += (v || 0) * src[i + 1]; } it.qty = ok ? +q.toFixed(1) : null; }
      by[it.tag] = it.qty;
    }
  }
  const detect = name => { const up = String(name).toUpperCase().replace(/[_-]+/g, ' '); return ['pid', ...Object.keys(DISC)].find(d => d !== 'civil' && DISC[d][1].some(w => up.includes(w))) || (DISC.civil[1].some(w => up.includes(w)) ? 'civil' : ''); };
  function takeoff(u, f, o, n = 0) {
    const name = String(f.name || 'drawing.pdf').slice(0, 140); if (!/\.pdf$/i.test(name)) throw err(400, 'PDF only. Multi-page supported.');
    const pick = Object.keys(DISC), d = DISC[o.discipline] ? o.discipline : detect(name) || pick[n % 6], vl = !!o.vlVerify;
    const sheet = { n: 1, title: name.replace(/\.pdf$/i, ''), discipline: d, mmPerPx: d === 'pid' ? null : 30, scaleFrom: d === 'pid' ? '' : (o.scaleRoom ? 'Room ' + String(o.scaleRoom).slice(0, 30) : o.scaleDim ? 'Dimension ' + String(o.scaleDim).slice(0, 30) : 'Room dimensions'), items: JSON.parse(JSON.stringify(SHEETS[d])).filter(it => vl || it.layer !== 4) };
    measure(sheet);
    const j = { id: uid('job'), filename: name, size: +f.size || 0, by: u.name, userId: u.id, checked: {}, log: [], approved: null, at: now(), discipline: d, detected: !DISC[o.discipline], vl, sheets: [sheet] }; MB.jobs[j.id] = j; return j;
  }
  const jobView = j => { const done = Date.now() - new Date(j.at).getTime() > 2400; return { id: j.id, filename: j.filename, status: done ? 'done' : 'processing', step: done ? '' : Date.now() - new Date(j.at).getTime() > 900 ? 'Extracting quantities...' : 'Uploading file...', discipline: j.discipline, disciplineName: DISC[j.discipline][0], vl: j.vl, approved: j.approved || null, checked: j.checked || {}, log: (j.log || []).slice(-20), ...(done ? { sheets: j.sheets.map(s => ({ n: s.n, title: s.title, discipline: s.discipline, mmPerPx: s.mmPerPx, scaleFrom: s.scaleFrom, rooms: s.discipline === 'pid' ? [] : ROOMS, line: s.discipline === 'pid' ? PIDLINE : null, items: s.items.map((it, i) => ({ sno: i + 1, tag: it.tag, desc: it.desc, qty: it.qty, unit: it.unit, spec: it.spec, conf: it.conf, layer: it.layer, edited: it.edited != null, pts: it.pts || null, paths: it.paths || null, polys: it.polys || null })) })) } : {}) }; };
  const job = id => { const j = MB.jobs[id]; if (!j) throw err(404, 'Job not found'); return j; };
  on('GET', '/api/measurebook/disciplines', ({ u }) => { need(u, 'measurebook'); return Object.fromEntries(Object.entries(DISC).map(([k, v]) => [k, { name: v[0], title_keywords: v[1] }])); });
  on('GET', '/api/measurebook/rate-books', ({ u }) => { need(u, 'measurebook'); return Object.fromEntries(Object.entries(BOOKS).map(([k, v]) => [k, { name: v.name, currency: v.currency }])); });
  on('POST', '/api/measurebook/analyze', ({ u, body }) => { need(u, 'measurebook'); const j = takeoff(u, body.file || {}, body); audit(u, 'Ran a takeoff', j.filename, DISC[j.discipline][0] + ' · Vanik MeasureBook'); return { job_id: j.id }; });
  on('GET', '/api/measurebook/jobs/:id', ({ u, p }) => { need(u, 'measurebook'); return jobView(job(p.id)); });
  on('PUT', '/api/measurebook/jobs/:id/scale', ({ u, p, body }) => { need(u, 'measurebook'); const j = job(p.id), s = j.sheets[(+body.sheet || 1) - 1], a = body.a, b = body.b, mm = +body.mm; if (!s || !Array.isArray(a) || !Array.isArray(b) || !(mm > 0) || dist(a, b) < 2) throw err(400, 'Need two clicked points and a distance value'); if (j.approved) throw err(409, 'This bill is approved and locked.'); s.mmPerPx = +(mm / dist(a, b)).toFixed(3); s.scaleFrom = 'Set by hand'; measure(s); return jobView(j); });
  on('PUT', '/api/measurebook/jobs/:id/items/:tag', ({ u, p, body }) => { need(u, 'measurebook'); const j = job(p.id), s = j.sheets[(+body.sheet || 1) - 1], it = s && s.items.find(x => x.tag === p.tag); if (!it) throw err(404, 'Row not found'); if (j.approved) throw err(409, 'This bill is approved and locked.'); j.checked = j.checked || {}; j.log = j.log || []; if (body.checked !== undefined) j.checked[it.tag] = !!body.checked; if (body.qty !== undefined) { const was = it.qty; it.edited = body.qty === '' || body.qty === null ? null : Math.max(0, +body.qty || 0); measure(s); if (it.qty !== was) { j.log.push({ at: now(), by: u.name, tag: it.tag, from: was, to: it.qty }); j.checked[it.tag] = true; } } if (body.desc !== undefined) it.desc = String(body.desc).slice(0, 160) || it.desc; measure(s); return jobView(j); });
  on('GET', '/api/measurebook/jobs', ({ u }) => { need(u, 'measurebook'); return Object.values(MB.jobs).filter(j => j.userId === u.id).sort((a, b) => (a.at < b.at ? 1 : -1)).slice(0, 12).map(j => ({ id: j.id, filename: j.filename, at: j.at, discipline: DISC[j.discipline][0], rows: j.sheets[0].items.length, approved: !!j.approved })); });
  on('POST', '/api/measurebook/jobs/:id/approve', ({ u, p, body }) => { need(u, 'measurebook'); const j = job(p.id), r = roleOf(u, 'measurebook'); if (!['Reviewer', 'MeasureBook admin'].includes(r)) throw err(403, 'Only a Reviewer can approve a bill.'); if (body && body.reopen) { j.approved = null; audit(u, 'Reopened a bill of quantities', j.filename, 'Vanik MeasureBook'); return jobView(j); } const left = j.sheets[0].items.filter(it => it.conf === 'Low' && !(j.checked || {})[it.tag]).length; if (left) throw err(409, `Check the ${left} low-confidence row${left === 1 ? '' : 's'} first.`); j.approved = { by: u.name, at: now() }; audit(u, 'Approved a bill of quantities', j.filename, 'Locked · Vanik MeasureBook'); return jobView(j); });
  const boqRows = j => j.sheets.flatMap(s => s.items.map((it, i) => [i + 1, it.tag, it.desc, it.qty ?? '', it.unit, it.spec, it.conf]));
  on('GET', '/api/measurebook/jobs/:id/download', ({ u, p }) => { need(u, 'measurebook'); const j = job(p.id); audit(u, 'Exported a bill of quantities', j.filename, 'Vanik MeasureBook'); return { name: j.filename.replace(/\.pdf$/i, '') + ' BOQ.csv', text: csv([['S.No', 'Tag', 'Description', 'Qty', 'Unit', 'Spec', 'Conf.'], ...boqRows(j)]) }; });
  const unified = b => { const m = {}; b.files.filter(f => f.jobId).forEach(f => MB.jobs[f.jobId].sheets.forEach(s => s.items.forEach(it => { const k = it.tag + '|' + it.desc + '|' + it.unit, r = m[k] = m[k] || { tag: it.tag, desc: it.desc, unit: it.unit, qty: 0, discipline: s.discipline, sources: [] }; r.qty = +(r.qty + (it.qty || 0)).toFixed(1); if (!r.sources.includes(f.name)) r.sources.push(f.name); }))); return Object.values(m).map((r, i) => ({ sno: i + 1, ...r })); };
  const batchView = b => { const ms = Date.now() - new Date(b.at).getTime(), done = Math.min(b.files.length, Math.floor(ms / 700)), fin = done >= b.files.length, boq = fin ? unified(b) : []; return { id: b.id, status: fin ? 'done' : 'processing', done, total: b.files.length, current: fin ? '' : b.files[done].name, ...(fin ? { files: b.files.map(f => ({ name: f.name, jobId: f.jobId, error: f.error || '', discipline: f.jobId ? MB.jobs[f.jobId].discipline : '', pages: f.jobId ? 1 : 0 })), stats: { files: b.files.length, pages: b.files.filter(f => f.jobId).length, disciplines: new Set(boq.map(r => r.discipline)).size, types: boq.length, items: Math.round(boq.reduce((a, r) => a + (r.unit === 'Nos' ? r.qty : 1), 0)) }, byDiscipline: Object.keys(DISC).map(d => ({ id: d, name: DISC[d][0], n: boq.filter(r => r.discipline === d).length })).filter(x => x.n), boq } : {}) }; };
  on('POST', '/api/measurebook/analyze-batch', ({ u, body }) => { need(u, 'measurebook'); const files = (Array.isArray(body.files) ? body.files : []).slice(0, 40); if (!files.length) throw err(400, 'Drop at least one PDF drawing.'); const b = { id: uid('bat'), at: now(), by: u.name, files: files.map((f, i) => { try { const j = takeoff(u, f, body, i); j.at = new Date(Date.now() - 5000).toISOString(); j.batch = true; return { name: j.filename, jobId: j.id }; } catch (e) { return { name: String(f.name || 'file'), error: 'Error' }; } }) }; MB.batches[b.id] = b; audit(u, 'Ran a tender set takeoff', `${files.length} files`, 'Vanik MeasureBook'); return { batch_job_id: b.id }; });
  const batch = id => { const b = MB.batches[id]; if (!b) throw err(404, 'Batch not found'); return b; };
  on('GET', '/api/measurebook/batch/:id', ({ u, p }) => { need(u, 'measurebook'); return batchView(batch(p.id)); });
  on('GET', '/api/measurebook/batch/:id/download', ({ u, p }) => { need(u, 'measurebook'); const b = batch(p.id); audit(u, 'Exported a unified bill of quantities', `${b.files.length} files`, 'Vanik MeasureBook'); return { name: 'Unified BOQ.csv', text: csv([['S.No', 'Tag', 'Description', 'Qty', 'Unit', 'Discipline', 'Sources'], ...unified(b).map(r => [r.sno, r.tag, r.desc, r.qty, r.unit, DISC[r.discipline][0], r.sources.join('; ')])]) }; });
  // built in the live API with no screen yet: pricing against a rate book, and comparing two takeoffs
  on('POST', '/api/measurebook/estimate', ({ u, body }) => { need(u, 'measurebook'); const j = job(body.job_id), bk = BOOKS[body.rate_book] || BOOKS.cpwd_2024, rows = j.sheets.flatMap(s => s.items.map(it => ({ tag: it.tag, desc: it.desc, qty: it.qty, unit: it.unit, rate: Math.round(it.rate * bk.k), amount: it.qty == null ? null : Math.round(it.qty * it.rate * bk.k) }))); return { rate_book: bk.name, currency: bk.currency, rows, total: rows.reduce((a, r) => a + (r.amount || 0), 0) }; });
  on('POST', '/api/measurebook/compare', ({ u, body }) => { need(u, 'measurebook'); const a = job(body.a), b = job(body.b), A1 = Object.fromEntries(boqRows(a).map(r => [r[1], r])), B1 = Object.fromEntries(boqRows(b).map(r => [r[1], r])); return { added: Object.keys(B1).filter(k => !A1[k]), removed: Object.keys(A1).filter(k => !B1[k]), changed: Object.keys(A1).filter(k => B1[k] && A1[k][3] !== B1[k][3]).map(k => ({ tag: k, from: A1[k][3], to: B1[k][3] })) }; });

  // ================= Vanik Echo =================
  const EC = R.echo;
  const HINDI = [[1, 'नमस्ते, सब लोग जुड़ गए हैं तो शुरू करते हैं।'], [1, 'आज हमें पिछले हफ्ते की डिलीवरी और अगले महीने के ऑर्डर पर बात करनी है।'], [2, 'पिछले हफ्ते बारह में से ग्यारह ऑर्डर समय पर पहुँचे।'], [2, 'एक ऑर्डर टेस्ट सर्टिफिकेट न होने की वजह से रुका था।'], [3, 'भुगतान की तरफ से दो इनवॉइस रुके हुए हैं, क्योंकि कुल रकम परचेज़ ऑर्डर से मेल नहीं खाती।'], [1, 'ठीक है, तो पहले उन दो इनवॉइस को ठीक करवाते हैं।'], [3, 'मैं शुक्रवार तक सप्लायर से सही इनवॉइस मँगवा लूँगी।'], [2, 'अगले महीने के लिए हमें चार हज़ार बोल्ट और चाहिए।'], [1, 'तो तय रहा, ऑर्डर इसी हफ्ते भेज देंगे।'], [1, 'धन्यवाद, आज के लिए इतना ही।']];
  const eView = (m, full) => ({ sentTo: m.sentTo || '', id: m.id, title: m.title, startedAt: m.startedAt, endedAt: m.endedAt, live: !m.endedAt, language: 'Hindi', by: m.by, lines: full ? m.lines : undefined, count: m.lines.length, speakers: new Set(m.lines.map(l => l.speaker)).size, more: !m.endedAt && m.lines.length < HINDI.length });
  const eMeet = (u, id) => { const m = EC.meetings.find(x => x.id === id && x.userId === u.id); if (!m) throw err(404, 'Meeting not found'); return m; };
  on('GET', '/api/echo', ({ u }) => { need(u, 'echo'); return { role: roleOf(u, 'echo'), meetings: EC.meetings.filter(m => m.userId === u.id).map(m => eView(m, false)) }; });
  on('POST', '/api/echo/meetings', ({ u, body }) => { need(u, 'echo'); if (EC.meetings.some(m => m.userId === u.id && !m.endedAt)) throw err(409, 'A meeting is already running. End it first.'); const m = { id: uid('ech'), title: String(body.title || '').trim().slice(0, 120) || 'Meeting ' + new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }), userId: u.id, by: u.name, startedAt: now(), endedAt: '', lines: [] }; EC.meetings.unshift(m); return eView(m, true); });
  on('GET', '/api/echo/meetings/:id', ({ u, p }) => { need(u, 'echo'); return eView(eMeet(u, p.id), true); });
  // one more utterance. In the live app this is the speech model answering after a pause; here it is the next line of a stored meeting.
  on('POST', '/api/echo/meetings/:id/utterance', ({ u, p }) => { need(u, 'echo'); const m = eMeet(u, p.id); if (m.endedAt) throw err(409, 'This meeting has ended.'); const n = HINDI[m.lines.length]; if (n) { const s = Math.round((Date.now() - new Date(m.startedAt).getTime()) / 1000); m.lines.push({ t: `${String(Math.floor(s / 60)).padStart(2, '0')}:${String(s % 60).padStart(2, '0')}`, speaker: 'Speaker ' + n[0], text: n[1] }); } return eView(m, true); });
  on('POST', '/api/echo/meetings/:id/end', ({ u, p }) => { need(u, 'echo'); const m = eMeet(u, p.id); if (!m.endedAt) { m.endedAt = now(); audit(u, 'Recorded a meeting', m.title, `${m.lines.length} utterances kept on the appliance · Vanik Echo`); } return eView(m, true); });
  on('DELETE', '/api/echo/meetings/:id', ({ u, p }) => { need(u, 'echo'); const m = eMeet(u, p.id); EC.meetings = EC.meetings.filter(x => x !== m); audit(u, 'Deleted a meeting transcript', m.title, 'Vanik Echo'); return { ok: true }; });

  on('POST', '/api/echo/meetings/:id/to-sense', ({ u, p }) => { need(u, 'echo'); const m = eMeet(u, p.id); if (!m.endedAt) throw err(409, 'End the meeting first.'); if (!m.lines.length) throw err(409, 'There is nothing to send.'); if (!m.sentTo) m.sentTo = toSense(u, m.title, m.lines); return eView(m, true); });

  // ================= sample content, added once =================
  function sample() {
    if (R.sampled || !DEMO) return; R.sampled = true;
    const owner = db.users.find(x => x.role === 'owner'), by = n => db.users.find(x => x.name.startsWith(n)) || owner, ago = (d, h = 0) => new Date(Date.now() - d * 864e5 - h * 36e5).toISOString();
    const c1 = { id: uid('col'), name: 'Project Manager, Solar EPC', by: by('Neha').name, at: ago(20) }, c2 = { id: uid('col'), name: 'Procurement Analyst', by: by('Neha').name, at: ago(12) }, c3 = { id: uid('col'), name: 'Backend Engineer', by: by('Neha').name, at: ago(6) }; SC.collections.push(c1, c2, c3); [c1, c2, c3].forEach(c => { c.byId = by('Neha').id; c.status = 'open'; c.managerId = ''; }); c1.managerId = owner.id; c1.sharedAt = ago(1); c1.sharedBy = by('Neha').name;
    const cv = (name, mail, city, title, sum, exp, edu, skills) => `${name}\n${mail} | +91 98${String(sha(name)).replace(/\D/g, '').padEnd(8, '1').slice(0, 8)} | ${city}\n${title}\nSummary: ${sum}\nExperience:\n${exp.map(e => '- ' + e).join('\n')}\nEducation:\n${edu.map(e => '- ' + e).join('\n')}\nSkills: ${skills}`;
    const add = (c, d, ...a) => addResume(by('Neha'), a[0].replace(/ /g, '_') + '.pdf', cv(...a), 180000 + a[0].length * 3100, c.id, ago(d));
    add(c1, 18, 'Ananya Kulkarni', 'ananya.k@example.com', 'Pune', 'Senior Project Manager', '9 years delivering utility-scale solar projects from design to commissioning.', ['2021-2026 Senior Project Manager, SunVolt EPC (Pune)', '2017-2021 Project Engineer, Greenfield Renewables (Pune)'], ['B.E. Electrical, Pune University, 2016'], 'solar, epc, project management, autocad, site execution, vendor management');
    add(c1, 17, 'Rahul Deshmukh', 'rahul.d@example.com', 'Bengaluru', 'Project Manager', '7 years in rooftop and ground-mount solar. PMP certified.', ['2020-2026 Project Manager, HelioGrid (Bengaluru)', '2018-2020 Site Engineer, Suntrack Infra (Hubli)'], ['B.Tech Mechanical, RVCE, 2018'], 'solar, epc, project management, site execution, excel');
    add(c1, 15, 'Farah Sheikh', 'farah.s@example.com', 'Pune', 'Lead, Projects', '13 years across wind and solar EPC. Runs a team of 20 site engineers.', ['2016-2026 Lead Projects, Vayu Energy (Pune)', '2012-2016 Planning Engineer, L&T Construction (Mumbai)'], ['M.Tech Energy Systems, IIT Bombay, 2012'], 'solar, epc, project management, tendering, site execution, negotiation');
    add(c1, 14, 'Imran Qureshi', 'imran.q@example.com', 'Hyderabad', 'Site Engineer', '4 years of site execution on photovoltaic plants up to 50 MW.', ['2022-2026 Site Engineer, SolarOne (Hyderabad)'], ['B.Tech Civil, JNTU, 2021'], 'pv, site execution, autocad, quality control');
    add(c1, 40, 'Ananya Kulkarni', 'ananya.k@example.com', 'Pune', 'Project Manager', '7 years in solar projects.', ['2021-2024 Project Manager, SunVolt EPC (Pune)', '2017-2021 Project Engineer, Greenfield Renewables (Pune)'], ['B.E. Electrical, Pune University, 2016'], 'solar, epc, project management, site execution');
    add(c2, 11, 'Vikram Joshi', 'vikram.j@example.com', 'Pune', 'Procurement Analyst', '5 years in sourcing for an auto parts maker.', ['2021-2026 Procurement Analyst, Bharat Forge Components (Pune)'], ['B.Com, Symbiosis, 2020'], 'sap, excel, vendor management, negotiation, gst');
    add(c2, 10, 'Sneha Pillai', 'sneha.p@example.com', 'Chennai', 'Senior Buyer', '8 years buying castings and fasteners. Built supplier scorecards in Power BI.', ['2018-2026 Senior Buyer, TVS Supply (Chennai)'], ['MBA Operations, LIBA, 2018'], 'sap, power bi, vendor management, negotiation, logistics');
    add(c2, 9, 'Karan Malhotra', 'karan.m@example.com', 'Delhi', 'Accounts Executive', '3 years in accounts payable.', ['2023-2026 Accounts Executive, Northline Traders (Delhi)'], ['B.Com, Delhi University, 2022'], 'tally, gst, excel');
    add(c3, 5, 'Divya Ramesh', 'divya.r@example.com', 'Bengaluru', 'Backend Engineer', '6 years building event-driven services.', ['2020-2026 Backend Engineer, Ledgerly (Bengaluru)'], ['B.Tech CSE, NIT Trichy, 2020'], 'java, kafka, sql, aws');
    add(c3, 4, 'Arnav Bose', 'arnav.b@example.com', 'Pune', 'Software Engineer', '4 years of Python services and data pipelines.', ['2022-2026 Software Engineer, FreightLoop (Pune)'], ['B.E. IT, VIT Pune, 2022'], 'python, sql, aws, react');
    mark(by('Neha'), 'ananya.k@example.com', 'shortlisted', '', c1.id); mark(by('Neha'), 'imran.q@example.com', 'rejected', 'Too junior', c1.id);

    EC.meetings.push({ id: uid('ech'), title: 'साप्ताहिक समीक्षा', userId: by('Rohan').id, by: by('Rohan').name, startedAt: ago(3, 2), endedAt: ago(3, 1.6), lines: HINDI.slice(0, 7).map((n, i) => ({ t: `0${Math.floor(i * 9 / 60)}:${String((i * 9) % 60).padStart(2, '0')}`, speaker: 'Speaker ' + n[0], text: n[1] })) });
  }
  return { sample };
};
