'use strict';
// Vanik Sense (the meeting product that runs today as mBot), at its MVP: minutes, actions that are right and easy to fix,
// a daily list, focus contacts, questions with sources, and the feedback of October 2026 built in. Loaded by server.js.
// What stands in for the real thing: meetings are stored samples, minutes are picked out by plain rules, and emails,
// Teams messages and forwards are recorded, not sent. Plan: ../VANIK_EDGE_PLAN.md, section 8.
module.exports = function install(ctx) {
  const { db, on, err, uid, now, audit, DEMO, need, roleOf } = ctx;
  const S = db.sense = db.sense || { meetings: [], focus: {}, prefs: {}, intro: {} };
  const day = (d = 0) => new Date(Date.now() + d * 864e5).toISOString().slice(0, 10);
  const person = id => db.users.find(x => x.id === id), mailOf = u => u.email || u.name.toLowerCase().replace(/[^a-z]+/g, '.') + '@example.com', domain = u => mailOf(u).split('@')[1];
  const STOP = new Set('what when where which with that this from have were will would about their there your they them then than into over happened'.split(' '));
  const WD = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
  const dueOn = (s, at) => { const base = new Date(at), m = String(s || '').toLowerCase(), add = n => new Date(base.getTime() + n * 864e5).toISOString().slice(0, 10); if (!m) return ''; if (/^\d{4}-\d{2}-\d{2}$/.test(m)) return m; if (m === 'tomorrow') return add(1); if (m === 'end of week') return add((5 - base.getUTCDay() + 7) % 7 || 7); const w = WD.indexOf(m); return w < 0 ? '' : add((w - base.getUTCDay() + 7) % 7 || 7); };

  // Minutes by plain rules. An action goes to the person named, or to the speaker only when they say "I will".
  // Anything else has no owner and carries a suggestion for the host to confirm.
  function digest(lines, at) {
    const names = [...new Set(lines.map(l => l.who))], firsts = names.map(s => s.split(' ')[0]), actions = [], decisions = [];
    lines.forEach(l => l.text.split(/(?<=[.!?।])\s+/).forEach(s => {
      if (/\?\s*$/.test(s)) return;
      if (/\b(decided|agreed|approved|we will go with|go ahead with|is final|signed off)\b/i.test(s) && s.length > 20) return decisions.push(s.trim());
      if (!/\b(i will|i'll|will send|will share|will check|will raise|will call|will draft|needs? to)\b/i.test(s)) return;
      const named = firsts.find(f => new RegExp('\\b' + f + ' (will|needs? to)\\b', 'i').test(s)), mine = /\b(i will|i'll)\b/i.test(s), who = named ? names[firsts.indexOf(named)] : mine ? l.who : '';
      const pu = db.users.find(x => x.name === who), sp = db.users.find(x => x.name === l.who), due = (s.match(/\bby ((?:mon|tues|wednes|thurs|fri|satur|sun)day|tomorrow|end of week|\d{4}-\d{2}-\d{2})\b/i) || [])[1] || '';
      actions.push({ id: uid('act'), task: s.trim(), owner: who, ownerId: pu ? pu.id : '', due: dueOn(due, at), status: 'open', nudgedAt: '', trail: [], suggest: who && pu ? null : { name: who || l.who, userId: who ? '' : sp ? sp.id : '' } });
    }));
    const used = new Set([...decisions, ...actions.map(a => a.task)]), points = lines.flatMap(l => l.text.split(/(?<=[.!?।])\s+/)).filter(x => x.split(/\s+/).length >= 9 && !used.has(x.trim()) && !/\?\s*$/.test(x)).slice(0, 4);
    return { names, actions, decisions, points };
  }
  function make(organizer, title, lines, at, mins, extra = {}) {
    const d = digest(lines, at);
    return { id: uid('mtg'), title: String(title).slice(0, 140), at, mins, organizerId: organizer.id, series: '', participants: d.names.map(n => { const pu = db.users.find(x => x.name === n); return { name: n, email: pu ? mailOf(pu) : n.toLowerCase().replace(/[^a-z0-9]+/g, '.') + '@partner.example', userId: pu ? pu.id : '', added: false }; }),
      transcript: lines, summary: { overall: `${d.names.length} people met for ${mins} minutes. ${d.decisions.length} decision${d.decisions.length === 1 ? '' : 's'} and ${d.actions.length} action${d.actions.length === 1 ? '' : 's'} came out of it.`, decisions: d.decisions, points: d.points },
      actions: d.actions, notes: {}, editRights: 'owners', deleters: [], viewers: [], links: [], off: false, removed: false, ...extra };
  }
  const parse = text => String(text).split(/\r?\n/).map(l => l.trim().match(/^\[?(\d{1,2}:\d{2})\]?\s*([^:]{2,40}):\s*(.+)$/)).filter(Boolean).map(m => ({ t: m[1], who: m[2].trim(), text: m[3].trim() }));

  const inMeet = (u, m) => m.organizerId === u.id || m.participants.some(p => p.userId === u.id), canSee = (u, m) => inMeet(u, m) || m.viewers.includes(u.id);
  const meet = (u, id) => { const m = S.meetings.find(x => x.id === id); if (!m) throw err(404, "We couldn't find this meeting."); if (!canSee(u, m)) throw err(403, "You don't have access to this meeting."); return m; };
  const live = m => !m.removed && !m.off;
  const focusOf = u => S.focus[u.id] || [], focusIn = (u, m) => m.participants.filter(p => focusOf(u).some(f => f.email.toLowerCase() === p.email.toLowerCase()));
  const canEdit = (u, m, a) => m.organizerId === u.id || (m.editRights === 'all' && inMeet(u, m)) || (m.editRights === 'owners' && !!a && a.ownerId === u.id);
  const canDelete = (u, m) => m.organizerId === u.id || m.deleters.includes(u.id);
  const aView = (u, m, a) => ({ id: a.id, task: a.task, owner: a.owner, due: a.due, status: a.status, nudged: !!a.nudgedAt, trail: a.trail, suggest: a.ownerId ? null : a.suggest, meetingId: m.id, meeting: m.title, mine: a.ownerId === u.id, matched: !!a.ownerId, canEdit: canEdit(u, m, a), overdue: a.status === 'open' && !!a.due && a.due < day(), canNudge: a.status === 'open' && !!a.ownerId && a.ownerId !== u.id && (!a.nudgedAt || Date.now() - new Date(a.nudgedAt).getTime() > 864e5) });
  const attention = (u, m) => live(m) && m.actions.some(a => a.status === 'open' && (!a.ownerId || !a.due || a.due < day()));
  const mRow = (u, m) => ({ id: m.id, title: m.title, at: m.at, mins: m.mins, series: m.series, organizer: (person(m.organizerId) || { name: 'Someone' }).name, host: m.organizerId === u.id, readOnly: !inMeet(u, m), participants: m.participants.length, focus: focusIn(u, m).map(p => p.name), status: m.removed ? 'Removed' : m.off ? 'Not transcribed' : 'Ready', on: live(m), attention: attention(u, m), open: live(m) ? m.actions.filter(a => a.status === 'open').length : 0, done: live(m) ? m.actions.filter(a => a.status === 'done').length : 0 });
  const mine = u => S.meetings.filter(m => canSee(u, m)), acts = u => S.meetings.filter(m => inMeet(u, m) && live(m)).flatMap(m => m.actions.map(a => aView(u, m, a)));
  const pick = (u, f) => { const all = acts(u), wk = day(7); return (f === 'overdue' ? all.filter(a => a.mine && a.overdue) : f === 'tomorrow' ? all.filter(a => a.mine && a.status === 'open' && a.due === day(1)) : f === 'week' ? all.filter(a => a.mine && a.status === 'open' && a.due && a.due >= day() && a.due <= wk) : f === 'waiting' ? all.filter(a => a.status === 'open' && !a.mine && a.matched) : f === 'missing' ? all.filter(a => a.status === 'open' && (!a.due || !a.matched)) : f === 'done' ? all.filter(a => a.status === 'done') : f === 'all' ? all.filter(a => a.status === 'open') : all.filter(a => a.mine && a.status === 'open')).sort((a, b) => ((a.due || '9') < (b.due || '9') ? -1 : 1)); };

  on('GET', '/api/sense/home', ({ u }) => { need(u, 'sense'); const n = f => pick(u, f).length; return { name: u.name.split(' ')[0], role: roleOf(u, 'sense'), intro: !S.intro[u.id], counts: { overdue: n('overdue'), week: n('week'), waiting: n('waiting'), missing: n('missing'), meetings: mine(u).length }, digest: { on: (S.prefs[u.id] || {}).notifications !== false, overdue: pick(u, 'overdue').length, tomorrow: pick(u, 'tomorrow').length, week: n('week') }, recent: mine(u).slice(0, 3).map(m => mRow(u, m)) }; });
  on('POST', '/api/sense/intro', ({ u }) => { need(u, 'sense'); S.intro[u.id] = now(); return { ok: true }; });
  on('GET', '/api/sense/tasks', ({ u, q }) => { need(u, 'sense'); return pick(u, (q && q.get && q.get('filter')) || 'mine'); });
  const find = (u, id) => { for (const m of S.meetings) if (inMeet(u, m)) { const a = m.actions.find(x => x.id === id); if (a) return [m, a]; } throw err(404, 'Action not found'); };
  const setOwner = (u, m, a, key) => { const p = m.participants.find(x => x.email === key || (x.userId && x.userId === key)); if (!p) throw err(400, 'Pick someone from this meeting.'); a.trail.push({ at: now(), by: u.name, what: `Owner: ${a.owner || 'nobody'} to ${p.name}` }); a.owner = p.name; a.ownerId = p.userId; a.suggest = null; };
  const change = (u, m, a, b) => {
    if (b.status !== undefined) { if (!(a.ownerId === u.id || canEdit(u, m, a))) throw err(403, `Only ${a.owner || 'the host'} can mark this done`); a.status = b.status === 'done' ? 'done' : 'open'; a.trail.push({ at: now(), by: u.name, what: a.status === 'done' ? 'Marked done' : 'Reopened' }); }
    if (b.due !== undefined) { if (!canEdit(u, m, a)) throw err(403, 'Only the host or the owner can change this.'); if (b.due && !/^\d{4}-\d{2}-\d{2}$/.test(b.due)) throw err(400, 'Pick a date.'); a.trail.push({ at: now(), by: u.name, what: `Due: ${a.due || 'no date'} to ${b.due || 'no date'}` }); a.due = b.due || ''; }
    if (b.owner !== undefined) { if (!canEdit(u, m, a)) throw err(403, 'Only the host or the owner can change this.'); setOwner(u, m, a, b.owner); }
  };
  on('PUT', '/api/sense/tasks/:id', ({ u, p, body }) => { need(u, 'sense'); const [m, a] = find(u, p.id); change(u, m, a, body); return aView(u, m, a); });
  on('POST', '/api/sense/tasks/:id/confirm', ({ u, p }) => { need(u, 'sense'); const [m, a] = find(u, p.id); if (!canEdit(u, m, a)) throw err(403, 'Only the host can confirm an owner.'); if (!a.suggest || !a.suggest.userId) throw err(409, 'There is no one to suggest. Pick an owner.'); setOwner(u, m, a, a.suggest.userId); return aView(u, m, a); });
  on('DELETE', '/api/sense/tasks/:id', ({ u, p }) => { need(u, 'sense'); const [m, a] = find(u, p.id); if (!canEdit(u, m, a)) throw err(403, 'Only the host or the owner can delete this.'); m.actions = m.actions.filter(x => x !== a); audit(u, 'Deleted an action', m.title, 'Vanik Sense'); return { ok: true }; });
  const nudge = (u, m, a) => { if (!a.ownerId) throw err(409, 'This action has no owner yet.'); if (a.nudgedAt && Date.now() - new Date(a.nudgedAt).getTime() < 864e5) throw err(429, 'One reminder per action every 24 hours'); a.nudgedAt = now(); a.trail.push({ at: now(), by: u.name, what: 'Reminder sent by email and Teams' }); };
  on('POST', '/api/sense/tasks/:id/nudge', ({ u, p }) => { need(u, 'sense'); const [m, a] = find(u, p.id); nudge(u, m, a); return { ok: true, text: `Reminded ${a.owner} by email and Teams` }; });
  on('POST', '/api/sense/tasks/bulk', ({ u, body }) => { need(u, 'sense'); let n = 0, skipped = 0; for (const id of (body.ids || []).slice(0, 100)) { try { const [m, a] = find(u, id); if (body.op === 'done') change(u, m, a, { status: 'done' }); else if (body.op === 'due') change(u, m, a, { due: body.due }); else if (body.op === 'nudge') nudge(u, m, a); else if (body.op === 'delete') { if (!canEdit(u, m, a)) throw err(403, ''); m.actions = m.actions.filter(x => x !== a); } else throw err(400, 'Unknown'); n++; } catch (e) { skipped++; } } return { changed: n, skipped }; });

  on('GET', '/api/sense/meetings', ({ u, q }) => { need(u, 'sense'); const g = k => (q && q.get && q.get(k)) || '', s = g('q').toLowerCase(); return { contacts: focusOf(u), list: mine(u).filter(m => (g('scope') === 'organized' ? m.organizerId === u.id : g('scope') === 'participated' ? m.organizerId !== u.id : true) && (!g('transcript') || live(m)) && (!g('focus') || focusIn(u, m).length) && (!g('attention') || attention(u, m)) && (!g('contact') || m.participants.some(p => p.email.toLowerCase() === g('contact').toLowerCase())) && (!s || [m.title, ...m.participants.map(p => p.name + ' ' + p.email), ...m.summary.points, ...m.actions.map(a => a.task)].join(' ').toLowerCase().includes(s))).map(m => mRow(u, m)) }; });
  on('GET', '/api/sense/meetings/:id', ({ u, p }) => { need(u, 'sense'); const m = meet(u, p.id), ok = live(m), ro = !inMeet(u, m); return { ...mRow(u, m), editRights: m.editRights, canDelete: canDelete(u, m), deleters: m.deleters, people: m.participants.map(x => ({ ...x, focus: focusOf(u).some(f => f.email.toLowerCase() === x.email.toLowerCase()), host: !!x.userId && x.userId === m.organizerId })), summary: ok ? m.summary : null, transcript: ok ? m.transcript : [], links: ok ? m.links : [], actions: ok ? m.actions.map(a => ({ ...aView(u, m, a), canEdit: !ro && canEdit(u, m, a) })) : [], notes: ro ? [] : m.notes[u.id] || [], domain: domain(u), earlier: m.series ? S.meetings.filter(x => x !== m && x.series === m.series && x.title === m.title && canSee(u, x)).map(x => ({ id: x.id, at: x.at, open: x.actions.filter(a => a.status === 'open').length })) : [] }; });
  on('PUT', '/api/sense/meetings/:id', ({ u, p, body }) => {
    need(u, 'sense'); const m = meet(u, p.id); if (m.organizerId !== u.id) throw err(403, 'Only the host can change this.');
    if (['host', 'owners', 'all'].includes(body.editRights)) m.editRights = body.editRights;
    if (Array.isArray(body.deleters)) m.deleters = body.deleters.filter(id => m.participants.some(x => x.userId === id));
    if (body.off !== undefined) { const set = body.scope === 'all' && m.series ? S.meetings.filter(x => x.series === m.series && x.title === m.title && x.organizerId === u.id) : [m]; set.forEach(x => { x.off = !!body.off; }); audit(u, body.off ? 'Turned transcription off' : 'Turned transcription on', m.title, (set.length > 1 ? 'The whole series · ' : '') + 'Vanik Sense'); return { ok: true, changed: set.length }; }
    return { ok: true };
  });
  on('POST', '/api/sense/meetings/:id/notes', ({ u, p, body }) => { need(u, 'sense'); const m = meet(u, p.id), t = String(body.text || '').trim().slice(0, 2000); if (!t || !inMeet(u, m)) throw err(400, 'Write a note first.'); (m.notes[u.id] = m.notes[u.id] || []).push({ at: now(), text: t }); return m.notes[u.id]; });
  on('POST', '/api/sense/meetings/:id/forward', ({ u, p, body }) => { need(u, 'sense'); const m = meet(u, p.id), e = String(body.email || '').trim().toLowerCase(); if (!inMeet(u, m)) throw err(403, 'Only people who were in the meeting can forward it.'); const to = db.users.find(x => mailOf(x).toLowerCase() === e); if (!/^[\w.+-]+@[\w-]+\.[\w.]+$/.test(e) || (!to && e.split('@')[1] !== domain(u))) throw err(400, `Only people in your company can be sent this (@${domain(u)}).`); if (to && !canSee(to, m)) m.viewers.push(to.id); audit(u, 'Forwarded a meeting summary', m.title, 'Read-only · Vanik Sense'); return { ok: true, points: m.summary.points.length + m.summary.decisions.length, opens: to ? 'read-only' : 'email only' }; });
  on('POST', '/api/sense/meetings/:id/participants', ({ u, p, body }) => { need(u, 'sense'); const m = meet(u, p.id), name = String(body.name || '').trim().slice(0, 60), e = String(body.email || '').trim().toLowerCase(); if (!inMeet(u, m)) throw err(403, 'Only people who were in the meeting can add someone.'); if (!name || !/^[\w.+-]+@[\w-]+\.[\w.]+$/.test(e)) throw err(400, 'Give a name and a work email.'); if (m.participants.some(x => x.email.toLowerCase() === e)) throw err(409, `${name} is already in this meeting`); const pu = db.users.find(x => mailOf(x).toLowerCase() === e); m.participants.push({ name, email: e, userId: pu ? pu.id : '', added: true }); return { ok: true }; });
  on('DELETE', '/api/sense/meetings/:id/summary', ({ u, p }) => { need(u, 'sense'); const m = meet(u, p.id); if (!canDelete(u, m)) throw err(403, 'Only the host, or someone the host named, can delete this.'); m.removed = true; m.transcript = []; m.actions = []; m.links = []; m.summary = { overall: '', decisions: [], points: [] }; audit(u, 'Deleted meeting minutes', m.title, 'Minutes, transcript and actions · Vanik Sense'); return { ok: true }; });

  const prefs = u => ({ notifications: true, ...(S.prefs[u.id] || {}) });
  on('GET', '/api/sense/settings', ({ u }) => { need(u, 'sense'); return { ...prefs(u), focus: focusOf(u), role: roleOf(u, 'sense') }; });
  on('PUT', '/api/sense/settings', ({ u, body }) => { need(u, 'sense'); S.prefs[u.id] = { ...prefs(u), ...(body.notifications !== undefined ? { notifications: !!body.notifications } : {}) }; return prefs(u); });
  on('POST', '/api/sense/focus', ({ u, body }) => { need(u, 'sense'); const name = String(body.name || '').trim().slice(0, 60), e = String(body.email || '').trim().toLowerCase(); if (!name || !/^[\w.+-]+@[\w-]+\.[\w.]+$/.test(e)) throw err(400, 'Give a name and an email.'); const L = S.focus[u.id] = focusOf(u); if (L.some(f => f.email === e)) throw err(409, `${name} is already a focus contact`); L.push({ id: uid('fc'), name, email: e }); return L; });
  on('DELETE', '/api/sense/focus/:id', ({ u, p }) => { need(u, 'sense'); S.focus[u.id] = focusOf(u).filter(f => f.id !== p.id); return S.focus[u.id]; });
  on('POST', '/api/sense/ask', ({ u, body }) => { need(u, 'sense'); const terms = String(body.q || '').toLowerCase().split(/[^a-z0-9]+/).filter(t => t.length > 3 && !STOP.has(t)); if (!terms.length) throw err(400, 'Ask a question about your meetings.'); const hits = mine(u).filter(m => live(m) && (!body.meetingId || m.id === body.meetingId)).flatMap(m => m.transcript.map(l => ({ m, l, n: terms.filter(t => l.text.toLowerCase().includes(t)).length }))).filter(h => h.n > 0).sort((a, b) => b.n - a.n).slice(0, 3); return { answer: hits.length ? hits.map(h => h.l.text).join(' ') : 'Not found in your meetings.', sources: hits.map(h => ({ meetingId: h.m.id, meeting: h.m.title, who: h.l.who, t: h.l.t })) }; });

  // a transcript handed over from a room (Vanik Echo)
  function fromTranscript(u, title, lines) { const m = make(u, title, lines.map(l => ({ t: l.t, who: l.speaker, text: l.text })), now(), Math.max(1, Math.round(lines.length * 0.4)), { room: true }); m.summary.overall = `Room meeting. ${lines.length} utterances from ${m.participants.length} speakers. Minutes in Hindi need a Hindi model.`; S.meetings.unshift(m); audit(u, 'Sent a room transcript to Vanik Sense', m.title, 'Vanik Echo'); return m.id; }

  function sample() {
    if (S.sampled || !DEMO) return; S.sampled = true;
    const owner = db.users.find(x => x.role === 'owner'), by = n => db.users.find(x => x.name.startsWith(n)) || owner, ago = (d, h = 0) => new Date(Date.now() - d * 864e5 - h * 36e5).toISOString(), O = owner.name, f = O.split(' ')[0];
    const T1 = `[00:05] Rohan Mehta: Thanks for joining. Shree Fasteners delivered eleven of twelve orders on time last quarter, and the one late order was held at their end for a missing test certificate.\n[00:41] Asha Verma: On payments, two invoices are on hold because the invoice total did not match the purchase order. Finance cannot release them until the supplier sends corrected copies.\n[01:20] Neha Iyer: We agreed to keep them as an approved vendor for the next year, given the delivery record.\n[01:52] Rohan Mehta: Asha will send the two invoice numbers to the supplier by Friday.\n[02:10] Asha Verma: I will share the payment schedule once the corrected invoices arrive.\n[02:34] Neha Iyer: Rohan needs to raise the purchase order for the next four thousand bolts by tomorrow.\n[02:58] Rohan Mehta: Someone from quality will check the test certificate process with their plant.\n[03:10] Vikas Rao: I will send the revised test certificates once our lab signs them.`;
    const T2 = `[00:03] Neha Iyer: Three offers went out last week for the procurement analyst role and two were accepted.\n[00:30] Asha Verma: The third candidate asked for a later joining date, which pushes our month-end close support by two weeks.\n[01:02] Neha Iyer: We decided to hold the third offer open until Monday and then move to the next person on the shortlist.\n[01:25] Neha Iyer: I will call the candidate by Monday.\n[01:40] Asha Verma: I will draft the onboarding plan for the two joiners by end of week.`;
    const T3 = w => `[00:04] ${O}: Let us start with the plant audit. ${w ? 'The audit closed with two findings on storage of test certificates.' : 'The audit is booked for next week and the checklist is still open.'}\n[00:40] Rohan Mehta: Supplier delivery held at ninety two percent this week, and the late order from Shree Fasteners has now arrived.\n[01:15] Asha Verma: We agreed to release the two held invoices once the corrected copies are matched.\n[01:44] ${O}: Rohan will share the audit checklist with the plant by ${w ? 'Friday' : 'tomorrow'}.\n[02:05] Neha Iyer: I will send the hiring plan for the next quarter by end of week.\n[02:30] ${O}: Someone will check the travel policy changes with finance.`;
    const m1 = make(by('Rohan'), 'Vendor review: Shree Fasteners', parse(T1), ago(2, 3), 32, { links: [{ kind: 'link', title: 'Supplier scorecard, Q2', by: 'Rohan Mehta', t: '00:20' }, { kind: 'file', title: 'Held invoices.xlsx', by: 'Asha Verma', t: '00:50' }] });
    const m2 = make(by('Neha'), 'Hiring sync: procurement analyst', parse(T2), ago(1, 2), 18);
    const m3 = make(owner, 'Leadership weekly', parse(T3(1)), ago(8, 4), 28, { series: 'Weekly' }), m4 = make(owner, 'Leadership weekly', parse(T3(0)), ago(1, 4), 30, { series: 'Weekly', links: [{ kind: 'file', title: 'Audit checklist v3.docx', by: O, t: '00:10' }] });
    m3.actions.forEach((a, i) => { if (i < 2) a.status = 'done'; }); m1.actions[0].due = day(-1); m4.actions[0].due = day(1);
    S.meetings.unshift(m4, m2, m1, m3); void f;
  }
  return { sample, fromTranscript };
};
