'use strict';
// The rest of the Vanik Edge suite, from the master roadmap (Oct 2026): the five other apps in the store with install, health, access and a
// gateway key from the platform; a first working slice of each app; first-run set-up with a recovery key; the plan the appliance was sold on;
// models brought in from a file; and an evidence pack built from what the appliance is really set to do. Loaded by server.js.
const crypto = require('crypto');
module.exports = function install(ctx) {
  const { db, on, err, uid, now, audit, isAdmin, A, byId, allowed, cleanAccess, search, DEMO } = ctx;
  const S = db.suite = db.suite || {};
  S.apps = S.apps || {}; S.idp = S.idp || { docs: [] }; S.desk = S.desk || { tickets: [], seq: 1000, collectionId: '', firstHours: 4, resolveHours: 24 };
  S.echo = S.echo || { meetings: [] }; S.scout = S.scout || { jobs: [] }; S.mb = S.mb || { sets: [] };
  S.plan = S.plan || { tier: 'Department', people: 200, hardware: 'One GPU, 96 GB', renewsOn: new Date(Date.now() + 300 * 864e5).toISOString().slice(0, 10), offline: false };
  if (S.setup === undefined) S.setup = DEMO || db.users.length > 1 ? { doneAt: now(), by: 'Vanik' } : null;
  const sha = s => crypto.createHash('sha256').update(String(s)).digest('hex');
  const person = id => db.users.find(u => u.id === id);
  const label = a => !a || a.mode === 'everyone' ? 'Everyone' : (a.teams.length + a.users.length ? [...a.teams, ...a.users.map(i => (person(i) || { name: 'Someone' }).name)].join(', ') : 'Admins only');

  // ---------- the apps: what each is, what it needs, how it is doing
  const APPS = {
    idp: { name: 'Document processing', what: 'Pull chosen fields from invoices, orders and forms into a table, check them, and send them on.', icon: 'description', needsGb: 4, port: 9008, model: 'chat', noModel: 'No chat model serving. Documents written as label and value still work.', data: () => [S.idp.docs.length > 0, `${S.idp.docs.length} documents read, ${S.idp.docs.filter(d => d.status === 'review').length} waiting for a person`] },
    desk: { name: 'Vanik Desk', what: 'One queue for requests, with timers and a reply drafted from your knowledge base.', icon: 'support_agent', needsGb: 3, port: 9015, model: 'chat', noModel: 'No chat model serving. Drafts are built from passages as they are written.', data: () => { const c = db.collections.find(x => x.id === S.desk.collectionId); return [!!c, c ? 'Drafts from ' + c.name : 'No collection chosen to draft from']; } },
    echo: { name: 'Vanik Echo', what: 'A transcript with speakers, the decisions and the actions from any meeting.', icon: 'graphic_eq', needsGb: 4, port: 9014, model: 'speech', noModel: 'No speech model in the Model Hub. Paste or upload a transcript.', data: () => [true, `${S.echo.meetings.length} meetings kept on this appliance`] },
    scout: { name: 'Vanik Scout', what: 'Rank resumes against a job profile, with the reasons shown and each decision recorded.', icon: 'person_search', needsGb: 3, port: 9007, model: 'chat', noModel: 'No chat model serving. Ranking by stated skills and years still works.', data: () => [true, `${S.scout.jobs.length} jobs, ${S.scout.jobs.reduce((a, j) => a + j.candidates.length, 0)} candidates`] },
    measurebook: { name: 'Vanik MeasureBook', what: 'Turn engineering drawings into a bill of quantities, each line tied to its place on the drawing.', icon: 'straighten', needsGb: 9, port: 9013, model: 'vision', noModel: 'No drawing model serving. Lists can still be checked, corrected and priced.', data: () => [true, `${S.mb.sets.length} drawing sets`] },
  };
  const ORDER = Object.keys(APPS);
  const def = id => { if (!APPS[id]) throw err(404, 'App not found'); return APPS[id]; };
  const usedGb = () => ORDER.reduce((a, id) => a + (S.apps[id] && S.apps[id].status === 'running' ? APPS[id].needsGb : 0), 0);
  const canUse = (u, id) => !!S.apps[id] && S.apps[id].status === 'running' && db.device.online && allowed(S.apps[id].access, u);
  const need = (u, id) => { const a = S.apps[id], d = def(id); if (!a || a.status !== 'running') throw err(503, d.name + ' is not running.'); if (!db.device.online) throw err(503, 'The Vanik Appliance is offline.'); if (!allowed(a.access, u)) throw err(403, 'You do not have access to ' + d.name + '.'); };
  function health(id) {
    const a = S.apps[id], d = APPS[id], up = db.device.online, run = !!a && a.status === 'running', m = db.models.find(x => x.kind === d.model && x.status === 'serving'), key = db.keys.find(k => k.system && k.name === d.name && !k.revokedAt), dat = d.data();
    return [{ name: 'Device', state: up ? 'ok' : 'err', detail: up ? db.device.name + ' is online' : 'The appliance is offline' },
      { name: 'App', state: run && up ? 'ok' : 'err', detail: run ? (up ? 'Running on port ' + d.port : 'Stopped with the appliance') : 'Stopped' },
      { name: 'Model', state: m ? 'ok' : 'warn', detail: m ? 'Using ' + m.id : d.noModel },
      { name: 'Gateway key', state: key ? 'ok' : 'err', detail: key ? 'Issued by Vanik OS, ends …' + key.last4 : 'No key. Stop and start the app to issue one.' },
      { name: 'Access', state: 'ok', detail: label(a && a.access) },
      { name: 'Data', state: dat[0] ? 'ok' : 'warn', detail: dat[1] }];
  }
  const appView = (id, u, full) => { const a = S.apps[id], d = APPS[id]; return { id, name: d.name, what: d.what, icon: d.icon, needsGb: d.needsGb, port: d.port, status: a ? a.status : 'not_installed', canUse: canUse(u, id), ...(full && a ? { installedAt: a.installedAt, by: a.by, access: a.access, health: health(id) } : {}) }; };
  const boot = u => ({ apps: ORDER.map(id => appView(id, u, false)).filter(a => isAdmin(u) || a.canUse), setupDone: !!S.setup, plan: isAdmin(u) ? planView() : null });
  const planView = () => ({ ...S.plan, hardware: db.device.memGb + ' GB of GPU memory', used: db.users.length, over: db.users.length > S.plan.people });
  const view = u => ({ apps: ORDER.map(id => appView(id, u, true)), setup: S.setup, recovery: S.recovery ? { createdAt: S.recovery.createdAt, by: S.recovery.by } : null, plan: planView() });
  on('GET', '/api/suite', ({ u }) => view(u), A);
  function installApp(u, id) {
    const d = def(id); if (S.apps[id]) throw err(409, d.name + ' is already installed.');
    if (d.needsGb > ctx.freeGb()) throw err(409, `${d.name} needs ${d.needsGb} GB and ${ctx.freeGb()} GB is free. Park a model first.`);
    S.apps[id] = { status: 'running', installedAt: now(), by: u.name, access: { mode: 'everyone', teams: [], users: [] } };
    ctx.issueKey(d.name, 'Vanik OS', true);
    if (id === 'measurebook' && !db.models.some(m => m.kind === 'vision')) db.models.push({ id: 'qwen3-vl-8b-instruct', kind: 'vision', memGb: 12, context: 32768, status: 'available', port: null, note: 'Reads drawings and images' });
    if (id === 'desk' && !S.desk.collectionId && db.collections[0]) S.desk.collectionId = db.collections[0].id;
    audit(u, 'Installed an app', d.name, 'Gateway key issued by Vanik OS');
  }
  on('POST', '/api/suite/apps/:id/install', ({ u, p }) => { installApp(u, p.id); return view(u); }, A);
  on('POST', '/api/suite/apps/:id/stop', ({ u, p }) => { const a = S.apps[p.id]; if (!a || a.status !== 'running') throw err(409, def(p.id).name + ' is not running.'); a.status = 'stopped'; audit(u, 'Stopped an app', def(p.id).name); return view(u); }, A);
  on('POST', '/api/suite/apps/:id/start', ({ u, p }) => { const a = S.apps[p.id], d = def(p.id); if (!a || a.status !== 'stopped') throw err(409, d.name + ' is not stopped.'); if (d.needsGb > ctx.freeGb()) throw err(409, `${d.name} needs ${d.needsGb} GB and ${ctx.freeGb()} GB is free.`); a.status = 'running'; if (!db.keys.some(k => k.system && k.name === d.name && !k.revokedAt)) ctx.issueKey(d.name, 'Vanik OS', true); audit(u, 'Started an app', d.name); return view(u); }, A);
  on('DELETE', '/api/suite/apps/:id', ({ u, p }) => { const d = def(p.id); if (!S.apps[p.id]) throw err(409, d.name + ' is not installed.'); delete S.apps[p.id]; ctx.revokeSystemKeys(d.name); audit(u, 'Uninstalled an app', d.name, 'Its data is kept on the appliance'); return view(u); }, A);
  on('PUT', '/api/suite/apps/:id/access', ({ u, p, body }) => { const a = S.apps[p.id], d = def(p.id); if (!a) throw err(409, d.name + ' is not installed.'); a.access = cleanAccess(body.access); audit(u, 'Changed who can use an app', d.name, label(a.access)); return view(u); }, A);

  // ---------- first-run set-up and the recovery key. The key is shown once; only its fingerprint is kept.
  const newKey = u => { const raw = 'VNK-' + crypto.randomBytes(10).toString('hex').toUpperCase().match(/.{4}/g).join('-'); S.recovery = { hash: sha(raw), createdAt: now(), by: u.name }; return raw; };
  on('POST', '/api/suite/setup', async ({ u, body }) => {
    const name = String(body.name || '').trim().replace(/\s+/g, ' ').slice(0, 40); if (name.length < 2) throw err(400, 'Give the appliance a name people will recognise.');
    const domain = String(body.domain || '').trim().toLowerCase(); if (domain && !/^[a-z0-9-]+(\.[a-z0-9-]+)+$/.test(domain)) throw err(400, 'Enter a name such as ai.yourcompany.com, or leave it empty.');
    db.device.name = name; if (db.edge && db.edge.network) db.edge.network.domain = domain;
    const m = db.models.find(x => x.id === body.modelId); if (m && m.status === 'available' || m && m.status === 'parked') { try { await ctx.call(u, 'POST', `/api/models/${encodeURIComponent(m.id)}/serve`); } catch (e) { throw err(409, e.message); } }
    S.setup = { doneAt: now(), by: u.name }; const recoveryKey = newKey(u); audit(u, 'Finished set-up', name, 'Recovery key created');
    return { recoveryKey, suite: view(u) };
  }, A);
  on('POST', '/api/suite/recovery', ({ u }) => { const recoveryKey = newKey(u); audit(u, 'Made a new recovery key', '', 'The old key no longer works'); return { recoveryKey, suite: view(u) }; }, A);
  on('POST', '/api/suite/recovery/check', ({ body }) => ({ ok: !!S.recovery && sha(String(body.key || '').trim().toUpperCase()) === S.recovery.hash }), A);

  // ---------- a model brought in from a file, for sites with no connection. This build checks the shape of the package, not its signature.
  on('POST', '/api/suite/models/import', ({ u, body }) => {
    const m = body.manifest || {}, id = String(m.id || '').trim();
    if (!/^[\w.:\-]{3,60}$/.test(id)) throw err(400, 'The package has no model id.'); if (db.models.some(x => x.id === id)) throw err(409, id + ' is already in the Model Hub.');
    if (!['chat', 'embedding', 'vision', 'speech'].includes(m.kind)) throw err(400, 'The package does not say what the model is for.');
    if (!(+m.memGb > 0 && +m.memGb < 2000)) throw err(400, 'The package does not say how much memory the model needs.');
    if (!/^[a-f0-9]{64}$/i.test(m.sha256 || '') || !String(m.signature || '').trim()) throw err(400, 'The package is not signed. Only signed packages can be added.');
    db.models.push({ id, kind: m.kind, memGb: +(+m.memGb).toFixed(1), context: +m.context || null, status: 'available', port: null, note: String(m.note || 'Added from a file').slice(0, 80), source: 'file' });
    audit(u, 'Added a model from a file', id, 'Checksum ' + String(m.sha256).slice(0, 12)); return { ok: true, id };
  }, A);

  // ---------- evidence: where data goes, how long it is kept, what is hidden, who may use what. Read from the live settings.
  on('GET', '/api/suite/evidence', ({ u, q }) => {
    const E = db.edge || {}, cfg = db.app.config, sf = cfg.safety || {}, out = Object.entries(E.outside || {}).filter(([, v]) => v.key && (v.models || []).length), host = x => { try { return new URL(x).host || x; } catch { return String(x); } };
    const leaves = [
      ['Reached from the internet', !!(E.network && E.network.publicOn), E.network && E.network.publicOn ? 'Open at ' + E.network.domain : 'Closed. Only the office network reaches the appliance.'],
      ['Questions sent to models outside', out.length > 0, out.length ? out.map(([k, v]) => `${k}: ${v.models.map(m => m.id).join(', ')}`).join('; ') : 'No outside model is switched on.'],
      ['Documents sent to models outside', !!E.outsideDocs && out.length > 0, E.outsideDocs ? 'Passages may be sent with a question.' : 'Never. Outside models get the question only.'],
      ['Tools in other systems', db.mcp.length > 0, db.mcp.length ? db.mcp.map(m => `${m.name} (${host(m.url)})`).join(', ') : 'None connected.'],
      ['Events sent to other systems', db.webhooks.some(w => !w.paused), db.webhooks.length ? db.webhooks.map(w => host(w.url)).join(', ') : 'None.'],
      ['Sites the browser may open', (cfg.tools && cfg.tools.sites || []).length > 0, (cfg.tools && cfg.tools.sites || []).join(', ') || 'None.'],
      ['Voice typing', !!sf.voice, sf.voice ? 'On. Speech is turned into text by the browser maker.' : 'Off.'],
      ['Vanik support access', (E.support || []).some(s => s.status === 'open' && new Date(s.endsAt) > new Date()), 'Opened by an admin for a set time. ' + (E.support || []).length + ' sessions so far.'],
    ].map(([what, on_, detail]) => ({ what, on: on_, detail }));
    const kept = [['Chats', sf.retentionDays ? `Removed after ${sf.retentionDays} days` : 'Kept until a person deletes them'], ['Audit log and delivery records', `Kept ${(E.retention || { logsDays: 30 }).logsDays} days`], ['Temporary chats', 'Never saved'], ['Recordings and transcripts in Echo', 'Kept until a person deletes them']].map(([what, rule]) => ({ what, rule }));
    const hidden = [['Indian IDs in questions (Aadhaar, PAN, GSTIN, phone)', { mask: 'Hidden before the model sees them', flag: 'Flagged to the person', off: 'Not checked' }[sf.pii] || 'Not checked'], ['Indian IDs in documents', sf.maskDocuments ? 'Hidden when a document is added' : 'Kept as written'], ['Admins reading people\'s chats', sf.adminChats ? 'Allowed, and every opening is recorded' : 'Not allowed']].map(([what, rule]) => ({ what, rule }));
    const restricted = l => l.filter(x => x.access && x.access.mode === 'restricted').length;
    const access = [['Collections', db.collections.length, restricted(db.collections)], ['Shared agents', db.assistants.filter(a => a.shared).length, restricted(db.assistants.filter(a => a.shared))], ['Apps', ORDER.filter(i => S.apps[i]).length + (db.app.status === 'not_installed' ? 0 : 1), restricted(ORDER.map(i => S.apps[i]).filter(Boolean)) + (cfg.access && cfg.access.mode === 'restricted' ? 1 : 0)]].map(([what, total, limited]) => ({ what, total, limited }));
    const people = { total: db.users.length, admins: db.users.filter(isAdmin).length, fromDirectory: db.users.filter(x => x.fromDirectory).length };
    if (q && q.get && q.get('download')) audit(u, 'Downloaded the evidence pack');
    return { at: now(), appliance: db.device.name, os: (E.updates || {}).version || db.device.agent, leaves, kept, hidden, access, people, log: { entries: db.audit.length, first: db.audit.length ? db.audit[db.audit.length - 1].at : null, last: db.audit.length ? db.audit[0].at : null } };
  }, A);

  // ---------- Document processing: fields by template, checks, a person corrects what is doubtful
  const C36 = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  const gstinDigit = g => { let s = 0; for (let i = 0; i < 14; i++) { const p = C36.indexOf(g[i]) * (i % 2 ? 2 : 1); s += Math.floor(p / 36) + p % 36; } return C36[(36 - s % 36) % 36]; };
  const gstinOk = g => /^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(g) && gstinDigit(g) === g[14];
  const money = v => { const n = parseFloat(String(v).replace(/[^\d.\-]/g, '')); return isFinite(n) ? n : null; };
  const TPL = {
    gst_invoice: { name: 'GST invoice', hint: /tax invoice|invoice (no|number)/i, fields: [['invoice_no', 'Invoice number', ['invoice no', 'invoice number', 'invoice'], 'text', 1], ['invoice_date', 'Invoice date', ['invoice date', 'date'], 'date', 1], ['supplier', 'Supplier', ['supplier', 'seller', 'from'], 'text', 1], ['supplier_gstin', 'Supplier GSTIN', ['supplier gstin', 'seller gstin', 'gstin'], 'gstin', 1], ['buyer_gstin', 'Buyer GSTIN', ['buyer gstin', 'customer gstin', 'bill to gstin'], 'gstin', 0], ['po_number', 'Purchase order', ['po number', 'po no', 'purchase order'], 'text', 0], ['taxable', 'Taxable value', ['taxable value', 'taxable amount', 'subtotal'], 'money', 1], ['tax', 'GST', ['gst', 'igst', 'total gst', 'total tax', 'tax'], 'money', 1], ['total', 'Invoice total', ['invoice total', 'grand total', 'total', 'total amount'], 'money', 1]] },
    purchase_order: { name: 'Purchase order', hint: /purchase order/i, fields: [['po_number', 'PO number', ['po number', 'po no', 'purchase order'], 'text', 1], ['po_date', 'PO date', ['po date', 'date'], 'date', 1], ['supplier', 'Supplier', ['supplier', 'vendor', 'to'], 'text', 1], ['buyer_gstin', 'Buyer GSTIN', ['buyer gstin', 'gstin'], 'gstin', 0], ['deliver_by', 'Deliver by', ['deliver by', 'delivery date', 'due date'], 'date', 0], ['total', 'Order total', ['order total', 'total', 'total amount'], 'money', 1]] },
    eway_bill: { name: 'E-way bill', hint: /e-?way bill/i, fields: [['ewb_no', 'E-way bill number', ['e way bill no', 'eway bill no', 'ewb no', 'e way bill number'], 'ewb', 1], ['ewb_date', 'Generated on', ['generated on', 'date'], 'date', 1], ['from_gstin', 'From GSTIN', ['from gstin', 'supplier gstin'], 'gstin', 1], ['to_gstin', 'To GSTIN', ['to gstin', 'recipient gstin', 'buyer gstin'], 'gstin', 1], ['vehicle', 'Vehicle', ['vehicle no', 'vehicle number', 'vehicle'], 'text', 0], ['value', 'Value of goods', ['value of goods', 'total value', 'value'], 'money', 1]] },
  };
  const okDate = v => /^\d{1,2}[\/\-. ](\d{1,2}|[A-Za-z]{3,9})[\/\-. ]\d{2,4}$/.test(v) || /^\d{4}-\d{2}-\d{2}$/.test(v);
  const doubt = (kind, v) => !v ? 'Not found' : kind === 'gstin' && !gstinOk(v) ? 'Not a well-formed GSTIN' : kind === 'money' && money(v) === null ? 'Not an amount' : kind === 'date' && !okDate(v) ? 'Not a date' : kind === 'ewb' && !/^\d{12}$/.test(v.replace(/\s/g, '')) ? 'An e-way bill number has 12 digits' : '';
  function recheck(d) {
    const f = k => (d.fields.find(x => x.key === k) || {}).value || '', t = TPL[d.template];
    d.fields.forEach(x => { const kind = t.fields.find(y => y[0] === x.key)[3]; x.doubt = x.value || x.required ? doubt(kind, x.value) : ''; if (x.corrected && !x.doubt) x.conf = 1; });
    d.checks = [];
    if (d.template === 'gst_invoice') { const a = money(f('taxable')), b = money(f('tax')), c = money(f('total')); d.checks.push({ name: 'Taxable value plus GST equals the total', ok: a !== null && b !== null && c !== null && Math.abs(a + b - c) <= 1, detail: a !== null && b !== null && c !== null ? `${a.toLocaleString('en-IN')} + ${b.toLocaleString('en-IN')} = ${(a + b).toLocaleString('en-IN')}, document says ${c.toLocaleString('en-IN')}` : 'An amount is missing' }); }
    if (d.template === 'eway_bill') d.checks.push({ name: 'Sender and receiver are different', ok: !!f('from_gstin') && f('from_gstin') !== f('to_gstin'), detail: 'From and To GSTIN' });
    const ids = d.fields.filter(x => /gstin/.test(x.key) && x.value); if (ids.length) d.checks.push({ name: 'Every GSTIN is well formed', ok: ids.every(x => gstinOk(x.value)), detail: ids.map(x => x.value).join(', ') });
    const open = d.fields.filter(x => x.doubt || (x.value && x.conf < 0.8)).length + d.checks.filter(c => !c.ok).length;
    if (d.status !== 'approved') d.status = open ? 'review' : 'ready';
    d.open = open; return d;
  }
  function readDoc(u, name, text, template) {
    const tid = TPL[template] ? template : (Object.keys(TPL).find(k => TPL[k].hint.test(text)) || 'gst_invoice'), t = TPL[tid];
    const pairs = text.split(/\r?\n/).map(l => l.trim().match(/^([^:]{2,40}):\s*(.+)$/)).filter(Boolean).map(m => [m[1].toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim(), m[2].trim()]), taken = new Set();
    const fields = t.fields.map(([key, lab, alias, , req]) => { let hit = pairs.findIndex((p, i) => !taken.has(i) && alias.includes(p[0])), conf = 0.96; if (hit < 0) { hit = pairs.findIndex((p, i) => !taken.has(i) && alias.some(a => a.length > 3 && p[0].includes(a))); conf = 0.7; } if (hit >= 0) taken.add(hit); return { key, label: lab, value: hit >= 0 ? pairs[hit][1].slice(0, 200) : '', conf: hit >= 0 ? conf : 0, required: !!req, corrected: false }; });
    return recheck({ id: uid('idp'), name: String(name).slice(0, 160), template: tid, text: text.slice(0, 20000), fields, checks: [], status: 'review', addedBy: u.name, addedAt: now(), history: [] });
  }
  const idpRow = d => ({ id: d.id, name: d.name, template: TPL[d.template].name, status: d.status, open: d.open, addedBy: d.addedBy, addedAt: d.addedAt, total: (d.fields.find(f => /total|value/.test(f.key)) || {}).value || '' });
  on('GET', '/api/idp', ({ u }) => { need(u, 'idp'); return { docs: S.idp.docs.map(idpRow), templates: Object.entries(TPL).map(([id, t]) => ({ id, name: t.name, fields: t.fields.map(f => f[1]) })) }; });
  on('POST', '/api/idp/docs', ({ u, body }) => { need(u, 'idp'); const text = String(body.text || ''); if (text.trim().length < 20) throw err(400, 'No readable text found in "' + (body.name || 'the file') + '".'); const d = readDoc(u, body.name || 'Document', text, body.template); S.idp.docs.unshift(d); audit(u, 'Read a document', d.name, TPL[d.template].name + (d.open ? `, ${d.open} to check` : ', nothing to check')); return d; });
  on('GET', '/api/idp/docs/:id', ({ u, p }) => { need(u, 'idp'); return byId(S.idp.docs, p.id, 'Document'); });
  on('PUT', '/api/idp/docs/:id', ({ u, p, body }) => { need(u, 'idp'); const d = byId(S.idp.docs, p.id, 'Document'), f = d.fields.find(x => x.key === body.key); if (!f) throw err(404, 'Field not found'); if (d.status === 'approved') throw err(409, 'This document is approved. Reopen it to change a field.'); const v = String(body.value || '').trim().slice(0, 200); if (v !== f.value) { d.history.unshift({ at: now(), by: u.name, field: f.label, was: f.value, now: v }); f.value = v; f.corrected = true; } else if (body.confirm) { f.corrected = true; f.conf = 1; } return recheck(d); });
  on('POST', '/api/idp/docs/:id/approve', ({ u, p, body }) => { need(u, 'idp'); const d = byId(S.idp.docs, p.id, 'Document'); if (body.reopen) { d.status = 'review'; d.approvedBy = ''; audit(u, 'Reopened a document', d.name); return recheck(d); } const missing = d.fields.filter(f => f.required && !f.value); if (missing.length) throw err(409, 'Fill in first: ' + missing.map(f => f.label).join(', ') + '.'); const failed = d.checks.filter(c => !c.ok).length; d.status = 'approved'; d.approvedBy = u.name; d.approvedAt = now(); d.open = 0; audit(u, 'Approved a document', d.name, failed ? `${failed} check not passed, accepted by a person` : 'All checks passed'); return d; });
  on('DELETE', '/api/idp/docs/:id', ({ u, p }) => { need(u, 'idp'); const d = byId(S.idp.docs, p.id, 'Document'); S.idp.docs = S.idp.docs.filter(x => x !== d); audit(u, 'Deleted a read document', d.name); return { ok: true }; });
  const csv = rows => rows.map(r => r.map(v => `"${String(v == null ? '' : v).replace(/"/g, '""')}"`).join(',')).join('\n');
  on('GET', '/api/idp/export', ({ u }) => { need(u, 'idp'); const done = S.idp.docs.filter(d => d.status === 'approved'), keys = [...new Set(done.flatMap(d => d.fields.map(f => f.label)))]; audit(u, 'Exported approved documents', done.length + ' documents'); return { name: 'approved-documents', count: done.length, csv: csv([['Document', 'Kind', 'Approved by', ...keys], ...done.map(d => [d.name, TPL[d.template].name, d.approvedBy, ...keys.map(k => (d.fields.find(f => f.label === k) || {}).value || '')])]), json: done.map(d => ({ document: d.name, kind: d.template, fields: Object.fromEntries(d.fields.map(f => [f.key, f.value])) })) }; });

  // ---------- Vanik Desk: one queue, timers, a reply drafted from the knowledge base with its source
  const dueAt = (t, h) => new Date(new Date(t.createdAt).getTime() + h * 36e5).toISOString();
  const tView = t => { const first = t.messages.find(m => m.who === 'agent'), fDue = dueAt(t, S.desk.firstHours), rDue = dueAt(t, S.desk.resolveHours), nowT = now(); return { ...t, firstDue: fDue, resolveDue: rDue, firstState: first ? (first.at <= fDue ? 'met' : 'missed') : nowT > fDue ? 'late' : 'running', resolveState: t.status === 'solved' ? (t.solvedAt <= rDue ? 'met' : 'missed') : nowT > rDue ? 'late' : 'running', assigneeName: (person(t.assignee) || { name: '' }).name }; };
  const deskDocs = u => { const c = db.collections.find(x => x.id === S.desk.collectionId); return c && allowed(c.access, u) ? db.documents.filter(d => d.collectionId === c.id && d.chunks.length) : []; };
  on('GET', '/api/desk', ({ u }) => { need(u, 'desk'); return { tickets: S.desk.tickets.map(tView).map(t => ({ ...t, messages: undefined, last: t.messages[t.messages.length - 1].at })), settings: { collectionId: S.desk.collectionId, firstHours: S.desk.firstHours, resolveHours: S.desk.resolveHours }, collections: db.collections.filter(c => allowed(c.access, u)).map(c => ({ id: c.id, name: c.name })), agents: db.users.filter(x => canUse(x, 'desk')).map(x => ({ id: x.id, name: x.name })) }; });
  function addTicket(u, b, at) { const subject = String(b.subject || '').trim().slice(0, 160), text = String(b.body || '').trim().slice(0, 6000), from = String(b.from || '').trim().slice(0, 80); if (!subject || !text || !from) throw err(400, 'A request needs who it is from, a subject and the message.'); const t = { id: uid('tk'), n: ++S.desk.seq, from, email: String(b.email || '').slice(0, 120), subject, channel: ['mail', 'form', 'chat'].includes(b.channel) ? b.channel : 'form', priority: ['low', 'normal', 'high'].includes(b.priority) ? b.priority : 'normal', status: 'open', assignee: '', createdAt: at || now(), messages: [{ at: at || now(), who: 'customer', by: from, text }] }; S.desk.tickets.unshift(t); return t; }
  on('POST', '/api/desk/tickets', ({ u, body }) => { need(u, 'desk'); const t = addTicket(u, body); audit(u, 'Logged a request', `#${t.n} ${t.subject}`); return tView(t); });
  on('GET', '/api/desk/tickets/:id', ({ u, p }) => { need(u, 'desk'); return tView(byId(S.desk.tickets, p.id, 'Request')); });
  async function draft(u, t) {
    const q = t.subject + ' ' + t.messages.filter(m => m.who === 'customer').map(m => m.text).join(' '), hits = await search(q, deskDocs(u), 3); if (!hits.length) return { text: '', sources: [] };
    const words = new Set(q.toLowerCase().match(/[a-z0-9]{4,}/g) || []), top = hits[0], sents = top.text.replace(/^#+\s.*$/gm, '').split(/(?<=[.!?])\s+|\n+/).map(s => s.replace(/^[-*]\s*/, '').trim()).filter(s => s.length > 25);
    const best = sents.map((s, i) => [i, (s.toLowerCase().match(/[a-z0-9]{4,}/g) || []).filter(w => words.has(w)).length]).sort((a, b) => b[1] - a[1]).slice(0, 3).filter(x => x[1] > 0).sort((a, b) => a[0] - b[0]).map(x => sents[x[0]]);
    return { text: `Hello ${t.from.split(' ')[0]},\n\n${(best.length ? best : sents.slice(0, 2)).join(' ')}\n\nRegards,\n${u.name}`, sources: hits.map(h => ({ docId: h.docId, docName: h.docName, page: h.page })) };
  }
  on('POST', '/api/desk/tickets/:id/draft', async ({ u, p }) => { need(u, 'desk'); return draft(u, byId(S.desk.tickets, p.id, 'Request')); });
  on('POST', '/api/desk/tickets/:id/reply', ({ u, p, body }) => { need(u, 'desk'); const t = byId(S.desk.tickets, p.id, 'Request'), text = String(body.text || '').trim().slice(0, 6000); if (!text) throw err(400, 'Write the reply first.'); t.messages.push({ at: now(), who: 'agent', by: u.name, text, sources: (Array.isArray(body.sources) ? body.sources : []).slice(0, 5).map(s => ({ docId: String(s.docId || ''), docName: String(s.docName || '').slice(0, 160), page: s.page || null })) }); if (!t.assignee) t.assignee = u.id; t.status = body.solve ? 'solved' : 'waiting'; if (body.solve) t.solvedAt = now(); audit(u, body.solve ? 'Answered and solved a request' : 'Answered a request', `#${t.n} ${t.subject}`); return tView(t); });
  on('PUT', '/api/desk/tickets/:id', ({ u, p, body }) => { need(u, 'desk'); const t = byId(S.desk.tickets, p.id, 'Request'); if (body.assignee !== undefined) t.assignee = person(body.assignee) ? body.assignee : ''; if (['low', 'normal', 'high'].includes(body.priority)) t.priority = body.priority; if (['open', 'waiting', 'solved'].includes(body.status)) { t.status = body.status; t.solvedAt = body.status === 'solved' ? now() : null; } return tView(t); });
  on('PUT', '/api/desk/settings', ({ u, body }) => { if (body.collectionId !== undefined) S.desk.collectionId = db.collections.some(c => c.id === body.collectionId) ? body.collectionId : ''; if (body.firstHours) S.desk.firstHours = Math.max(1, Math.min(72, +body.firstHours || 4)); if (body.resolveHours) S.desk.resolveHours = Math.max(1, Math.min(720, +body.resolveHours || 24)); audit(u, 'Changed Desk settings'); return { ok: true }; }, A);

  // ---------- Vanik Echo: a transcript with speakers; decisions and actions picked out by plain rules
  function readMeeting(u, title, text, at) {
    const lines = []; let who = 'Speaker 1';
    String(text).split(/\r?\n/).map(l => l.trim()).filter(Boolean).forEach(l => { const m = l.match(/^(?:\[?(\d{1,2}:\d{2}(?::\d{2})?)\]?\s*)?([A-Z][A-Za-z .'-]{1,28}):\s*(.+)$/); if (m) { who = m[2].trim(); lines.push({ t: m[1] || '', speaker: who, text: m[3].trim() }); } else if (lines.length && !/^\[?\d{1,2}:\d{2}/.test(l)) lines[lines.length - 1].text += ' ' + l; else lines.push({ t: '', speaker: who, text: l.replace(/^\[?\d{1,2}:\d{2}(?::\d{2})?\]?\s*/, '') }); });
    if (!lines.length) throw err(400, 'No lines found in the transcript.');
    const speakers = [...new Set(lines.map(l => l.speaker))], firsts = speakers.map(s => s.split(' ')[0]);
    const actions = [], decisions = [];
    lines.forEach((l, i) => l.text.split(/(?<=[.!?])\s+/).forEach(s => {
      if (/\?\s*$/.test(s)) return;
      if (/\b(decided|agreed|approved|we will go with|go ahead with|is final|signed off)\b/i.test(s) && s.length > 20) decisions.push({ text: s.trim(), line: i });
      else if (/\b(i will|i'll|we will|we'll|will send|will share|will check|will raise|will call|will draft|needs? to|to be done by|action:)\b/i.test(s)) { const named = firsts.find(f => new RegExp('^' + f + '\\b.*\\bwill\\b', 'i').test(s) || new RegExp('\\b' + f + ' (will|needs? to)\\b', 'i').test(s)), due = (s.match(/\bby ((?:mon|tues|wednes|thurs|fri|satur|sun)day|tomorrow|end of (?:day|week|month)|\d{1,2}(?:st|nd|rd|th)? [A-Za-z]{3,9}|\d{4}-\d{2}-\d{2})\b/i) || [])[1] || ''; actions.push({ text: s.trim(), owner: named ? speakers[firsts.indexOf(named)] : l.speaker, due, line: i, taskId: '' }); }
    }));
    const points = lines.map((l, i) => [i, l.text.split(/\s+/).length]).filter(x => !actions.some(a => a.line === x[0]) && x[1] >= 12).sort((a, b) => b[1] - a[1]).slice(0, 3).sort((a, b) => a[0] - b[0]).map(x => ({ text: lines[x[0]].text.split(/(?<=[.!?])\s+/)[0], speaker: lines[x[0]].speaker }));
    return { id: uid('mt'), title: String(title || 'Meeting').slice(0, 120), at: at || now(), by: u.name, userId: u.id, lines, speakers, points, decisions, actions, savedTo: '' };
  }
  const mine = (u, m) => isAdmin(u) || m.userId === u.id || (m.shared || []).includes(u.id);
  on('GET', '/api/echo', ({ u }) => { need(u, 'echo'); return { meetings: S.echo.meetings.filter(m => mine(u, m)).map(m => ({ id: m.id, title: m.title, at: m.at, by: m.by, speakers: m.speakers.length, lines: m.lines.length, actions: m.actions.length, decisions: m.decisions.length })), collections: db.collections.filter(c => ctx.canWrite(u, c)).map(c => ({ id: c.id, name: c.name })), speech: db.models.some(x => x.kind === 'speech' && x.status === 'serving') }; });
  on('POST', '/api/echo/meetings', ({ u, body }) => { need(u, 'echo'); const m = readMeeting(u, body.title, body.text); S.echo.meetings.unshift(m); audit(u, 'Added a meeting transcript', m.title, `${m.lines.length} lines, ${m.actions.length} actions`); return m; });
  const meeting = (u, id) => { const m = byId(S.echo.meetings, id, 'Meeting'); if (!mine(u, m)) throw err(404, 'Meeting not found'); return m; };
  on('GET', '/api/echo/meetings/:id', ({ u, p }) => { need(u, 'echo'); return meeting(u, p.id); });
  on('POST', '/api/echo/meetings/:id/actions/:i/task', async ({ u, p }) => { need(u, 'echo'); const m = meeting(u, p.id), a = m.actions[+p.i]; if (!a) throw err(404, 'Action not found'); if (a.taskId) throw err(409, 'This is already a task.'); const to = db.users.find(x => x.name === a.owner || x.name.split(' ')[0] === a.owner.split(' ')[0]); const t = await ctx.call(u, 'POST', '/api/tasks', { title: a.text.slice(0, 160), note: `From the meeting "${m.title}".` + (a.due ? ' Due: ' + a.due + '.' : ''), assignee: to ? to.id : undefined, due: /^\d{4}-\d{2}-\d{2}$/.test(a.due) ? a.due : '' }); a.taskId = t.id; a.taskFor = t.assigneeName; return m; });
  on('POST', '/api/echo/meetings/:id/save', ({ u, p, body }) => { need(u, 'echo'); const m = meeting(u, p.id), c = byId(db.collections, body.collectionId, 'Collection'); if (!ctx.canWrite(u, c)) throw err(403, 'You cannot add to ' + c.name + '.'); const text = `Meeting: ${m.title}\nDate: ${m.at.slice(0, 10)}\n\n` + m.lines.map(l => `${l.speaker}: ${l.text}`).join('\n'); ctx.addDocument(u, c.id, { name: m.title + ' (transcript).txt', type: 'txt', size: text.length, pages: [text], paged: false, purpose: 'Meeting transcript' }); m.savedTo = c.name; audit(u, 'Saved a transcript to knowledge', m.title, c.name); return m; });
  on('DELETE', '/api/echo/meetings/:id', ({ u, p }) => { need(u, 'echo'); const m = meeting(u, p.id); S.echo.meetings = S.echo.meetings.filter(x => x !== m); audit(u, 'Deleted a meeting', m.title); return { ok: true }; });

  // ---------- Vanik Scout: score against stated skills and years, never the name; record every decision
  const has = (text, skill) => new RegExp('(^|[^a-z0-9+#])' + skill.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '([^a-z0-9+#]|$)').test(text);
  const listOf = v => [...new Set((Array.isArray(v) ? v : String(v || '').split(',')).map(s => String(s).trim()).filter(Boolean))].slice(0, 12);
  function score(job, c) {
    const text = c.text.toLowerCase(), yrs = Math.max(0, ...(c.text.match(/(\d{1,2})\+?\s*(?:years|yrs)/gi) || []).map(x => parseInt(x, 10)).filter(n => n < 45)), must = job.must.map(s => [s, has(text, s)]), nice = job.nice.map(s => [s, has(text, s)]);
    const wM = 60, wN = job.nice.length ? 25 : 0, wY = job.minYears ? 15 : 0, tot = wM + wN + wY, pts = wM * (must.filter(x => x[1]).length / (must.length || 1)) + wN * (nice.filter(x => x[1]).length / (nice.length || 1)) + wY * Math.min(1, yrs / (job.minYears || 1));
    c.years = yrs; c.score = Math.round(100 * pts / tot);
    c.reasons = [...must.map(([s, ok]) => ({ ok, text: ok ? `Mentions ${s}` : `No mention of ${s} (must have)` })), ...(job.minYears ? [{ ok: yrs >= job.minYears, text: yrs ? `${yrs} years stated, ${job.minYears} asked` : `Years of experience not stated, ${job.minYears} asked` }] : []), ...nice.filter(x => x[1]).map(([s]) => ({ ok: true, text: `Also mentions ${s}` }))];
    return c;
  }
  const strip = t => t.replace(/[\w.+-]+@[\w-]+\.[\w.]+/g, '[email]').replace(/(\+?\d[\d\s-]{8,}\d)/g, '[phone]');
  const jobView = (j, full) => { const cs = [...j.candidates].sort((a, b) => b.score - a.score); return { id: j.id, title: j.title, must: j.must, nice: j.nice, minYears: j.minYears, blind: j.blind, createdBy: j.createdBy, createdAt: j.createdAt, count: cs.length, shortlisted: cs.filter(c => c.decision && c.decision.value === 'shortlist').length, ...(full ? { candidates: cs.map((c, i) => ({ id: c.id, name: j.blind ? 'Candidate ' + (j.candidates.indexOf(c) + 1) : c.name, file: j.blind ? '' : c.file, score: c.score, years: c.years, reasons: c.reasons, decision: c.decision, rank: i + 1, text: j.blind ? strip(c.text.split('\n').slice(1).join('\n')) : c.text })) } : {}) }; };
  on('GET', '/api/scout', ({ u }) => { need(u, 'scout'); return { jobs: S.scout.jobs.map(j => jobView(j, false)) }; });
  on('POST', '/api/scout/jobs', ({ u, body }) => { need(u, 'scout'); const title = String(body.title || '').trim().slice(0, 120), must = listOf(body.must); if (!title || !must.length) throw err(400, 'A job needs a title and at least one must-have skill.'); const j = { id: uid('job'), title, must, nice: listOf(body.nice), minYears: Math.max(0, Math.min(40, +body.minYears || 0)), blind: true, candidates: [], createdBy: u.name, createdAt: now() }; S.scout.jobs.unshift(j); audit(u, 'Added a job to Scout', title, 'Must have: ' + must.join(', ')); return jobView(j, true); });
  on('GET', '/api/scout/jobs/:id', ({ u, p }) => { need(u, 'scout'); return jobView(byId(S.scout.jobs, p.id, 'Job'), true); });
  on('PUT', '/api/scout/jobs/:id', ({ u, p, body }) => { need(u, 'scout'); const j = byId(S.scout.jobs, p.id, 'Job'); if (body.blind !== undefined) j.blind = !!body.blind; if (body.must) { j.must = listOf(body.must); j.nice = listOf(body.nice); j.minYears = Math.max(0, Math.min(40, +body.minYears || 0)); j.candidates.forEach(c => score(j, c)); audit(u, 'Changed a job profile', j.title, 'Every candidate was scored again'); } return jobView(j, true); });
  on('POST', '/api/scout/jobs/:id/candidates', ({ u, p, body }) => { need(u, 'scout'); const j = byId(S.scout.jobs, p.id, 'Job'), added = []; for (const r of (Array.isArray(body.resumes) ? body.resumes : [body]).slice(0, 200)) { const text = String(r.text || '').trim().slice(0, 30000); if (text.length < 40) continue; const name = String(r.name || text.split('\n')[0]).trim().slice(0, 60); if (j.candidates.some(c => c.text === text)) continue; const c = score(j, { id: uid('cd'), name, file: String(r.file || '').slice(0, 120), text, decision: null, addedAt: now() }); j.candidates.push(c); added.push(c); } if (!added.length) throw err(400, 'No new resume with readable text was found.'); audit(u, 'Added resumes', j.title, added.length + ' added'); return jobView(j, true); });
  on('PUT', '/api/scout/jobs/:id/candidates/:cid', ({ u, p, body }) => { need(u, 'scout'); const j = byId(S.scout.jobs, p.id, 'Job'), c = byId(j.candidates, p.cid, 'Candidate'); if (!['shortlist', 'hold', 'reject'].includes(body.decision)) throw err(400, 'Choose shortlist, hold or reject.'); const note = String(body.note || '').trim().slice(0, 300); if (body.decision === 'reject' && note.length < 5) throw err(400, 'Say why, in a few words. It is kept with the decision.'); c.decision = { value: body.decision, by: u.name, at: now(), note, score: c.score }; audit(u, 'Recorded a hiring decision', `${j.title}: candidate ${j.candidates.indexOf(c) + 1}`, body.decision + (note ? ': ' + note : '')); return jobView(j, true); });
  on('GET', '/api/scout/jobs/:id/export', ({ u, p }) => { need(u, 'scout'); const j = byId(S.scout.jobs, p.id, 'Job'), v = jobView({ ...j, blind: false }, true); audit(u, 'Exported a shortlist', j.title); return { name: 'shortlist-' + j.title.toLowerCase().replace(/[^a-z0-9]+/g, '-'), csv: csv([['Rank', 'Candidate', 'Score', 'Years', 'Decision', 'Decided by', 'Note', 'Reasons'], ...v.candidates.map(c => [c.rank, c.name, c.score, c.years, c.decision ? c.decision.value : '', c.decision ? c.decision.by : '', c.decision ? c.decision.note : '', c.reasons.map(r => (r.ok ? '+ ' : '- ') + r.text).join('; ')])]) }; });

  // ---------- Vanik MeasureBook: a bill of quantities where each line points at the drawing; corrections and revisions are kept
  const cleanLine = (b, n) => ({ id: uid('ln'), tag: String(b.tag || 'L' + n).slice(0, 12), desc: String(b.desc || '').trim().slice(0, 160), size: String(b.size || '').slice(0, 40), unit: ['m', 'nos', 'kg', 'sqm', 'set'].includes(b.unit) ? b.unit : 'nos', qty: Math.max(0, +b.qty || 0), rate: b.rate === '' || b.rate == null ? null : Math.max(0, +b.rate || 0), sheet: String(b.sheet || '').slice(0, 20), marks: Array.isArray(b.marks) ? b.marks : [], path: Array.isArray(b.path) ? b.path : null, was: null });
  const setView = (s, rev) => { const r = s.revs.find(x => x.rev === rev) || s.revs[s.revs.length - 1], amount = l => l.rate == null ? null : +(l.qty * l.rate).toFixed(2); return { id: s.id, name: s.name, kind: s.kind, read: s.read, rev: r.rev, revs: s.revs.map(x => x.rev), drawing: r.drawing || null, lines: r.lines.map(l => ({ ...l, amount: amount(l) })), total: r.lines.every(l => l.rate == null) ? null : +r.lines.reduce((a, l) => a + (amount(l) || 0), 0).toFixed(2), unpriced: r.lines.filter(l => l.rate == null).length, corrected: r.lines.filter(l => l.was).length, history: s.history.slice(0, 30), addedBy: s.addedBy, addedAt: s.addedAt }; };
  on('GET', '/api/measurebook', ({ u }) => { need(u, 'measurebook'); return { sets: S.mb.sets.map(s => { const v = setView(s); return { id: s.id, name: s.name, kind: s.kind, rev: v.rev, revs: v.revs.length, lines: v.lines.length, total: v.total, corrected: v.corrected, read: s.read, addedAt: s.addedAt }; }), reader: db.models.some(x => x.kind === 'vision' && x.status === 'serving') }; });
  on('POST', '/api/measurebook/sets', ({ u, body }) => { need(u, 'measurebook'); const name = String(body.name || '').trim().slice(0, 120); if (!name) throw err(400, 'Give the drawing set a name.'); const s = { id: uid('ds'), name, kind: String(body.kind || 'Piping').slice(0, 30), read: 'by hand', file: String(body.file || '').slice(0, 160), revs: [{ rev: 'A', lines: [], drawing: null }], history: [], addedBy: u.name, addedAt: now() }; S.mb.sets.unshift(s); audit(u, 'Added a drawing set', name, body.file ? 'File kept: ' + s.file : 'Lines entered by hand'); return setView(s); });
  const dset = id => byId(S.mb.sets, id, 'Drawing set');
  on('GET', '/api/measurebook/sets/:id', ({ u, p, q }) => { need(u, 'measurebook'); return setView(dset(p.id), q && q.get ? q.get('rev') : ''); });
  on('POST', '/api/measurebook/sets/:id/lines', ({ u, p, body }) => { need(u, 'measurebook'); const s = dset(p.id), r = s.revs.find(x => x.rev === body.rev) || s.revs[s.revs.length - 1]; if (!String(body.desc || '').trim()) throw err(400, 'Describe the item.'); const l = cleanLine(body, r.lines.length + 1); l.byHand = true; r.lines.push(l); s.history.unshift({ at: now(), by: u.name, text: `Added ${l.tag} ${l.desc}: ${l.qty} ${l.unit}` }); return setView(s, r.rev); });
  on('PUT', '/api/measurebook/sets/:id/lines/:lid', ({ u, p, body }) => { need(u, 'measurebook'); const s = dset(p.id), r = s.revs.find(x => x.lines.some(l => l.id === p.lid)); if (!r) throw err(404, 'Line not found'); const l = r.lines.find(x => x.id === p.lid); if (body.qty !== undefined && +body.qty !== l.qty) { const q2 = Math.max(0, +body.qty || 0); s.history.unshift({ at: now(), by: u.name, text: `${l.tag} ${l.desc}: ${l.qty} to ${q2} ${l.unit}` }); if (!l.was) l.was = { qty: l.qty, by: u.name, at: now() }; l.qty = q2; audit(u, 'Corrected a quantity', `${s.name}: ${l.tag}`, `${l.was.qty} to ${q2} ${l.unit}`); } if (body.rate !== undefined) l.rate = body.rate === '' || body.rate == null ? null : Math.max(0, +body.rate || 0); return setView(s, r.rev); });
  on('DELETE', '/api/measurebook/sets/:id/lines/:lid', ({ u, p }) => { need(u, 'measurebook'); const s = dset(p.id), r = s.revs.find(x => x.lines.some(l => l.id === p.lid)); if (!r) throw err(404, 'Line not found'); const l = r.lines.find(x => x.id === p.lid); r.lines = r.lines.filter(x => x !== l); s.history.unshift({ at: now(), by: u.name, text: `Removed ${l.tag} ${l.desc}` }); return setView(s, r.rev); });
  on('GET', '/api/measurebook/sets/:id/compare', ({ u, p }) => { need(u, 'measurebook'); const s = dset(p.id); if (s.revs.length < 2) throw err(409, 'There is only one revision.'); const a = s.revs[s.revs.length - 2], b = s.revs[s.revs.length - 1], tags = [...new Set([...a.lines, ...b.lines].map(l => l.tag))]; return { from: a.rev, to: b.rev, rows: tags.map(t => { const x = a.lines.find(l => l.tag === t), y = b.lines.find(l => l.tag === t); return { tag: t, desc: (y || x).desc, unit: (y || x).unit, was: x ? x.qty : null, now: y ? y.qty : null, change: !x ? 'added' : !y ? 'removed' : x.qty !== y.qty ? 'changed' : 'same' }; }).filter(r => r.change !== 'same') }; });
  on('GET', '/api/measurebook/sets/:id/export', ({ u, p, q }) => { need(u, 'measurebook'); const s = dset(p.id), v = setView(s, q && q.get ? q.get('rev') : ''); audit(u, 'Exported a bill of quantities', s.name, 'Revision ' + v.rev); return { name: 'boq-' + s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-rev-' + v.rev, csv: csv([['Item', 'Description', 'Size', 'Unit', 'Quantity', 'Rate', 'Amount', 'Sheet', 'Corrected by'], ...v.lines.map(l => [l.tag, l.desc, l.size, l.unit, l.qty, l.rate == null ? '' : l.rate, l.amount == null ? '' : l.amount, l.sheet, l.was ? l.was.by : '']), ['', '', '', '', '', 'Total', v.total == null ? '' : v.total, '', '']]) }; });

  // ---------- sample content for the demo workspace, added once, through the same functions the routes use
  function sample() {
    if (S.sampled || !DEMO) return; const owner = db.users.find(x => x.role === 'owner'), by = n => db.users.find(x => x.name.startsWith(n)) || owner, ago = (d, h = 0) => new Date(Date.now() - d * 864e5 - h * 36e5).toISOString(); S.sampled = true;
    for (const id of ORDER) if (!S.apps[id] && APPS[id].needsGb <= ctx.freeGb()) installApp(owner, id);
    const hr = db.collections.find(c => /HR/.test(c.name)), g = b => b + gstinDigit(b), A1 = g('27AABCS1429B1Z'), B1 = g('29AAACM1234C1Z'), C1 = g('24AAECA7788D1Z');
    if (S.apps.scout) S.apps.scout.access = { mode: 'restricted', teams: ['HR'], users: [] };
    if (S.apps.idp) {
      S.idp.docs.unshift(readDoc(by('Asha'), 'INV-2291 Shree Fasteners.pdf', `TAX INVOICE\nInvoice No: SF/26-27/2291\nInvoice Date: 02-10-2026\nSupplier: Shree Fasteners Pvt Ltd\nSupplier GSTIN: ${A1}\nBuyer GSTIN: ${B1}\nPO Number: PO-7841\n\nHex bolt M12 x 50, HSN 7318, 4,000 nos\n\nTaxable Value: 1,84,000.00\nGST: 33,120.00\nInvoice Total: 2,17,120.00`));
      S.idp.docs.unshift(readDoc(by('Asha'), 'INV-0457 Apex Industrial.pdf', `TAX INVOICE\nInvoice No: AI/0457\nInvoice Date: 04-10-2026\nSupplier: Apex Industrial\nSupplier GSTIN: ${C1}\nBuyer GSTIN: ${B1}\nPO Number: PO-7902\n\nSafety gloves, HSN 4015, 1,200 pairs\n\nTaxable Value: 96,000.00\nGST: 17,280.00\nInvoice Total: 1,14,280.00`));
      S.idp.docs.unshift(readDoc(by('Rohan'), 'EWB Shree Fasteners.pdf', `E-WAY BILL\nE-Way Bill No: 3410 8827 5512\nGenerated On: 03-10-2026\nFrom GSTIN: ${A1}\nTo GSTIN: ${B1.slice(0, 14)}9\nVehicle No: MH12 KT 4471\nValue of Goods: 2,17,120.00`));
      const ok = S.idp.docs[2]; ok.status = 'approved'; ok.approvedBy = 'Asha Verma'; ok.approvedAt = ago(0, 5);
    }
    if (S.apps.desk && hr) {
      S.desk.collectionId = hr.id; const T = (b, d, h) => addTicket(owner, b, ago(d, h));
      const t1 = T({ from: 'Kavita Rao', email: 'kavita.rao@example.com', subject: 'How long do I have to submit a travel claim?', body: 'I came back from the Pune plant visit last week. By when do I have to submit the travel claim, and what do I attach?', channel: 'mail' }, 0, 1);
      T({ from: 'Arjun Nair', email: 'arjun.nair@example.com', subject: 'Carry forward of unused leave', body: 'How many days of earned leave can I carry forward into next year?', channel: 'form', priority: 'low' }, 0, 6);
      const t3 = T({ from: 'Meera Shah', email: 'meera.shah@example.com', subject: 'Hotel limit for Mumbai', body: 'What is the hotel limit per night when travelling to Mumbai for a supplier audit?', channel: 'mail', priority: 'high' }, 2, 3);
      t3.messages.push({ at: ago(2, 1), who: 'agent', by: by('Neha').name, text: 'Hello Meera,\n\nThe limit for metro cities is in the travel policy. I have attached the section.\n\nRegards,\nNeha', sources: [] }); t3.status = 'solved'; t3.assignee = by('Neha').id; t3.solvedAt = ago(2, 1); t1.assignee = by('Neha').id;
    }
    if (S.apps.echo) S.echo.meetings.unshift(readMeeting(by('Rohan'), 'Vendor review: Shree Fasteners', `[00:05] Rohan Mehta: Thanks for joining. Shree Fasteners delivered eleven of twelve orders on time last quarter, and the one late order was held at their end for a missing test certificate.\n[00:41] Asha Verma: On payments, two invoices are on hold because the invoice total did not match the purchase order. Finance cannot release them until the supplier sends corrected invoices.\n[01:10] Imran Khan: The supply agreement fixes prices until 31 December 2026, so any revision they ask for now should wait for the renewal talks.\n[01:32] Rohan Mehta: Agreed. We decided to keep them as the primary supplier for fasteners for the next quarter.\n[01:50] Asha Verma: I will send the list of held invoices to the supplier by Friday.\n[02:04] Rohan Mehta: Imran will draft the renewal terms by 2026-10-30.\n[02:15] Imran Khan: Do we want a second source for M12 bolts?\n[02:22] Rohan Mehta: Yes. I will raise a request for quotes from two other suppliers by end of month.`, ago(1, 2)));
    if (S.apps.scout) {
      const j = { id: uid('job'), title: 'Procurement analyst', must: ['SAP', 'Excel', 'vendor management'], nice: ['Power BI', 'GST'], minYears: 3, blind: true, candidates: [], createdBy: by('Neha').name, createdAt: ago(3) };
      [['Ananya Gupta', 'Ananya Gupta\nananya.g@example.com | +91 98200 11223\n\nProcurement analyst with 5 years of experience in a manufacturing company. Runs purchase orders in SAP MM, builds spend reports in Excel and Power BI, and leads vendor management reviews every quarter. Familiar with GST input credit checks.'], ['Vikram Joshi', 'Vikram Joshi\nvikram.j@example.com\n\n4 years in sourcing for an auto parts maker. Daily user of SAP and advanced Excel (pivot tables, lookups). Negotiated annual contracts with twelve suppliers.'], ['Sara Thomas', 'Sara Thomas\n+91 99000 44556\n\nOperations executive, 2 years. Strong in Excel and Power BI dashboards. Supported vendor management for packaging suppliers. Learning SAP.'], ['Karan Malhotra', 'Karan Malhotra\nkaran.m@example.com\n\nFinance associate with 6 years of experience in accounts payable. Works in Tally and Excel. Handles GST returns.']].forEach(([name, text]) => j.candidates.push(score(j, { id: uid('cd'), name, file: name.toLowerCase().replace(' ', '-') + '.pdf', text, decision: null, addedAt: ago(2) })));
      S.scout.jobs.unshift(j);
    }
    if (S.apps.measurebook) {
      const M = [[40, 300], [160, 300], [160, 220], [300, 220], [300, 120], [430, 120], [430, 60], [560, 60]], M2 = [...M, [560, 140], [650, 140]], br = [[230, 220], [230, 290]];
      const mk = (main, n) => { const corners = main.slice(1, -1), L = (tag, desc, size, unit, qty, rate, marks, path) => cleanLine({ tag, desc, size, unit, qty, rate, marks, path, sheet: 'CW-101-01' }, 0), ends = [main[0], main[main.length - 1]];
        return [L('P1', 'Pipe, carbon steel, schedule 40', '100 NB', 'm', n ? 46 : 42.5, 1850, [], main), L('P2', 'Pipe, carbon steel, schedule 40 (branch)', '50 NB', 'm', 6.2, 780, [], br), L('E1', 'Elbow 90 degree, butt weld', '100 NB', 'nos', corners.length, 1240, corners), L('T1', 'Reducing tee', '100 x 50 NB', 'nos', 1, 2150, [br[0]]),
          L('V1', 'Gate valve, class 150, flanged', '100 NB', 'nos', 2, 18400, [[100, 300], [365, 120]]), ...(n ? [L('V2', 'Check valve, class 150, flanged', '100 NB', 'nos', 1, 16900, [[600, 140]])] : []),
          L('F1', 'Flange, weld neck, class 150', '100 NB', 'nos', n ? 10 : 8, 1650, [...ends, [88, 300], [112, 300], [353, 120], [377, 120], ...(n ? [[588, 140], [612, 140]] : []), [222, 290], [238, 290]]), L('G1', 'Gasket, spiral wound', '100 NB', 'nos', n ? 10 : 8, 310, []), L('B1', 'Stud bolt with two nuts', 'M16 x 90', 'nos', n ? 80 : 64, 62, []),
          L('S1', 'Pipe support, shoe type', '100 NB', 'nos', n ? 8 : 7, 2900, [[70, 300], [130, 300], [200, 220], [270, 220], [330, 120], [400, 120], [495, 60], ...(n ? [[605, 140]] : [])])]; };
      S.mb.sets.unshift({ id: uid('ds'), name: 'Cooling water line CW-101', kind: 'Piping', read: 'sample', file: 'CW-101 isometric.pdf', revs: [{ rev: 'A', lines: mk(M, 0), drawing: { main: M, branch: br } }, { rev: 'B', lines: mk(M2, 1), drawing: { main: M2, branch: br } }], history: [{ at: ago(1), by: 'Rohan Mehta', text: 'Revision B received: line extended to the heat exchanger' }], addedBy: 'Rohan Mehta', addedAt: ago(4) });
    }
  }

  return { usedGb, boot, sample, canUse, apps: () => ORDER.filter(id => S.apps[id]).map(id => ({ id, name: APPS[id].name, access: S.apps[id].access })) };
};
